### PR TITLE
understands units and adds resolution to tif

### PR DESCRIPTION
**Pull request by to266**
https://github.com/hyperspy/hyperspy/issues/838

The (slightly tricky) resolution in tif files.. Experimental, so to say.
As an alternative, without changing the current code the user can supply the resolution directly:

```python
s.save('myfile.tif', resolution = (0.3, (1, 100)))
```
Where `resolution` is a tuple of two elements, where each can be:
 - a float
 - a tuple of two integers, if a rational number is given

### Need:
 - [ ] tests
 - [ ] documentation

### CODE REVIEW

**Comment by thomasaarholt** [comment]
Can you briefly describe how `resolution` should be formatted? Is 0.3 your pixel size? Units? And what is the second one?

**Comment by tjof2** [comment]
Perhaps worth noting the discussion about how ImageJ saves its units in TIFF files? http://imagej.1557.x6.nabble.com/Spatial-and-density-calibration-from-TIFF-files-to-ImageJ-td5014677.html

**Comment by to266** [comment]
Sorry for the too-quick reply.

@thomasaarholt , `resolution = (resolution_x, resolution_y)`, where each is in pixels / some_unit. In the official tiff specification those are the only two resolutions that can be specified, and the choice of units is constrained to ('None', 'cm' and 'inch'). However we use a library to write the files, where the unit is constrained to be an inch and cannot be changed.

@tjof2 thanks for the links. From what I gather, my implemented way is constrained, however the only universal / official way? Otherwise we would have to mimic one of the ImageJ plugins / some other software

**Comment by tjof2** [comment]
@to266 I think so - I guess the options are either matching the ImageJ tag, or matching the [relevant tag in the OME-TIFF specification](https://www.openmicroscopy.org/site/support/ome-model/ome-tiff/)

**Pull request closed without merging**
