### PR TITLE
New det efficiency

### PR DESCRIPTION
**Pull request by pburdet**
Compute the detector efficiency from the layers. The efficiency is calculated by estimating the absorption of the different the layers in front of the detector.

Merge into #481 and #471

``` python

        >>> s = signals.EDSTEMSpectrum(np.ones(1024))
        >>> s.axes_manager.signal_axes[0].scale = 0.01
        >>> s.axes_manager.signal_axes[0].units = "keV"
        >>> s.detetector_efficiency_from_layers()
        <EDSTEMSpectrum, title: Detection efficiency, dimensions: (|1024)>

```
## TO DO
- [ ] doc

### CODE REVIEW

**Comment by francisco-dlp** [comment]
Is anybody available to have a look at this?

**Comment by sem-geologist** [comment]
This looks interesting. It could be useful for bruker's formats, which always attach detector and window information. Would estimating the window efficiency differ a lot from this det. efficiency estimation?
This probably should be merged before trying to implement any quantification of SEM EDS...

**Comment by ericpre** [comment]
@sem-geologist, please feel free to pull this branch and to make a new PR! :wink:

**Comment by ZanettaPM** [comment]
I never view this PR before but it's entirely related to #1835 
Quite interresting ! We talked about that few days ago with @sem-geologist 
Ofc this function only work for bruker format right ? 
In my PR i've created a dictionnary which contain the det.efficiency of classical detector to obtain det.efficiency even if the format is not bruker but this is a more precise way to modelise the bakcground.

**Comment by tjof2** [comment]
See #2535

**Pull request closed without merging**
