### PR TITLE
Fix for dm3 reader to properly assign metadata in multi-signal files

### LINKED ISSUE #2296: BUG: dm3 reader discards important original metadata in files that contain multiple signals
# Issue description

Came across a bug in the .dm3 reader when trying to parse the metadata of a file containing multiple signals ([BF1HAADF20016.dm3.zip](https://github.com/hyperspy/hyperspy/files/4021211/BF1HAADF20016.dm3.zip)).

Essentially, this file contains both an image and a profile plot within the same display:

image

HyperSpy reads file into a list of length 2, with the following signal axis properties:

```
> s[0]
<Signal1D, title: Plot, dimensions: (512|512)>

> s[0].axes_manager
<Axes manager, axes: (512|512)>
            Name |   size |  index |  offset |   scale |  units 
================ | ====== | ====== | ======= | ======= | ====== 
               y |    512 |      0 |      -0 |   0.018 |     nm 
---------------- | ------ | ------ | ------- | ------- | ------ 
               x |    512 |        |      -0 |   0.018 |     nm 

> s[1]
<Signal1D, title: Plot, dimensions: (|512)>

> s[1].axes_manager
<Axes manager, axes: (|512)>
            Name |   size |  index |  offset |   scale |  units 
================ | ====== | ====== | ======= | ======= | ====== 
---------------- | ------ | ------ | ------- | ------- | ------ 
               x |    512 |        |      -0 |       1 |        
```

The axial information is incorrect, as the first signal should be a Signal2D with two signal dimensions (it is a HAADF image, but is read with the same information as the second signal).

Some more info:

```
> s[0].metadata
├── General
│   ├── original_filename = BF1HAADF20015.dm3
│   └── title = Plot
└── Signal
    ├── Noise_properties
    │   └── Variance_linear_model
    │       ├── gain_factor = 1.0
    │       └── gain_offset = 0.0
    ├── binned = False
    ├── quantity = Intensity
    └── signal_type = 

> s[1].metadata
├── General
│   ├── original_filename = BF1HAADF20015.dm3
│   └── title = Plot
└── Signal
    ├── Noise_properties
    │   └── Variance_linear_model
    │       ├── gain_factor = 1.0
    │       └── gain_offset = 0.0
    ├── binned = False
    ├── quantity = Intensity
    └── signal_type = 
```

# Initial investigations

## Metadata 

It looks like this is caused (in part) with how the metadata is stored for multi-signal images around [line 1035](https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/io_plugins/digital_micrograph.py#L1035-L1037) of the DM reader. After reading all the metadata as a dictionary, the code nukes `dm.tags_list['ImageList']` and then rebuilds it for each signal found in the file. The problem on line 1037 is that for every signal, the "sub-signal" dictionary is stored into the same place (`dm.tags_dict['ImageList']['TagGroup0']`), and since the dictionary is not copied, it is overwritten in `imd`, so the last signal to be read overwrites the metadata of all the preceding ones. This explains why the metadata structure for `s[0]` and `s[1]` is the same above.

This is simple enough to fix by making sure that a deepcopy of `dm.tags_dict` is used when adding to `imd` each iteration through that loop (and same with the regular metadata as well).

### Fix for metadata

My initial changes (to be submitted in a PR) fix the metadata:

```
> s[0]
<Signal1D, title: Plot, dimensions: (512|512)>

> s[0].metadata
├── Acquisition_instrument
│   └── TEM
│       ├── Stage
│       │   ├── tilt_alpha = 0.001951998453075299
│       │   ├── x = 0.07872150000000001
│       │   ├── y = 0.100896
│       │   └── z = -0.0895279
│       ├── acquisition_mode = STEM
│       ├── beam_current = 0.0
│       ├── beam_energy = 300.0
│       ├── camera_length = 77.0
│       ├── dwell_time = 3.2400001525878905e-05
│       ├── magnification = 10000000.0
│       └── microscope = <censored>
├── General
│   ├── authors = <censored>
│   ├── date = 2019-12-10
│   ├── original_filename = BF1HAADF20016.dm3
│   ├── time = 15:32:41
│   └── title = HAADF
├── Sample
│   └── description = <censored>
└── Signal
    ├── Noise_properties
    │   └── Variance_linear_model
    │       ├── gain_factor = 1.0
    │       └── gain_offset = 0.0
    ├── binned = False
    ├── quantity = Intensity
    └── signal_type = 

>s[1]
<Signal1D, title: Plot, dimensions: (|512)>

> s[1].metadata
├── General
│   ├── original_filename = BF1HAADF20016.dm3
│   └── title = Plot
└── Signal
    ├── Noise_properties
    │   └── Variance_linear_model
    │       ├── gain_factor = 1.0
    │       └── gain_offset = 0.0
    ├── binned = False
    ├── quantity = Intensity
    └── signal_type = 
```

but do nothing for the Signal dimension issue. 

## Signal axes definitions

As mentioned previously, the first signal in the file should be a `Signal2D` (size 512 x 512), but instead is read as `Signal1D` The changes mentioned above fix this issue, as well.

### PR DESCRIPTION
**Pull request by jat255**
### Description of the change

This is a small change that makes the dm3 reader use a deepcopy of the metadata dictionaries during file loading if there are multiple signals defined in the file. This fixes #2296 

### Progress of the PR
- [x] Change implemented (can be split into several points),
- [x] add tests
- [x] ready for review.

All existing tests pass. I can include the example file I've been using to test and write up a test case for it, but I'm not sure if we're okay including the file (it's a couple of MB)

### CODE REVIEW

**Comment by francisco-dlp** [comment]
Good catch! It looks good to me, but it would be good adding a test (using e.g. the file in https://github.com/hyperspy/hyperspy/issues/2296), to prevent future regressions.

**Comment by francisco-dlp** [comment]
It would also be nice to add some comments in the code explaining why deepcopying is needed.

**Comment by jat255** [comment]
Ok, added some comments and some tests for the added test file. All the IO tests pass locally, so should be good to go.

**Comment by jat255** [comment]
Not sure why my tests fail but other recent PRs pass... All the IO/dm3 tests are passing, though. Looks like the failures are elsewhere.

**Comment by ericpre** [comment]
Some tests are failing following the releases of the last versoin of the scipy and pint libraries. These failures are fixed in #2295 and #2298.

**Pull request merged**
