### PR TITLE
added first iteration of anaconda hyperspy environment (again)

### PR DESCRIPTION
**Pull request by to266**
Seems to run fine. 

run like so:
```bash
conda env create -f anaconda_hyperspy_environment.yml
source activate hyperspy
```

It has the drawback that every time before using hyperspy the user has to activate the environment, but at least it stays consistent.... And the user can use it as root, env, if s(he) chooses to

### CODE REVIEW

**Comment by jrminter** [comment]
Thanks. Worked nicely for me.

**Comment by francisco-dlp** [comment]
Couldn't we limit the dependencies to the actual dependencies? i.e. no mayavi, pandas etc...

**Comment by to266** [comment]
Done, I think

**Comment by francisco-dlp** [comment]
Just a little bit of documentation in the User Guide is missing.

**Comment by to266** [comment]
Added

**Comment by francisco-dlp** [comment]
The download link should not point to the master branch as the dependencies might be different from those of the latests pypi release.

**Comment by to266** [comment]
Done, points to 0.8.x

**Pull request merged**
