### PR TITLE
BUGFIX: Proposed patch to allow Hyperspy to run with wx3 installed

### PR DESCRIPTION
**Pull request by jat255**
Added (ugly) patch to component.py to allow hyperspy to run with the qt4 toolkit if wx3 is installed

NB: this does not provide compatibility with wx 3, but merely prevents its presence from bombing the whole program when using the qt4 toolkit.

Resolves https://github.com/hyperspy/hyperspy/issues/435

### CODE REVIEW

**Comment by vidartf** [comment]
I'd rather put in a complete map (qt/tk/wx/etc) somewhere appropriate, preferably a place where it would always be loaded before traitsui code is run (I'm guessing it doesn't like switching toolkit in the middle of a run). Unless there is any scenario where anyone would not want them to be the same?

**Comment by vidartf** [comment]
I see from #435 that the place hyperspy tries to set it didn't do the trick. I remember debugging that trying to solve a very similar problem with the UI, but there I had the luxury of setting it before loading anything from hyperspy/traits (does that work for you?).

**Comment by jat255** [comment]
What do you mean by "setting it before loading anything"? It appears that this is attempted in bin/hyperspy, but it doesn't seem carry through into when component.py is executed. 

As is, the toolkit is not switched at all during execution. It only explicitly sets the toolkit to qt4 if the matplotlib backend is determined to be qt. If it is set to wx, nothing happens. 

Since the only two guis for matplotlib are qt4 and wx, would a method at the beginning of component.py that gets the backend from matplotlib and then explicitly sets the backend to qt4 or wx (before traitsui is loaded) be acceptable?

**Comment by francisco-dlp** [comment]
Possibly this is fixed by #584, what do you think @jat255?

**Comment by jat255** [comment]
Yup, this seems to be okay now given #584, so I'll close this ugly hack :smile:

**Pull request closed without merging**
