### PR TITLE
ENH: Generalising 'map'

### PR DESCRIPTION
**Pull request by dnjohnstone**
Working towards a more generalised 'map' function as discussed in #496.

At present 'map' overwrites the original signal that is being acted on and can only accept functions for which the output dimension is the same as the original signal dimension. This is good in terms of memory usage and speed but not so good if you want to apply a function which returns some other dimension or if you want to tweak the parameters of that function.

Here, I have implemented a second approach based on first generating a structured array with dimensions equal to the navigation dimensions and iterating over that. This approach is used elsewhere in the source code and is potentially very general as the output of the function to be mapped can now have any output dimension and furthermore may be ragged. The downside of the structured array is that it's not very compatible with indexation within HyperSpy (though it is fully indexable).

Next step: Enable the output to be returned as a HyperSpy signal when the output dimensions are not ragged.

### CODE REVIEW

**Comment by to266** [comment]
https://github.com/hyperspy/hyperspy/pull/737

Will update in a second to be up-to-date. 

Sorry for creating a very similar branch, did not know about this one at the time. Have you actually user yours in any task? If so, could you see if mine (once updated) is good enough? Looks like there is slightly more done in #737, so fewer things to do next

**Comment by dnjohnstone** [comment]
@to266 Happy to work from #737  - I agree that you've got more done there! As you know, I'm currently going through the obligatory baptism of fire regarding what's actually required to consider something finished for inclusion in HyperSpy...

If we're agreed - I'll close this pull request and then (if it looks like it's worth it) will try and include the idea I had here into #737... Sound ok?

**Comment by to266** [comment]
Yup, go for it. I'm happy to add things if something is lacking any way

**Comment by dnjohnstone** [comment]
Closed in favour of #737

**Pull request closed without merging**
