### PR TITLE
New: set EELSCLEdge onset

### PR DESCRIPTION
**Pull request by magnunor**
As discussed in https://github.com/hyperspy/hyperspy/issues/487 there should be some better way to set the onset of EELSCLEdges.

This implementation uses the routine described in https://github.com/hyperspy/hyperspy/issues/487 and seems to work nicely for the L-edges for the transition metals like Mn, Fe and Ti.

Routine for fitting a Manganese L23-edge, see the image below for the different energy ranges:

set_edge_onset

```python
s = load("some_spectrum.hdf5")
s.add_elements(['Mn',])
s.set_microscope_parameters(convergence_angle=24., collection_angle=26.)
ll = load("lowloss.hdf5")
m = create_model(s, ll=ll)
m.set_coreloss_edge_onset(Mn_L3) # (1) Just before the L3 onset and a little past the peak 
m.set_coreloss_edge_onset(Mn_L2) # (2) Just before the L2 onset and a little past the peak
m.set_signal_range() # (3) About 30 eV before the onset to just in front of the onset
m.add_signal_range() # (4) About 3 eV right after the L2, at the lowest point
m.multifit()
m.reset_signal_range
```

Result: set_edge_onset_result

I can probably automate this even more, is I've done here: https://gist.github.com/magnunor/47c8a8b3b69f4370229e . But I think having a separate function like the one in this PR would be useful.

When using only_current=False with the interactive mode, the process is very slow due to the plot windows updating for every change in position. Is there some way to suppress this?

Todo:
- [x] documentation
- [x] tests

### CODE REVIEW

**Comment by vidartf** [comment]
> When using only_current=False with the interactive mode, the process is very slow due to the plot windows updating for every change in position. Is there some way to suppress this?

There is an ongoing PR/Issue for this, which will probably be sorted by events and events suppression. For now the most common workaround is simply to do the calculation on a deepcopy with the same data (`s._deepcopy_with_new_data(s.data)`). This deepcopy will then have a new `AxesManager` that is not connected to the plot. However, for your case, I guess that means that the results of the fit will sit on the wrong `Signal`. Maybe you can temporarily swap the `AxesManager` on your signal (with a copy), do the fit, then swap back?

**Comment by magnunor** [comment]
I added some tests and documentation, but I'm not certain if the explanation in the docstring is really understandable. 

In any case the function itself seems to work nicely, except for the GUI iterating over every position when using the GUI version of the function. Has the event suppression mentioned by vidartf been merged?

**Comment by francisco-dlp** [comment]
Very nice. It'll be good to test this against the spectra in the EELSdb.

2015-05-08 22:23 GMT+01:00 magnunor <notifications@github.com>:

**Comment by magnunor** [comment]
I merged the current master into the branch, and everything seems to be working nicely.

Should be ready for review.

**Pull request closed without merging**
