### PR TITLE
BUG-FIX DM3 timeformat

### PR DESCRIPTION
**Pull request by thomasaarholt**
Some DM3 files have a different format of their time tag. I’ve changed the `datetime.strptime` which takes a fixed formatter to `dateutil.parser`, which parses the date. It works for both time formats.

### CODE REVIEW

**Comment by thomasaarholt** [comment]
Ignore all the odd commits, the code is correctly changed.

**Comment by ericpre** [comment]
This is something that I fixed in #1282, but without using dateutil.parser. Since your fix seems to be more simple and much nicer, I guess this is better to keep this one!
Could you please add a few tests? You could use the test dm files added in #1282 and saved with different locale. These are working OK after fixing the `_get_time` function, same than that you did with `_get_date`.

**Comment by thomasaarholt** [comment]
Ok, cool. Could I ask you to walk me through a bit with the tests? I've got very little experience with writing tests in general, so I'm a bit unsure on how to go forward.

**Comment by ericpre** [comment]
This is maybe not the best example but I have just generated dm files from an online GMS with different locale... and tested if these files are loaded nicely using this [test](https://github.com/hyperspy/hyperspy/pull/1282/files#diff-371868400621ecb704a1d7ecadc552e0L175)!

Maybe it would be more simple to merge both pull requests together. Obviously they will be a conflict, but it should be easy to solve!
Hope this help! :)

**Comment by ericpre** [comment]
I will try to make a pull request to yours! Let see if I can get it to work correctly...

**Comment by ericpre** [comment]
I suspect this should be pushed to RELEASE_next_patch, because it's a bug fix!

**Comment by thomasaarholt** [comment]
There, that should do it.

**Comment by thomasaarholt** [comment]
Anything necessary to merge this?

**Comment by magnunor** [comment]
Agreed, should be merged asap.

There seems to be changes not related to fixing the "wrong-time-format-bug", for example changes in `hyperspy/drawing/image.py`.

If you sort that out, I'll review the pull request.

**Comment by thomasaarholt** [comment]
This was a bit of a pain in the ass. Since I made changes on my branch made from RELEASE_next_minor, but committed them to RELEASE_next_patch (on @ericpre's suggestion), it's included a load of changes that weren't supposed to be merged through this pull request...

For now I'm manually editing them out until this pull request looks correct.

**Comment by magnunor** [comment]
Hmmm, an easier way would be to make a new branch, then cherry-pick the commits you want.

This would also keep the commit history a lot cleaner.

**Comment by thomasaarholt** [comment]
You're right, this is awful. How do I go about cherry-picking?

edit: Found it online.

**Comment by thomasaarholt** [comment]
For now I'm creating a new branch on my local repo from RELEASE_new_patch.

That is, unless you think this should be in RELEASE_new_minor.

I need to go back and look at what the different branches are supposed to contain.

**Comment by magnunor** [comment]
Bug-fixes = hyperspy:RELEASE_next_patch

**Comment by thomasaarholt** [comment]
Ok, but how often does next_patch get merged into next_minor?

**Comment by thomasaarholt** [comment]
Closed and replaced by #1311.

**Pull request closed without merging**
