### PR TITLE
Add download badges and fix azure pipeline badge

### PR DESCRIPTION
**Pull request by ericpre**
I have just came across https://pepy.tech/project/hyperspy and interestingly, there is a non-negligible number of download of old version of hyperspy 1.5.1 and 1.5.2...

### CODE REVIEW

**Review by tjof2 — APPROVED** [review]

**Comment by francisco-dlp** [comment]
I find the download badges confusing: the monthly one counts pypi downloads and the total one points to total downloads in conda-forge one...

**Comment by tjof2** [comment]
Good point, I didn't spot that - agreed

**Comment by ericpre** [comment]
What would be less confusing? To remove the total downloads from anaconda cloud?

**Comment by francisco-dlp** [comment]
Actually, since we cannot count downloads reliably (for that we would need to aggregate pypi, conda, bundle, linux distros...), my personal preference it not to highlight this information. New potential users who are trying to judge the size of the hyperspy community before investing their time in learning how to use it can make up their minds by looking at  e.g. GH stars and used by.

That said, as @ericpre pointed out, monitoring pypi downloads can be useful to detect issues with the current version (it is indeed surprising that the 1.5.* remain popular, may it be because 1.6 require newer versions of some libraries?

**Comment by tjof2** [comment]
Also recall that e.g. pyxem hasn't moved to 1.6.0 due to the histogram bug, that's waiting on the 1.6.1 release.

**Comment by ericpre** [comment]
> Actually, since we cannot count downloads reliably (for that we would need to aggregate pypi, conda, bundle, linux distros...), my personal preference it not to highlight this information. New potential users who are trying to judge the size of the hyperspy community before investing their time in learning how to use it can make up their minds by looking at e.g. GH stars and used by.
> 
> That said, as @ericpre pointed out, monitoring pypi downloads can be useful to detect issues with the current version (it is indeed surprising that the 1.5.* remain popular, may it be because 1.6 require newer versions of some libraries?

Agreed, my thought process was similar and the is the reason why I added this link (https://pepy.tech/project/hyperspy) in the `README.rst` is to make it more accessible and "discoverable".
While I was at it, I also added the link to anaconda cloud but got side track and added the download from anaconda cloud too... and indeed, all these download numbers are misleading.

Shall we keep the https://pepy.tech/project/hyperspy badge and remove the anaconda download one?

**Comment by francisco-dlp** [comment]
What about adding it to the devel guide, with a little explanation of the limitations and its usefulness for developers? Everything in README makes it into the pypi frontpage and the zotero DOI page, so I think that it is better to keep unreliable info aside.

**Pull request merged**
