### PR TITLE
Update warning for decomposition of non-float types

### PR DESCRIPTION
**Pull request by jat255**
Per [discussion](https://gitter.im/hyperspy/hyperspy?at=5b48cba9c2d95c60f4d7777a) on gitter chat... change the warning for decomposition to a logger error, since in this situation HyperSpy does something different than what the user expects.

### CODE REVIEW

**Comment by francisco-dlp** [comment]
Personally I had in mind a proper error for this e.g. ``raise TypeError``

**Comment by jat255** [comment]
Agreed and changed.

**Comment by francisco-dlp** [comment]
Thanks. Could you add a test for this? A simple one, just testing that the right dtype does not raise an error while the wrong one does.

**Comment by jat255** [comment]
Sure thing; done

**Pull request merged**
