### PR TITLE
BUGFIX: Line2DROI in  #1330

### PR DESCRIPTION
**Pull request by thomasaarholt**
This is a bug which stems from the navigator dimension swapping between hyperspy signals and numpy data shapes.

nd.map_coordinates is taking x and y coordinates for the data shape, which is indexed y, x. This PR flips the data input, which I think is the right way around to do this.

### CODE REVIEW

**Comment by francisco-dlp** [comment]
Looks good! It'll be nice to  add an unittest to check that the issue doesn't come back. The example in #1330 could serve as inspiration:

```python


import hyperspy.api as hs
import numpy as np
im = hs.signals.Signal1D(np.zeros((100, 100, 1024)))
im.axes_manager[0].offset = 0.7
im.axes_manager[0].scale = 0.5
im.data[:50, 50:, 500:600] = 1
line_roi = hs.roi.Line2DROI(10, 20,  30 ,40 ,2)

```

**Comment by vidartf** [comment]
It seems there is already a unit test for this, which is the one that is currently failing. I think simply updating the expected values in that test should be enough (maybe adding offset and scale as suggested by @francisco-dlp)?

**Comment by vidartf** [comment]
PS the test in question is here: https://github.com/thomasaarholt/hyperspy/blob/9c5e27fabcaa1070ef2debf0e522abd9933ce553/hyperspy/tests/utils/test_roi.py#L111

**Comment by francisco-dlp** [comment]
This is a serious bug that this PR fixes, @thomasaarholt, are you available to modify the test as suggested above? If not, one of us could do it.

**Comment by thomasaarholt** [comment]
I really am not. I've got a job interview on Thursday and am working late nights on my thesis. I would really appreciate it if someone else could modify the test.

**Comment by francisco-dlp** [comment]
thomasaarholt/hyperspy#6

**Pull request merged**
