### PR TITLE
Update residual line when model line is changed.

### PR DESCRIPTION
**Pull request by HanHsuanWu**
Currently, the plotted residual is not being updated whenever the model line changes.
So I added update for model._residual_line whenever mode._model_line is being updated.

```
import numpy as np
import hyperspy.api as hs

# Random Signal1D signal
s = hs.signals.Signal1D(data=np.random.random((2, 2, 1024)), 
                        axes=[{'name': 'x', 'size': 2}, 
                              {'name': 'y', 'size': 2}, 
                              {'name': 'sig', 'size': 1024}])
# Model object with Polynomial component
m = s.create_model()
# Polynomial=hs.model.components1D.Polynomial()
# m.append(Polynomial)
m.append(hs.model.components1D.PowerLaw())
m.plot(plot_residual=True)
```

### CODE REVIEW

**Comment by jlaehne** [comment]
I think it would make sense to rebase this on `release_next_PATCH`. Tests are failing.

**Comment by ericpre** [comment]
@HanHsuanWu, in case you are familiar with rebasing, there are some basic instructions in the [developer guide](https://hyperspy.org/hyperspy-doc/dev/dev_guide/git.html#changing-base-branch) on how to rebase - you may find more detailed instructions elsewhere online but this is not always very clear when not familiar with git!
It is not always straighforward to rebase correctly and quite often it is easier to start from scratch with an up to date branch and cherry-pick the commits or copy and paste the code manually.

The difference between the [various branches](https://hyperspy.org/hyperspy-doc/dev/dev_guide/git.html#semantic-versioning-and-hyperspy-main-branches) that we use is explained in the developer guide too.

**Comment by HanHsuanWu** [comment]
Thanks guys I opened a new commit in #3355.

**Comment by ericpre** [comment]
Closing in favour of #3355.

**Pull request closed without merging**
