### PR TITLE
BUGFIX DTB _double_lines when using "as_dictionary"

### PR DESCRIPTION
**Pull request by to266**
https://github.com/hyperspy/hyperspy/pull/751

### CODE REVIEW

**Comment by francisco-dlp** [comment]
Could you rebase it to make travis happy?

**Comment by to266** [comment]
but https://github.com/hyperspy/hyperspy/pull/751 is merged to master, not 0.8.x.... Or is master already with the updated travis build?

**Comment by francisco-dlp** [comment]
Yes it is. I try to merge 0.8.x into master every time something is merged into it. We should look into automatizing this though...

**Comment by to266** [comment]
But it is not:
https://github.com/hyperspy/hyperspy/blob/master/.travis.yml

**Comment by francisco-dlp** [comment]
Refresh ;)

**Comment by to266** [comment]
Done and passed

**Pull request merged**
