### PR TITLE
Fix future and deprecation warnings

### PR DESCRIPTION
**Pull request by ericpre**
I have been checking numba 0.53.0rc1 and python 3.9 and both works fine!

### Progress of the PR
- [x] Remove use of deprecated aliases, see https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
- [x] Remove scikit-learn decrepation warning, which is not necessary anymore since scikit-learn 0.22
- [x] Filter scikit-learn future warning about changing defaults in nmf, see https://scikit-learn.org/dev/whats_new/v0.24.html#sklearn-cross-decomposition
- [x] Close file in phenom reader (`ResourceWarning: unclosed file`)
- [x] Fix DBSCAN future warning
- [x] add entry to `CHANGES.rst` (if appropriate),
- [x] ready for review.

### CODE REVIEW

**Comment by ericpre** [comment]
@hyperspy/developers, anyone to review this PR?

**Comment by jlaehne** [comment]
There are two codecov warnings in the diff, which might be fixed along the way if not too difficult. Otherwise, looks good!
(just stumbled across the numpy warnings a few days ago myself, but you were faster in fixing them)

**Comment by ericpre** [comment]
> There are two codecov warnings in the diff, which might be fixed along the way if not too difficult. Otherwise, looks good!
> (just stumbled across the numpy warnings a few days ago myself, but you were faster in fixing them)

Yes, I have just noticed the github notification about the coverage, they are quite good! I don't know why they now appear and not before, thought!

**Comment by jlaehne** [comment]
Probably a new feature and because these lines were now changed, they appear?

**Comment by ericpre** [comment]
Yes, something must have changed in github or codecov recently. When we moved to github actions, I was expected these notifications to work in order to avoid having to go to the codecov website but it wasn't... and I thought that I would leave it for latter!

**Comment by jlaehne** [comment]
OK, once the tests pass ;-)

**Pull request merged**
