### PR TITLE
Added FastICA external link to .blind_source_separation()

### PR DESCRIPTION
**Pull request by thomasaarholt**
Linking to http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.FastICA.html in the documentation.

### CODE REVIEW

**Comment by francisco-dlp** [comment]
Nice. Could you send it to the maintenance branch, 0.8.x?

**Comment by thomasaarholt** [comment]
I tried now, but I'm not sure if it worked. I figured I couldn't move this PR to the other branch, so I went to the other branch and tried to do the commit there. Did that work?

**Comment by francisco-dlp** [comment]
Normally you could branch from `0.8.x`, cherry-pick or simply recreate the commit, push it to your hspy report and send another PR.

**Comment by dnjohnstone** [comment]
shall we just save this for 1.0.0 given it's here now and that there will be a big set of documentation improvements coming together then? If so, this would be fine to merge.

**Pull request merged**
