### PR TITLE
Remove vendored tifffile library

### PR DESCRIPTION
**Pull request by ericpre**
Now that tifffile packages on pypi and conda-forge are consistent, we can remove the vendored tifffile library and add it as dependency.

### Progress of the PR
- [x] Remove vendored tifffile library,
- [x] add tifffile as dependency in `setup.py`,
- [x] update CI,
- [x] ready for review.

### CODE REVIEW

**Comment by jat255** [comment]
I just tried installing via `conda install hyperspy -c conda-forge`, and `tifffile` was not pulled in as a dependency. Is this an error in the conda feedstock?

**Comment by jat255** [comment]
Paging @francisco-dlp

**Comment by francisco-dlp** [comment]
We haven't released this code yet.

**Comment by jat255** [comment]
Perhaps I don't understand well how the conda installation works, but if I do `conda install hyperspy -c conda-forge`, does it pull directly from the latest commit, then? As that's our primary way of telling people to install HyperSpy in the docs, if this method doesn't get to a working installation, then that's a pretty major problem, and we should either push out a release, or adjust the conda method (or instructions) such that it pulls the latest "stable" tag.

**Comment by jat255** [comment]
Well I guess nevermind... The following worked fine for me, so I must have had something messed up in my environment. Forget I said anything.

```
$ conda create -n hyperspy_test python=3.7
$ conda activate hyperspy_test
$ conda install -c conda-forge hyperspy

$ conda list | grep hyperspy
hyperspy                  1.5.2                    py37_0    conda-forge
hyperspy-base             1.5.2            py37h516909a_0    conda-forge
hyperspy-gui-ipywidgets   1.2                        py_2    conda-forge
hyperspy-gui-traitsui     1.2                        py_0    conda-forge

$ python -c "import hyperspy.api as hs; import hyperspy; print(hyperspy.__version__)"
1.5.2
```

I think when I was testing, I might have been in my local hyperspy directory, which would have overridden the environment-installed version.

**Pull request merged**
