### PR TITLE
Remove automatically generated API rst files

### PR DESCRIPTION
**Pull request by francisco-dlp**
Currently git tracks the files in `hyperspy/doc/api`. However, these are automatically generated by sphinx apidoc, so I don't think that there is any need to track them.

### CODE REVIEW

**Comment by vidartf** [comment]
Maybe add folder to .gitignore as well?

**Comment by dnjohnstone** [comment]
is this just waiting for the suggestion from @vidartf to be implemented?

**Comment by francisco-dlp** [comment]
Interestingly, it seems that [it's already there](https://github.com/hyperspy/hyperspy/blob/0.8.x/.gitignore#L28). Can we merge this?

**Comment by vidartf** [comment]
Aside from noting the interesting new failure of Travis (timeout on save of long list), I'm ok with it :)

**Pull request merged**
