### PR TITLE
Fix ReadTheDocs API docs

### LINKED ISSUE #1908: Autogenerated API doc in RtD
Currently, the API docs are not available in HyperSpy's RtD documentation. In https://github.com/rtfd/readthedocs.org/issues/1139#issuecomment-312626491 there is the code that we need to fix this.

### PR DESCRIPTION
**Pull request by francisco-dlp**
Fixes #1908

### CODE REVIEW

**Comment by francisco-dlp** [comment]
This is working fine locally with sphinx 1.7.7. However it breaks [like this](https://readthedocs.org/projects/hyperspy/builds/7701605/) with sphinx 1.7.8

**Comment by francisco-dlp** [comment]
I just opened an issue about it https://github.com/sphinx-doc/sphinx/issues/5361

**Comment by francisco-dlp** [comment]
This is now building the API properly (see [example](https://hyperspy.readthedocs.io/en/latest/user_guide/)), so it is ready for review.

**Comment by ericpre** [comment]
Well, I don't know how the doc build works but it seems to do the job, so we will trust you on that one! :D

**Pull request merged**
