### PR TITLE
Release v1.5.2

### PR DESCRIPTION
**Pull request by francisco-dlp**

### CODE REVIEW

**Comment by ericpre** [comment]
#2250

**Comment by francisco-dlp** [comment]
@hyperspy/developers, are we ready to release?

**Comment by ericpre** [comment]
Yes, I think so!

**Comment by ericpre** [comment]
Not sure if there is time to finish #2185.

**Comment by francisco-dlp** [comment]
I think that #2185 is better suited for 1.6 since it is a new feature.

**Pull request merged**
