### PR TITLE
Remove bundle build from appveyor (move to hyperspy-bundle repo)

### PR DESCRIPTION
**Pull request by ericpre**
### Progress of the PR
- [x] move to the bundle build part of `appveyor.yml` to https://github.com/hyperspy/hyperspy-bundle, as dicussed below.
- [x] tidy up `appveyor.yml`
- [x] ready for review.

### CODE REVIEW

**Comment by francisco-dlp** [comment]
Is this ready for review?

**Comment by ericpre** [comment]
Yes.

**Comment by francisco-dlp** [comment]
It looks good, except for targetting HyperSpyUI master instead of the current stable. Wouldn't it be better to release HyperSpyUI instead?

**Comment by ericpre** [comment]
Agree, shall we wait for HyperSpyUI to be released (and available in pypi) then?

**Comment by francisco-dlp** [comment]
If HyperSpyUI will be released in 1-2 days, we can wait. Otherwise, we must either:

1. release HyperSpy without the bundle
2. release HyperSpy with HyperSpyUI master.

This is because the plotting is currently broken for users using the latest mpl.

I am not too in favour of 2 because the reason why @vidartf doesn't release HyperSpyUI yet is that it suffers from a critical bug affecting window users.

**Comment by francisco-dlp** [comment]
If we go for 2. (and even if we don't), what about moving the WP building code to https://github.com/hyperspy/hyperspy-bundle where it belongs? As discussed elsewhere, decoupling the bundle releases from HyperSpy's is advantageous. Actually, the bundle releases should happen automatically triggered by winpython releases and hyperspy releases. Only when things go wrong or we want to improve the bundle could we should release the bundle "manually". Thoughts?

**Comment by ericpre** [comment]
Yes, I am for moving the bundle build to hyperspy-bundle, so I am going to remove all the bundle build code from hyperspy in this PR.
For the bundle release, we should definitely wait for the fixes in HyperSpyUI.

**Comment by francisco-dlp** [comment]
In the interest of keeping the history tidy I think that it'll be better to revert the last commit, merge this and send another PR to remove the code from this repo.

**Comment by ericpre** [comment]
Yes, most of the commits are now obsolete, would it better to close this PR and just make a new one to remove the relevant part?

**Comment by francisco-dlp** [comment]
Sounds good!

**Comment by ericpre** [comment]
I squashed the commits.

**Comment by francisco-dlp** [comment]
Looks good, but does more than described. It'll be good to add a little description of the changes unrelated to moving WP to the bundle repo before merging.

**Comment by ericpre** [comment]
Do you mean the `on_failure` part? I copied and paste the content of the appveyor from a upstream branch, I possibly took next minor by mistake. Shoujld I removed it and squash it to keep things simple?

**Comment by francisco-dlp** [comment]
Yes, that's what I mean. Sounds good.

**Pull request merged**
