### PR TITLE
fixed showing spikes help

### LINKED ISSUE #663: Spikes removal help
The spikes removal new help button does nothing. Probably it got broken in #656.

### PR DESCRIPTION
**Pull request by to266**
fixes #663

### CODE REVIEW

**Comment by francisco-dlp** [comment]
I wonder how many other difficult to detect bugs ``@staticmethod`` has introduced...

**Comment by to266** [comment]
I think none, I just checked

**Comment by jat255** [comment]
That's what I get for blindly listening to pycharm about static decorators...

**Comment by to266** [comment]
Actually it was me who blindly listened to pycharm. Your implementation worked, but I broke it with https://github.com/hyperspy/hyperspy/pull/650

**Pull request merged**
