### PR TITLE
Added dependency for scikit-image.

### PR DESCRIPTION
**Pull request by CodeMonkeyJan**
As mentioned in #1058 and #708

### CODE REVIEW

**Comment by francisco-dlp** [comment]
Great, you have only missed adding it to `anaconda_hyperspy_environment.yml`.

We usually try to minimize the number of non-pure-python packages that HyperSpy's depend on. Notice e.g. that HyperSpy doesn't require scikit-learn, but installing it enables some features. I think that we should do the same about skimage.

So, in practice, all that I'm proposing is to remove `scikit-image` from `install_requirements` in `setup.py`.

Once the issues above are addressed, I think that this is ready to merge. One minor comment: normally we add dependencies with the feature that requires them, why submitting this as a separate PR?

**Comment by dnjohnstone** [comment]
@francisco-dlp the separate PR is my fault/suggestion - it's just in this particular case we have more than one PR, that I expect will be merged before too long, that adds this dependency and I thought this would be a cleaner solution to get this in to the master and thus tidy up the other PRs/reduce risk of them containing their own bugs on this bit.

**Comment by CodeMonkeyJan** [comment]
Are you sure it is missing in `anaconda_hyperspy_environment.yml`? I did not add it, but it is present as far as I can see:
>name: hyperspy
>dependencies:
>- python=3.5
>- dill
>- h5py
>- ipython
>- jupyter
>- matplotlib
>- nose
>- numpy
>- qt
>- __scikit-image__
>- scikit-learn
>- scipy
>- setuptools
>- statsmodels
>- sympy
>- natsort
>- ncurses
>- pip:
>  - dask
>  - hyperspy
>  - traits
>  - traitsui
>  - ipywidgets

`scikit-image` is now gone from the `install_requirements` in `setup.py`. As it is only lazy-imported when neccessary in `WaveImage`, everyone who does not use it should be fine without `skimage`.

**Comment by francisco-dlp** [comment]
You are right, sorry for that.

**Pull request merged**
