### PR TITLE
Fix error when reading dm4 files larger than 4Gb

### LINKED ISSUE #2031: Troubles reading DM4 4-D stack
Got the following error trying to load large DM4 4-D stack file:

```python
ss = hs.load('D:\\Vadim\\2018-08-02_STEM-d_C_fiber_Fengshan\\bin2\\02_0V.dm4')

---------------------------------------------------------------------------
DM3TagIDError                             Traceback (most recent call last)
<ipython-input-20-bfa902970b32> in <module>()
----> 1 ss = hs.load('D:\\Vadim\\2018-08-02_STEM-d_C_fiber_Fengshan\\bin2\\02_0V.dm4')

C:\Users\migunov\AppData\Local\conda\conda\envs\hs\lib\site-packages\hyperspy\io.py in load(filenames, signal_type, stack, stack_axis, new_axis_name, lazy, **kwds)
    241             objects = [load_single_file(filename, lazy=lazy,
    242                                         **kwds)
--> 243                        for filename in filenames]
    244 
    245         if len(objects) == 1:

C:\Users\migunov\AppData\Local\conda\conda\envs\hs\lib\site-packages\hyperspy\io.py in <listcomp>(.0)
    241             objects = [load_single_file(filename, lazy=lazy,
    242                                         **kwds)
--> 243                        for filename in filenames]
    244 
    245         if len(objects) == 1:

C:\Users\migunov\AppData\Local\conda\conda\envs\hs\lib\site-packages\hyperspy\io.py in load_single_file(filename, signal_type, **kwds)
    284                                 reader=reader,
    285                                 signal_type=signal_type,
--> 286                                 **kwds)
    287 
    288 

C:\Users\migunov\AppData\Local\conda\conda\envs\hs\lib\site-packages\hyperspy\io.py in load_with_reader(filename, reader, signal_type, **kwds)
    293     lazy = kwds.get('lazy', False)
    294     file_data_list = reader.file_reader(filename,
--> 295                                         **kwds)
    296     objects = []
    297 

C:\Users\migunov\AppData\Local\conda\conda\envs\hs\lib\site-packages\hyperspy\io_plugins\digital_micrograph.py in file_reader(filename, record_by, order, lazy)
    986     with open(filename, "rb") as f:
    987         dm = DigitalMicrographReader(f)
--> 988         dm.parse_file()
    989         images = [ImageObject(imdict, f, order=order, record_by=record_by)
    990                   for imdict in dm.get_image_dictionaries()]

C:\Users\migunov\AppData\Local\conda\conda\envs\hs\lib\site-packages\hyperspy\io_plugins\digital_micrograph.py in parse_file(self)
     85             number_of_root_tags,
     86             group_name="root",
---> 87             group_dict=self.tags_dict)
     88 
     89     def parse_header(self):

C:\Users\migunov\AppData\Local\conda\conda\envs\hs\lib\site-packages\hyperspy\io_plugins\digital_micrograph.py in parse_tags(self, ntags, group_name, group_dict)
    219                     ntags=ntags,
    220                     group_name=tag_name,
--> 221                     group_dict=group_dict[tag_name])
    222             else:
    223                 _logger.debug('File address:', self.f.tell())

C:\Users\migunov\AppData\Local\conda\conda\envs\hs\lib\site-packages\hyperspy\io_plugins\digital_micrograph.py in parse_tags(self, ntags, group_name, group_dict)
    219                     ntags=ntags,
    220                     group_name=tag_name,
--> 221                     group_dict=group_dict[tag_name])
    222             else:
    223                 _logger.debug('File address:', self.f.tell())

C:\Users\migunov\AppData\Local\conda\conda\envs\hs\lib\site-packages\hyperspy\io_plugins\digital_micrograph.py in parse_tags(self, ntags, group_name, group_dict)
    219                     ntags=ntags,
    220                     group_name=tag_name,
--> 221                     group_dict=group_dict[tag_name])
    222             else:
    223                 _logger.debug('File address:', self.f.tell())

C:\Users\migunov\AppData\Local\conda\conda\envs\hs\lib\site-packages\hyperspy\io_plugins\digital_micrograph.py in parse_tags(self, ntags, group_name, group_dict)
    222             else:
    223                 _logger.debug('File address:', self.f.tell())
--> 224                 raise DM3TagIDError(tag_header['tag_id'])
    225 
    226     def get_data_reader(self, enc_dtype):

DM3TagIDError: 66
```
Lacking of knowledge I'm still trying to troubleshoot the issue without almost any success... As the file size is > 50GB, I have exported tags as .gtg file which is attached. 

[02_0V settings.gtg.zip](https://github.com/hyperspy/hyperspy/files/2282667/02_0V.settings.gtg.zip)

### PR DESCRIPTION
**Pull request by francisco-dlp**
Fixes #2031

### CODE REVIEW

**Comment by woozey** [comment]
Indeed, it has fixed the "Invalid argument" error in #2031. I'm now checking even larger file size that caused the original crash.

**Comment by francisco-dlp** [comment]
Thanks @woozey, did it fix the issue with the 50Gb file too?

**Comment by francisco-dlp** [comment]
@ericpre, since this is at least partially (and hopefully fully) fixing #2031 and it doesn't break any of the dm3/dm4 tests, would you agree to merge it without waiting for full confirmation from @woozey so that it makes it into v1.4?

**Comment by woozey** [comment]
@francisco-dlp sorry for delay, I confirm that it works for 50 GB files, I had another error popping up with a 250 GB file I should test it within an hour or so.

**Comment by francisco-dlp** [comment]
Great, thanks @woozey.

**Comment by woozey** [comment]
I got it quicker than I thought. It fixes the error with 250 GB file too. Thanks! Great job fixing it!

**Comment by francisco-dlp** [comment]
kudos to @mfm24 who warned me of this issue years ago!

**Pull request merged**
