### PR TITLE
Fix reading metadata tif issue with scikit image 0.13

### PR DESCRIPTION
**Pull request by ericpre**
Tifffile.py have been updated in the last release of scikit-image and this PR fixes parsing scale and units of tiff files.

- [x] Fix parsing scale and units with last version of scikit-image.
- [x] Parse more metadata for SEM.
- [x] Add a stage node (tilt_a, tilt_b, rotation, x, y, z) to metadata specification (See discussion in #1396).
- [x] Get a TVIPS camera test file and parse the metadata.

In this PR, the metadata (including scale and units) would not be parsed with older version of scikit-image (<0.13) or tifffile.py. The file will be still loaded correctly, though. The main reason is to make more simple. I would suggest to also complete #1433 after merging this one.

### CODE REVIEW

**Comment by ericpre** [comment]
It would be great if this PR could be reviewed and merged asap, to get CI green again... and then do #1565 and #1433!

**Comment by francisco-dlp** [comment]
Why not simply requiring skimage >= 0.13?

**Comment by ericpre** [comment]
Agree.

**Comment by francisco-dlp** [comment]
Just a couple of things:
* When changing the metadata structure (in this case replacing ``tilt_stage`` by the stage node) we must change the version in ``io_plugins/hdf5.py``. In this case, we need to increase the major index so it'll be v3.0. Now that you are at it, you could add the version to the metadata structure chapter, as this is actually the version of our hdf5 specification.
* HyperSpy must be able to read all the information from previous hdf5 specifications, so  ``io_plugins/hdf5.py`` requires modification to look for ``tilt_stage`` and place the information in the new node. A test to check that it does it properly is also required.

**Comment by ericpre** [comment]
I think some of it is in #1565. The two PR go together, sorry for the confusion, I made a separate one that update the metadata in all io plugins. I didn't wanted to make this one too complicated and focused here on tiff only.
Should we move the discussion regarding hdf5 in #1565?

**Comment by francisco-dlp** [comment]
The same applies to the camera node in #1565. Why not e.g. merging #1565 here and closing it?

**Comment by francisco-dlp** [comment]
Sorry to come up with a question after merging: why not renaming ``tilt_a`` and ``tilt_b`` to the more familiar ``tilt_alpha`` and ``tilt_beta``?

**Comment by ericpre** [comment]
No particular reason, can change it to `tilt_alpha` and `tilt_beta`.

**Pull request merged**
