### PR TITLE
Fix fit_component multifit and add test

### LINKED ISSUE #1661: fit_component only_current=True not working
fit_component does not multifit when I set `only_current = False`. Has the method changed in any way? Would be nice to write a test to catch this in the future.

### PR DESCRIPTION
**Pull request by thomasaarholt**
Fixes #1661. @francisco-dlp could you take a look and comment on why the code was the way it was set-up? Seems odd.

### CODE REVIEW

**Comment by thomasaarholt** [comment]
I do not understand why the deconvolution tests are failing in Rnp? I certainly haven't changed them. They are failing in my local Rnm as well.

**Comment by ericpre** [comment]
This seems to be related to the version of pytest because they are passing with pytest=3.1.0 and are failing with 3.1.1.

**Comment by thomasaarholt** [comment]
`3.0.7` here, and it fails. Windows.

**Comment by thomasaarholt** [comment]
The code runs fine manually, albeit with some warnings:

```python
class TestFourierRatioDeconvolution:

    def test_running(self):
        s = hs.signals.EELSSpectrum(np.arange(200))
        s_ll = hs.signals.EELSSpectrum(np.zeros(100))
        s_ll.data[18:23] = [3, 10, 20, 10, 3]
        s_ll.axes_manager[0].offset = -20
        s.fourier_ratio_deconvolution(s_ll)
        
a = TestFourierRatioDeconvolution()
a.test_running()

/Users/thomas/hyperspy/hyperspy/_components/power_law.py:131: RuntimeWarning: divide by zero encountered in true_divide
  r = 2 * log(I1 / I2) / log(x2 / x1)
/Users/thomas/hyperspy/hyperspy/_components/power_law.py:131: RuntimeWarning: invalid value encountered in log
  r = 2 * log(I1 / I2) / log(x2 / x1)
```

Running it like this works fine in the test:
```python
def test_thomas(self):
        s = hs.datasets.example_signals.EDS_SEM_Spectrum()
        s.set_signal_type("EELS")
        s.fourier_ratio_deconvolution(s)
```

**Comment by ericpre** [comment]
This is surprising that it also fails with pytest 3.0.7, because I can reproduce nicely and this looks consistent with CI over different commits. Appveyor with pytest 3.0.7 is passing in this PR, while travis with pytest 3.1.1 is failing. In another PR (#1665), both travis and appveyor are failing with pytest 3.1.1.

**Comment by ericpre** [comment]
Yes, that is it. This is because of the `RuntimeWarning` as for the other failing tests, however in this case the error traceback is wrong and this is why it was confusing.

**Comment by thomasaarholt** [comment]
I didn't really understand your last comment - anything we should do?

**Comment by ericpre** [comment]
The warnings make the tests failing and this is why `test_running` is failing and `test_thomas` is not. This needs to be sorted out in another PR. Maybe also report the wrong error traceback to pytest.

**Comment by thomasaarholt** [comment]
Understood. thanks!

**Pull request merged**
