### PR TITLE
Release next major

### PR DESCRIPTION
**Pull request by CSSFrancis**
Merging into release next minor.

### CODE REVIEW

**Comment by ericpre** [comment]
I am wondering if we should push directly the `RELEASE_next_major` branch to `RELEASE_next_patch` and `RELEASE_next_minor`, since the two latter should be (I think it is, but may be worth checking properly!) included in the first one?

**Comment by CSSFrancis** [comment]
> I am wondering if we should push directly the `RELEASE_next_major` branch to `RELEASE_next_patch` and `RELEASE_next_minor`, since the two latter should be (I think it is, but may be worth checking properly!) included in the first one?

Can we push directly to RELEASE_next_minor or is that branch protected?  The `RELEASE_next_patch` appears to have some additional commits that might make things a little more difficult.

**Comment by ericpre** [comment]
Then maybe, `RELEASE_next_patch` should be merged in `RELEASE_next_major` and then push to the two other branch? That way, there should be less files to change?

**Comment by jlaehne** [comment]
Looking at a merge of `RELEASE_next_patch` into `RELEASE_next_major` there seems to be nothing to do.

Just went through the 19 commits that `RELEASE_next_patch` is ahead of `RELEASE_next_minor`, which should be the only ones that could be relevant, and indeed almost all of them are already included in `RELEASE_next_major` (some typos, bumping of actions, backported numpy deprection, release notes) or are outdated now (e.g. pinning of pillow, skipping of tests).

The only point I am not sure of whether commits could get lost are:
- https://github.com/hyperspy/hyperspy/commit/c4cbd16b3f53f43663c85d94f7163dcb9edcc58c and https://github.com/hyperspy/hyperspy/commit/ab4f29a3407d23773103aa1c26504260026d2deb from @CSSFrancis: Testing of future file version import, which would have to go to `rsciio`. In this context, only the four lines from `axes.py` would be relevant for `hyperspy`.

Apart from that, we could thus directly push `RELEASE_next_major` to `RELEASE_next_patch` and `RELEASE_next_minor` as suggested by @ericpre

**Comment by ericpre** [comment]
> Looking at a merge of `RELEASE_next_patch` into `RELEASE_next_major` there seems to be nothing to do.
> 
> Just went through the 19 commits that `RELEASE_next_patch` is ahead of `RELEASE_next_minor`, which should be the only ones that could be relevant, and indeed almost all of them are already included in `RELEASE_next_major` (some typos, bumping of actions, backported numpy deprection, release notes) or are outdated now (e.g. pinning of pillow, skipping of tests).
> 
> The only point I am not sure of whether commits could get lost are:
> 
> * [c4cbd16](https://github.com/hyperspy/hyperspy/commit/c4cbd16b3f53f43663c85d94f7163dcb9edcc58c) and [ab4f29a](https://github.com/hyperspy/hyperspy/commit/ab4f29a3407d23773103aa1c26504260026d2deb) from @CSSFrancis: Testing of future file version import, which would have to go to `rsciio`. In this context, only the four lines from `axes.py` would be relevant for `hyperspy`.

These changes are for hyperspy <2.0 only because it helps for reading (with hyperspy 1.7.6) some files (not all, thinking of files containing markers for example) saved with hyperspy 2.0 and theses commits are not relevant to hyperspy >=2.0 (and rosettasciio).

> Apart from that, we could thus directly push `RELEASE_next_major` to `RELEASE_next_patch` and `RELEASE_next_minor` as suggested by @ericpre

Thinking about it, maybe there is value in merging `RELEASE_next_patch` into `RELEASE_next_major` so that the 1.7.6 tag can assigned to commit in the git history?

**Comment by CSSFrancis** [comment]
Hmm so how do we feel about merging RELEASE_next_patch into RELEASE_next_minor and then rebasing RELEASE_next_major into RELEASE_next_minor before merging RELEASE_next_major into both. 

I think that gives a pretty clean git history. We might have to roll back some changes in RELASE_next_major but that shouldn't be a huge issue.

**Comment by ericpre** [comment]
All the commit from `RELEASE_next_minor` are already in `RELEASE_next_major` right? Why would a rebase followed by a merge be necessary? `RELEASE_next_major` already contains all relevant history, except the commits of the 1.7.6 tag.

**Comment by CSSFrancis** [comment]
The patch is both behind and ahead of the minor release which causes the problem, right? 

We want a history that goes minor->patch->(roll back some of the patch changes)-> major.

Correct?

I think I misspoke above, we should rebase the patch on the minor release, roll back the patch changes that aren't needed and the rebase the major release on the patch.

Then push to all branches.

How does this sound?

**Comment by jlaehne** [comment]
Sounds like the cleanest in terms of history, but I just hope that it is not making things more complicated than they should be.

**Comment by ericpre** [comment]
I think we side-tracked ourselves here! The pattern that we follow in hyperspy is as follow:
- `RELEASE_next_patch` is merged into  `RELEASE_next_minor`
- `RELEASE_next_minor` is merged into  `RELEASE_next_major`
- After any release, the branch of the current release is merged into `RELEASE_next_patch` because we usually don't do patch release below the current release minor, (once 1.7.0 was released, the next patch release was 1.7.1 and we never did another 1.6.x release).

I think the same should work here and this is what in #3288:  a merge fast forward of `RELEASE_next_major` into `RELEASE_next_patch` and it works fine: no conflict and the history looks good to me.

**Comment by jlaehne** [comment]
> I think the same should work here and this is what in #3288: a merge fast forward of `RELEASE_next_major` into `RELEASE_next_patch` and it works fine: no conflict and the history looks good to me.

Sounds sensible - is the patch then automatically merged into minor?

**Comment by ericpre** [comment]
No, this will need to be done manually once in a while - obviously, this wasn't necessary in the last year or two. There is a workflow which does this regularly but it broke at some point. I am not sure if I find that useful, because it fails silently when there is a merge conflict, so you may expect that it the minor branch is up to date, but it is not...

**Comment by CSSFrancis** [comment]
> I think we side-tracked ourselves here! The pattern that we follow in hyperspy is as follow:
> 
> - `RELEASE_next_patch` is merged into  `RELEASE_next_minor`
> 
> - `RELEASE_next_minor` is merged into  `RELEASE_next_major`
> 
> - After any release, the branch of the current release is merged into `RELEASE_next_patch` because we usually don't do patch release below the current release minor, (once 1.7.0 was released, the next patch release was 1.7.1 and we never did another 1.6.x release).
> 
> 
> 
> I think the same should work here and this is what in #3288:  a merge fast forward of `RELEASE_next_major` into `RELEASE_next_patch` and it works fine: no conflict and the history looks good to me.
> 
> 
> 
> 

Yes let's do that. Sorry I kind of jumped the gun here thinking it would be easy :) 

Let me add that to the developer guide just as a reference.

**Comment by jlaehne** [comment]
> No, this will need to be done manually once in a while - obviously, this wasn't necessary in the last year or two. There is a workflow which does this regularly but it broke at some point. I am not sure if I find that useful, because it fails silently when there is a merge conflict, so you may expect that it the minor branch is up to date, but it is not...

Fair case to stay with a manual update then. We should have possibly even done that even before we released 2.0, because it seems to me that the author list on zenodo is taken from the RELEASE_next_minor branch? We should then in the future also push patch branches to minor before releasing them.

**Comment by jlaehne** [comment]
By the way, the documentation page on the website did not update yet: https://hyperspy.org/documentation.html
And we should include a news item that 2.0 was released!

**Comment by ericpre** [comment]
Yes and no: the link to [HyperSpy User Guide](https://hyperspy.org/hyperspy-doc/current/index.html) is up to date, but the website itself is not, because it doesn't support current sphinx and I tried to build it, I didn't have to setup a different sphinx environment, build the website and push!
This is something that would benefit from modernizing!

**Comment by CSSFrancis** [comment]
@ericpre I opened an issue #3290 and can work on that today if you would like!

**Comment by ericpre** [comment]
I updated the [hyperspy website](https://hyperspy.org/documentation.html) until there is something better.

**Pull request closed without merging**
