### PR TITLE
Bugfix for find_peaks1D_ohaver() when a datapoint is zero

### PR DESCRIPTION
**Pull request by magnunor**
Bugfix for https://github.com/hyperspy/hyperspy/issues/628

Send it to 0.8.x?

- [x] Unit test

### CODE REVIEW

**Comment by magnunor** [comment]
I added a test, but if the bug occurs the nosetest will basically "hang". I tried this: http://stackoverflow.com/questions/6548496/making-nose-fail-slow-tests but that didn't work either

**Comment by francisco-dlp** [comment]
Moved this to 0.8.2.

**Comment by francisco-dlp** [comment]
@magnunor, could you base this on 0.8.x and resubmit the PR there in time for the 0.8.3 release?

Beside, wouldn't masking the zero values for the fitting step be a more robust fix to the issue, for example by editing line 139 as follows:

```python
yynz = yy != 0
coef = np.polyfit(
                          xxf[yynz], np.log10(np.abs(yy[yynz])), 2)

```

**Comment by magnunor** [comment]
I'll fix this later today.

**Comment by magnunor** [comment]
I rebased this to the current master, and changed the mechanism to your suggestion @francisco-dlp, which seems to be working.

For the future we should think about replacing this function, as discussed here: https://github.com/hyperspy/hyperspy/issues/711

**Comment by vidartf** [comment]
@magnunor: Could you rebase to the 0.8.x branch and resubmit there?

**Comment by vidartf** [comment]
Also, the travis build fails since the test code uses `from hyperspy.hspy import load` instead of `hyperspy.api`.

**Comment by magnunor** [comment]
https://github.com/hyperspy/hyperspy/pull/870

**Pull request closed without merging**
