### PR TITLE
Enh parallel multifit

### PR DESCRIPTION
**Pull request by to266**
Enabling parallel multifit of a model. 

Actually includes lots of other branches merged:
 - https://github.com/hyperspy/hyperspy/pull/167 Model as dict
 - https://github.com/hyperspy/hyperspy/pull/202 Signal dict variance
 - https://github.com/hyperspy/hyperspy/pull/234 Enh fancy model indexing
 - https://github.com/hyperspy/hyperspy/pull/235 Bug: fold variance too, when folding signal
 - https://github.com/hyperspy/hyperspy/pull/236 ENH: fold model 

Mostly here now for testing purposes.

So please test and let me know if it works.

A known bug: not correctly initialising components that require some input (such as scalable fixed pattern, etc.) A preliminary (hopefully!) fix is in ENH_component_init  branch in my hyperspy repository

### CODE REVIEW

**Comment by jat255** [comment]
Hi there,

I was trying to use the branch to speed up some model fitting I'm doing, but unfortunately seem to have come across a bug dealing with the navigation indexing of models (`m.inav...`).

If I create a model from an EELS signal with no elements added, it works as expected:

```python
s = load("hyperspy_files/line3-mn/line3-high.hdf5")
m = create_model(s)
m.inav[0:35]
>>> <Model [<background (PowerLaw component)>]>
````

However, if I add core loss edges to this model, I get an error:

```python
s = load("hyperspy_files/line3-mn/line3-high.hdf5")
m = create_model(s)
m.inav[0:35]
>>> Elemental composition read from file
>>> Adding Mn_L2 subshell
>>> Adding Mn_L3 subshell
>>> 
>>> Hartree-Slater GOS
>>>        Element:  Mn
>>> 	       Subshell:  L3
>>> 	       Onset Energy =  640.0
>>> 
>>> Hartree-Slater GOS
>>> 	        Element:  Mn
>>>  	Subshell:  L2
>>>  	Onset Energy =  651.0
>>> ---------------------------------------------------------------------------
>>> ValueError                                Traceback (most recent call last)
>>> <ipython-input-13-cec185aad0e2> in <module>()
>>> ----> 1 m.inav[0:35]
>>> 
>>> d:\umd_research\software\hyperspy\hyperspy\model.py in __getitem__(self, slices)
>>>    2406 
>>>    2407     def __getitem__(self, slices):
>>> -> 2408         return self.model.__getitem__(slices, True, self.isNavigation)
>>> 
>>> d:\umd_research\software\hyperspy\hyperspy\model.py in __getitem__(self, value, not_components, isNavigation)
>>>    2366                                         1])])
>>>    2367                         # p_new.value = p_new.map['values'].ravel()[0]
>>> -> 2368                         p_new.value = p_orig.value
>>>    2369                         twin_dict[id(p_orig)] = ([id(i)
>>>    2370                                                   for i in list(p_orig._twins)], p_new)
>>> 
>>> d:\umd_research\software\hyperspy\hyperspy\component.py in _setvalue(self, arg)
>>>     211                 raise ValueError(
>>>     212                     "The lenght of the parameter must be ",
>>> --> 213                     self._number_of_elements)
>>>     214             else:
>>>     215                 if not isinstance(arg, tuple):
>>> 
>>> ValueError: ('The lenght of the parameter must be ', 1)
>>>
```

**Comment by francisco-dlp** [comment]
Hi Josh,

You've found a bug, thank you for reporting it. This branch will be merged into master for HyperSpy 0.9, so we'll fix it but probably not immediately.

Parallel multifit (aka SAMfire) is more than just a parallelisation of multifit, it's a much more resilient way to fit multidimensional spectra. However, it is not always faster than multifit so, if speed is your main concern, this branch may or may not help for your problem.

Curve fitting in HyperSpy is slow because we have never cared too much about speed (most datasets that we have worked with were small enough so that slowness was not a problem). However, several of us are starting to work on much bigger datasets and we're starting to crave for speed. There is an straightforward way to speed up fitting in HyperSpy: using [numexpr](https://github.com/pydata/numexpr). I have just opened an issue (#488) about it.

**Comment by to266** [comment]
Hi Josh,

If you have the time, could you see if the issue is resolved? It's been a while since I touched this branch, but it should work now.

I should probably also warn you that at the moment it contains model <-> dictionary functions, which might change quite a bit in the future and might not be functioning properly at the moment (seems to work for me though..), so many (like this particular one) bugs may be related to it. 
On the bright side, the fancy indexing works! :smile: 

Francisco also made a small mistake - this branch is not the "SAMFire" one, so nothing more fancy than the normal `multifit`

**Comment by dnjohnstone** [comment]
@to266 given our conversation earlier - how far away from something that I can try out is this branch? Certainly have some appropriate data that I could use to test this if that's all that needs doing.

**Comment by to266** [comment]
This will likely need a complete (or at least a significant) rewrite. I will get to it eventually, but not now

**Pull request closed without merging**
