### PR TITLE
Print a table about identified EELS edges

### PR DESCRIPTION
**Pull request by ptim0626**
### Description of the change
This is a follow-up of the [suggestion](https://github.com/hyperspy/hyperspy/pull/2390#issuecomment-627806669) in #2390. It includes:
- a static method in EELSSpectrum to print out a table about identified edges within an energy window 
- elements_db is updated with information from Gatan's [EELS atlas](https://eels.info/atlas)

### Progress of the PR
- [x] Change implemented
- [x] update user guide
- [x] add tests,
- [x] ready for review.

### Minimal example of the bug fix or the new feature
```python
>>> import hyperspy.api as hs
>>> s = hs.datasets.artificial_data.get_core_loss_eels_signal()
>>> s.print_edges_near_energy(401, width=20)
+-------+-------------------+-----------+-----------------------------+
|  edge | onset energy (eV) | relevance |         description         |
+-------+-------------------+-----------+-----------------------------+
|  N_K  |       401.0       |   Major   |         Abrupt onset        |
| Sc_L3 |       402.0       |   Major   | Sharp peak. Delayed maximum |
| Cd_M5 |       404.0       |   Major   |       Delayed maximum       |
| Sc_L2 |       407.0       |   Major   | Sharp peak. Delayed maximum |
| Mo_M2 |       410.0       |   Minor   |          Sharp peak         |
| Mo_M3 |       392.0       |   Minor   |          Sharp peak         |
| Cd_M4 |       411.0       |   Major   |       Delayed maximum       |
+-------+-------------------+-----------+-----------------------------+
```

### CODE REVIEW

**Comment by francisco-dlp** [comment]
It looks very good. Just a few suggestions:

* You could add an html table (for e.g. the jupyter notebook) by using out `print_html` function. See https://github.com/hyperspy/hyperspy/blob/dbb9821d5a9d41dd6a78af646a73c499cc0ceaa6/hyperspy/utils/__init__.py#L90 for an example.
* You could add a ``@staticmethod`` decorator.
* What about changing the name to ``print_edges_near_energy`` and not returning the list of edges?

**Comment by ptim0626** [comment]
> It looks very good. Just a few suggestions:
> 
> * You could add an html table (for e.g. the jupyter notebook) by using out `print_html` function. See https://github.com/hyperspy/hyperspy/blob/dbb9821d5a9d41dd6a78af646a73c499cc0ceaa6/hyperspy/utils/__init__.py#L90
>    for an example.
> * You could add a `@staticmethod` decorator.
> * What about changing the name to `print_edges_near_energy` and not returning the list of edges?

**Comment by ptim0626** [comment]
@francisco-dlp all suggestions taken and will reflect the change in the PR (sorry I accidentally closed the PR...pressed wrongly)

**Comment by francisco-dlp** [comment]
It looks good to me. @ericpre, do you have any suggestions?

**Comment by ericpre** [comment]
Looks good to me, too, thanks @ptim0626!

**Comment by ericpre** [comment]
Suggestion for further improvement #2409.

**Pull request merged**
