### PR TITLE
Correct .gitignore that was ignoring the API docs and /bin files

### PR DESCRIPTION
**Pull request by francisco-dlp**
As it was, the API rst files were ignored by git. Hence, our docs in readthedocs were partly broken. Also stop ignoring `hyperspy/bin`, except for the `.bat` files.

### CODE REVIEW

**Comment by vidartf** [comment]
I kinda figured that the api/*.rst files where compiled files?

**Comment by francisco-dlp** [comment]
Yes, they're automatically generated using `sphinx-apidoc`. However, readthedocs doesn't by default execute apidoc, so currently our docs there are missing the API. There might be a way to instruct it to run apidoc, but I couldn't find how...

**Comment by francisco-dlp** [comment]
@vidartf, is this ok then?

**Comment by vidartf** [comment]
I don't really know. I'm not really experienced with sphinx enough to know how it should work :-/

**Comment by francisco-dlp** [comment]
In that case, at least anybody has something against it, I'll merge it to fix the issue with ReadTheDocs. If we find a better solution (i.e. a way to execute sphinx-apidoc in RtD) then it'll be easy to undo it.

**Pull request merged**
