### PR TITLE
Update some obsolete lines

### PR DESCRIPTION
**Pull request by mwalls**
Check this before accepting. I can easily be mistaken.

### CODE REVIEW

**Comment by thomasaarholt** [comment]
Yep, that looks correct!

**Comment by vidartf** [comment]
I updated the branch target of this PR to patch branch, so now it only needs a git rebase before it can be merged! 👍

**Comment by vidartf** [comment]
The rebase commands in question would be:
```
git rebase --onto hyperspy/RELEASE_next_patch hyperspy/RELEASE_next_minor patch-1
git push -f
```

**Comment by francisco-dlp** [comment]
Merged manually 4081551822517d4789d7dec854334f7a9c57a13f

**Pull request closed without merging**
