### PR TITLE
Fixed Travis badge for RELEASE_next_patch

### PR DESCRIPTION
**Pull request by tjof2**
...which meant the Travis badge looked like the build was failing:

untitled

### CODE REVIEW

**Comment by francisco-dlp** [comment]
Shouldn't it point to RELEASE_next_patch now since you're sending the PR to RELEASE_next_patch?

**Comment by tjof2** [comment]
Ah good point. But then do I need to do another one for `RELEASE_next_minor`? I only sent the PR here based on #1170 because it is technically a bug :-)

**Comment by francisco-dlp** [comment]
This reminds me that we should disable the downloads badge until they fix the downloads statistics in pypi.

**Comment by francisco-dlp** [comment]
No, I'll do that when merging into the other branches, thanks!

**Pull request merged**
