### PR TITLE
Enh no progressbar in tests

### PR DESCRIPTION
**Pull request by to266**
removed progressbar from all tests, as a consequence had to add the functionality to some methods.
Nothing major, just something that annoyed me

### CODE REVIEW

**Comment by francisco-dlp** [comment]
Looks good. However, a drawback is that if they progress gets broken we won't know...

**Comment by to266** [comment]
A fair point, I added very rudimentary tests for progressbar. Should be visible once per run.

**Comment by francisco-dlp** [comment]
Still the progress bar can be broken in in the locations where it is used in the code (this has happened in the past). What about not setting the progress bar to False in the tests but to None? In this way, if you want to run the tests without progress bars you can just change your progress bar default in prefereces...

**Comment by to266** [comment]
Would that crash the running function, or just not print the pbar? If just print, then it would require us to actually count how many were printed, and that just sounds ridiculous...

**Comment by francisco-dlp** [comment]
It is possible that the pbar code breaks things, this is what has happened in the past and that's why I think that it is not wise to disable it for the tests in such a general way.

**Comment by to266** [comment]
Ok. Changed the tests back. Then this PR actually adds the arguments for progressbar for any functions that actually print it (some where missed previously)

**Comment by francisco-dlp** [comment]
When I run ``nosetests`` with ``show_progressbar`` disabled in preferences I get the following error:

```
ERROR: Failure: ImportError (cannot import name progressbar)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/utils/test_progressbar.py", line 21, in <module>
    from hyperspy.misc import progressbar
ImportError: cannot import name progressbar

----------------------------------------------------------------------
Ran 722 tests in 13.339s

FAILED (errors=1)
..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................E........
======================================================================
ERROR: Failure: ImportError (cannot import name progressbar)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/fjd29/Anaconda/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/fjd29/Python/hyperspy/hyperspy/tests/utils/test_progressbar.py", line 21, in <module>
    from hyperspy.misc import progressbar
ImportError: cannot import name progressbar

----------------------------------------------------------------------
```

**Comment by to266** [comment]
Works for me though

**Comment by francisco-dlp** [comment]
The problem is that ``progressbar`` is no longer in ``hyperspy.misc`` but in ``hyperspy.externals``. If you clean your local git repository you'll hit the issue too.

I have the following in ``.git/hooks/post-checkout`` to automatically delete old *.pyc files:

```sh

#! /bin/sh

# Start from the repository root.
cd ./$(git rev-parse --show-cdup)

# Delete .pyc files and empty directories.
find . -name "*.pyc" -delete
find . -type d -empty -delete

```

**Pull request merged**
