### PR TITLE
Resubmit of "fix replotting" 

### PR DESCRIPTION
**Pull request by to266**
Resubmit of https://github.com/hyperspy/hyperspy/pull/879, the original commits follow:

 - Fix delayed call of plot `_on_close()`

 - This event doesn't need connecting/disconnecting

 - As `Signal.update_plot()` has in-built checks, it is easier to simply
always have it connected.

 - Clean up plotting

 - Re-add direct call

 - Removed stray code line

 - Typos

### CODE REVIEW

**Comment by vidartf** [comment]
Only one of the commits made the jump. WIP?

**Comment by vidartf** [comment]
Or is it squashed?

**Comment by to266** [comment]
squashed, sorry :)

**Comment by vidartf** [comment]
No worries, just looked strange, so I was concerned that something had dropped out :)

**Comment by vidartf** [comment]
The changes does of course look OK to me since I originally wrote them, so someone else should probably review them :smile:

**Comment by to266** [comment]
FYI it looks OK to me too, and I'm not even the author! :D

**Comment by thomasaarholt** [comment]
Is there anything more needed here?

**Comment by to266** [comment]
review from a 3-rd party ( @francisco-dlp ?)

**Comment by francisco-dlp** [comment]
I only disagree with "This event doesn't need connecting/disconnecting" (b35b4aeee67401599). Although `update_plot` does check if the plot exists or not, `update_plot` needs to be refurbish and, once we do it, we might forget that we're relying on that property and introduce a bug. As long as disconnecting it on close does not cause any issue, +1 on disconnecting it.

**Comment by to266** [comment]
added back

**Pull request merged**
