### PR TITLE
Set version 1.0.0+dev

### PR DESCRIPTION
**Pull request by francisco-dlp**
Set master version to 1.0.0+dev

### CODE REVIEW

**Comment by to266** [comment]
```python
ERROR: Failure: IndentationError (unexpected indent (Release.py, line 19))
```
(travis)

**Comment by francisco-dlp** [comment]
That makes no sense. I didn't touch that line. All the tests pass in my
machine.

**Comment by vidartf** [comment]
Its the same issue we had previously, then I think @to266 fixed it by checking out a copy of the file from a branch where it worked. I checked just now by opening up the file in a hex editor and comparing it to a working version. There seems to be a difference in line endings.

**Comment by vidartf** [comment]
https://help.github.com/articles/dealing-with-line-endings/

**Comment by francisco-dlp** [comment]
@vidartf, thank you for the help. I have reverted the commit and redone the commit for a linux machine (the previous one was one in a windows machine).

However, I couldn't find any DOS line ending in `Release.py`. This is what I did (before push the new commit):

```bash

wget https://raw.githubusercontent.com/francisco-dlp/hyperspy/dev_version/hyperspy/Release.py
cat -v Release.py | grep -F ^M

```

It didn't print anything.

Let's see if travis is happier now...

**Comment by francisco-dlp** [comment]
No, it's not happy yet. I'll take the easiest path to fixing this: I'll close it and send a new one from a linux machine.

**Comment by vidartf** [comment]
Inspecting raw files more closely, everything does seem to be in order now. Not sure what else could cause this if not line endings.

You could try to debug things by tuning up the debug output from nose, but I'm at a loss.

**Pull request closed without merging**
