### PR TITLE
Implemented Arctan + EELSArctan as expressions

### PR DESCRIPTION
**Pull request by jlaehne**
### Description of the change
Implemented Arctan as Expression as proposed in https://github.com/hyperspy/hyperspy/issues/2251#issuecomment-529929541
* New component `EELSArctan` replaces `minimum_at_zero=True` option
* `Arctan` component will default to the former `minimum_at_zero=False`
* legacy feature supports old way of calling the functions (up to v2?) and raises warning if `Arctan` is called with `minimum_at_zero=True` 

### Progress of the PR
- [X] Change implemented (can be split into several points),
- [X] update docstring (if appropriate),
- [X] update user guide (if appropriate),
- [X] add tests,
- [X] ready for review.

### Minimal example of the bug fix or the new feature
```python
>>> import hyperspy.api as hs
>>> import numpy as np
>>> arctan1 = hs.model.components1D.Arctan(A=10., k=5, x0=1, minimum_at_zero=True)
>>> x = np.arange(arctan1.x0.value-5,arctan1.x0.value+5,step=0.01)
>>> s = hs.signals.Signal1D(arctan1.function(x))
>>> s.axes_manager.signal_axes[0].axis = x
>>> s.plot()
```
Note that this example can be useful to update the user guide.

### CODE REVIEW

**Comment by jlaehne** [comment]
No idea, why I can't get rid of the test_bss errors in the checks.

**Comment by ericpre** [comment]
This looks good to me, except for the bss test failures, which I don't understand neither where it comes from... `RELEASE_next_minor` is fine, merging it with this branch is not! @francisco-dlp, it seems the same thing happen in #2299, any idea what it is?

**Comment by jlaehne** [comment]
But in #2299 the tests ran through now, I tried to copy `test_bss.py` from several other branches where it was fixed -- to no avail. That strategy worked in #2262 though. So I'm kind of puzzled.

**Comment by tjof2** [comment]
Perhaps sklearn version now it's 0.23? Not sure really.

**Comment by jlaehne** [comment]
It is really weird that it fails in some PRs and not in others - all of which are not related to bss. Maybe there is some other file than the test file that has changed? But I have merged 'RELEASE_next_minor' both into this one and into #2262.

**Comment by tjof2** [comment]
Something may no longer be deterministic somewhere? @francisco-dlp

**Comment by ericpre** [comment]
> It is really weird that it fails in some PRs and not in others - all of which are not related to bss. Maybe there is some other file than the test file that has changed? But I have merged 'RELEASE_next_minor' both into this one and into #2262.

Indeed, it is behaving very weirdly... typically, the issue doesn't occurs in https://github.com/hyperspy/hyperspy/pull/2307 and it has been kept up to date with `RELEASE_next_minor`!

> Perhaps sklearn version now it's 0.23? Not sure really.

sklearn is an optional dependencies and the "minimum requirement" build on travis without sklearn is failing too...


> Something may no longer be deterministic somewhere? @francisco-dlp

It consistently passes or fails... very puzzling...

**Comment by ericpre** [comment]
I have rebased this branch (https://github.com/ericpre/hyperspy/commits/Arctan_Expression) and remove some of the last commits recently to check if the test suite pass and it still fails in the same way. All other branches pass fine...

**Comment by tjof2** [comment]
@ericpre and @jlaehne  I think I know what the issue is - I can create a separate PR to fix the BSS tests to remove their dependency on this code change. See #2430 for the fix that will stop the tests failing here.

That said, the reason the tests fail is actually because this PR affects the values in the artificial datasets such as  `get_core_loss_eels_line_scan_signal()`, i.e. https://github.com/hyperspy/hyperspy/blob/bf7a3654d459e34ef5a3b0e01933589019b4a44f/hyperspy/datasets/artificial_data.py#L180

I would therefore check that this behaviour is intentional - clearly HyperSpy doesn't have a test to compare the artificial datasets (@francisco-dlp ?)

**Comment by jlaehne** [comment]
Continued in  #2432

**Pull request closed without merging**
