### PR TITLE
Fix replotting

### PR DESCRIPTION
**Pull request by vidartf**
Attempt at fixing #878. A bit of a blind attempt since I was unable to reproduce error.

### CODE REVIEW

**Comment by dnjohnstone** [comment]
@k8macarthur would be great if you can pull this branch and see if it fixes your problem - I'm not sure if anyone else is using a mac.

**Comment by k8macarthur** [comment]
This solves the initial problem in that the common s.plot() will run without errors. However no plot is actually displayed.

**Comment by dnjohnstone** [comment]
have you run %matplotlib at the start of the notebook?

**Comment by k8macarthur** [comment]
I’ve imported matplotlib.pyplot at the beginning. I’ve not had any luck with magic so I’ve been importing everything separately. 

import hyperspy.api as hs
import numpy as np
import matplotlib.pyplot as plt

**Comment by dnjohnstone** [comment]
Ok - so just to confirm explicitly.... the following doesn't work? 

import hyperspy.api as hs
import numpy as np
%matplotlib

line magic for starting hyperspy doesn't work now, but when I used a mac two weeks ago this worked for me.

**Comment by k8macarthur** [comment]
Nope, unfortunately that gives the following runtime error:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-22-111a3af809a8> in <module>()
      3 import hyperspy.api as hs
      4 import numpy as np
----> 5 get_ipython().magic(u'matplotlib')

/Users/macark/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in magic(self, arg_s)
   2334         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2335         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2336         return self.run_line_magic(magic_name, magic_arg_s)
   2337 
   2338     #-------------------------------------------------------------------------

/Users/macark/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_line_magic(self, magic_name, line)
   2255                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2256             with self.builtin_trap:
-> 2257                 result = fn(*args,**kwargs)
   2258             return result
   2259 

<decorator-gen-106> in matplotlib(self, line)

/Users/macark/anaconda/lib/python2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, *a, **k)
    191     # but it's overkill for just that one bit of state.
    192     def magic_deco(arg):
--> 193         call = lambda f, *a, **k: f(*a, **k)
    194 
    195         if callable(arg):

/Users/macark/anaconda/lib/python2.7/site-packages/IPython/core/magics/pylab.pyc in matplotlib(self, line)
     98             print("Available matplotlib backends: %s" % backends_list)
     99         else:
--> 100             gui, backend = self.shell.enable_matplotlib(args.gui)
    101             self._show_matplotlib_backend(args.gui, backend)
    102 

/Users/macark/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in enable_matplotlib(self, gui)
   3135         # Now we must activate the gui pylab wants to use, and fix %run to take
   3136         # plot updates into account
-> 3137         self.enable_gui(gui)
   3138         self.magics_manager.registry['ExecutionMagics'].default_runner = \
   3139             pt.mpl_runner(self.safe_execfile)

/Users/macark/anaconda/lib/python2.7/site-packages/ipykernel/zmqshell.pyc in enable_gui(gui)
    380         from .eventloops import enable_gui as real_enable_gui
    381         try:
--> 382             real_enable_gui(gui)
    383         except ValueError as e:
    384             raise UsageError("%s" % e)

/Users/macark/anaconda/lib/python2.7/site-packages/ipykernel/eventloops.pyc in enable_gui(gui, kernel)
    270     loop = loop_map[gui]
    271     if loop and kernel.eventloop is not None and kernel.eventloop is not loop:
--> 272         raise RuntimeError("Cannot activate multiple GUI eventloops")
    273     kernel.eventloop = loop

RuntimeError: Cannot activate multiple GUI eventloops

**Comment by francisco-dlp** [comment]
Could you try the following?:

```python

import hyperspy.api as hs
%matplotlib qt4

```

**Comment by k8macarthur** [comment]
I get the same error with except with this written at the top.

Warning: Cannot change to a different GUI toolkit: qt4. Using osx instead.

**Comment by francisco-dlp** [comment]
What's your default mpl backend as given by plt.get_backend() before
importing anything but matplotlib?

If it is not Qt4Agg, could you try running the following before
importing hyperspy?

```python
import matplotlib
matplotlib.rcParams["backend"] = 'Qt4Agg'

```

**Comment by k8macarthur** [comment]
So it looks like my back end is u’MacOSX’

If I run what you suggested I get this error when trying to import hyper spy:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-a830eed399bd> in <module>()
----> 1 import hyperspy.api as hs
      2 import numpy as np

/Users/macark/Documents/hyperspy#879/hyperspy/__init__.py in <module>()
      2 try:
      3     import sip
----> 4     sip.setapi('QVariant', 2)
      5     sip.setapi('QDate', 2)
      6     sip.setapi('QDateTime', 2)

ValueError: API 'QVariant' has already been set to version 1

**Comment by francisco-dlp** [comment]
Just to verify, did you import as follows and from a fresh kernel?

import matplotlib
matplotlib.rcParams["backend"] = 'Qt4Agg'
import hyperspy.api as hs
%matplotlib

**Comment by k8macarthur** [comment]
Oops, yes good spot. That does now let me bring up plots.

**Comment by k8macarthur** [comment]
However they are not entirely functional plots. I’ll investigate and repost one I understand slightly more what’s happening.

**Comment by francisco-dlp** [comment]
Ok, thanks.

**Comment by vidartf** [comment]
PS: When trying to reproduce this issue I also had some issues when plotting from an IPython console (Qt or in cmd), where the opened plots would be completely frozen (had to kill kernel to fix).

**Comment by vidartf** [comment]
Never mind that last bit, that was because backend/interactive mode was not set up properly. Matplotlib magic fixes it.

**Comment by k8macarthur** [comment]
Okay so I think I now get the error below reproducibly. I have both figures showing up with s.plot() but can’t seem to interact with them.

On a side note, I’ve noticed a new blank python window appearing when running this version of hyperspy. It seems to interfere with the selection of pop up windows. Although maybe this is easier to show on Thursday?

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/artist.pyc in draw_wrapper(artist, renderer, *args, **kwargs)
     59     def draw_wrapper(artist, renderer, *args, **kwargs):
     60         before(artist, renderer)
---> 61         draw(artist, renderer, *args, **kwargs)
     62         after(artist, renderer)
     63 

/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/figure.pyc in draw(self, renderer)
   1163 
   1164         self._cachedRenderer = renderer
-> 1165         self.canvas.draw_event(renderer)
   1166 
   1167     def draw_artist(self, a):

/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/backend_bases.pyc in draw_event(self, renderer)
   1807         s = 'draw_event'
   1808         event = DrawEvent(s, self, renderer)
-> 1809         self.callbacks.process(s, event)
   1810 
   1811     def resize_event(self):

/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/cbook.pyc in process(self, s, *args, **kwargs)
    561             for cid, proxy in list(six.iteritems(self.callbacks[s])):
    562                 try:
--> 563                     proxy(*args, **kwargs)
    564                 except ReferenceError:
    565                     self._remove_proxy(proxy)

/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/cbook.pyc in __call__(self, *args, **kwargs)
    428             mtd = self.func
    429         # invoke the callable and return the result
--> 430         return mtd(*args, **kwargs)
    431 
    432     def __eq__(self, other):

/Users/macark/Documents/hyperspy#879/hyperspy/drawing/figure.pyc in _on_draw(self, *args)
     20         if self.figure:
     21             canvas = self.figure.canvas
---> 22             self._background = canvas.copy_from_bbox(self.figure.bbox)
     23             self._draw_animated()
     24 

AttributeError: 'FigureCanvasMac' object has no attribute 'copy_from_bbox'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/artist.pyc in draw_wrapper(artist, renderer, *args, **kwargs)
     59     def draw_wrapper(artist, renderer, *args, **kwargs):
     60         before(artist, renderer)
---> 61         draw(artist, renderer, *args, **kwargs)
     62         after(artist, renderer)
     63 

/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/figure.pyc in draw(self, renderer)
   1163 
   1164         self._cachedRenderer = renderer
-> 1165         self.canvas.draw_event(renderer)
   1166 
   1167     def draw_artist(self, a):

/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/backend_bases.pyc in draw_event(self, renderer)
   1807         s = 'draw_event'
   1808         event = DrawEvent(s, self, renderer)
-> 1809         self.callbacks.process(s, event)
   1810 
   1811     def resize_event(self):

/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/cbook.pyc in process(self, s, *args, **kwargs)
    561             for cid, proxy in list(six.iteritems(self.callbacks[s])):
    562                 try:
--> 563                     proxy(*args, **kwargs)
    564                 except ReferenceError:
    565                     self._remove_proxy(proxy)

/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/cbook.pyc in __call__(self, *args, **kwargs)
    428             mtd = self.func
    429         # invoke the callable and return the result
--> 430         return mtd(*args, **kwargs)
    431 
    432     def __eq__(self, other):

/Users/macark/Documents/hyperspy#879/hyperspy/drawing/figure.pyc in _on_draw(self, *args)
     20         if self.figure:
     21             canvas = self.figure.canvas
---> 22             self._background = canvas.copy_from_bbox(self.figure.bbox)
     23             self._draw_animated()
     24 

AttributeError: 'FigureCanvasMac' object has no attribute 'copy_from_bbox'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/artist.pyc in draw_wrapper(artist, renderer, *args, **kwargs)
     59     def draw_wrapper(artist, renderer, *args, **kwargs):
     60         before(artist, renderer)
---> 61         draw(artist, renderer, *args, **kwargs)
     62         after(artist, renderer)
     63 

/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/figure.pyc in draw(self, renderer)
   1163 
   1164         self._cachedRenderer = renderer
-> 1165         self.canvas.draw_event(renderer)
   1166 
   1167     def draw_artist(self, a):

/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/backend_bases.pyc in draw_event(self, renderer)
   1807         s = 'draw_event'
   1808         event = DrawEvent(s, self, renderer)
-> 1809         self.callbacks.process(s, event)
   1810 
   1811     def resize_event(self):

/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/cbook.pyc in process(self, s, *args, **kwargs)
    561             for cid, proxy in list(six.iteritems(self.callbacks[s])):
    562                 try:
--> 563                     proxy(*args, **kwargs)
    564                 except ReferenceError:
    565                     self._remove_proxy(proxy)

/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/cbook.pyc in __call__(self, *args, **kwargs)
    428             mtd = self.func
    429         # invoke the callable and return the result
--> 430         return mtd(*args, **kwargs)
    431 
    432     def __eq__(self, other):

/Users/macark/Documents/hyperspy#879/hyperspy/drawing/figure.pyc in _on_draw(self, *args)
     20         if self.figure:
     21             canvas = self.figure.canvas
---> 22             self._background = canvas.copy_from_bbox(self.figure.bbox)
     23             self._draw_animated()
     24 

AttributeError: 'FigureCanvasMac' object has no attribute 'copy_from_bbox'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/artist.pyc in draw_wrapper(artist, renderer, *args, **kwargs)
     59     def draw_wrapper(artist, renderer, *args, **kwargs):
     60         before(artist, renderer)
---> 61         draw(artist, renderer, *args, **kwargs)
     62         after(artist, renderer)
     63 

/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/figure.pyc in draw(self, renderer)
   1163 
   1164         self._cachedRenderer = renderer
-> 1165         self.canvas.draw_event(renderer)
   1166 
   1167     def draw_artist(self, a):

/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/backend_bases.pyc in draw_event(self, renderer)
   1807         s = 'draw_event'
   1808         event = DrawEvent(s, self, renderer)
-> 1809         self.callbacks.process(s, event)
   1810 
   1811     def resize_event(self):

/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/cbook.pyc in process(self, s, *args, **kwargs)
    561             for cid, proxy in list(six.iteritems(self.callbacks[s])):
    562                 try:
--> 563                     proxy(*args, **kwargs)
    564                 except ReferenceError:
    565                     self._remove_proxy(proxy)

/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/cbook.pyc in __call__(self, *args, **kwargs)
    428             mtd = self.func
    429         # invoke the callable and return the result
--> 430         return mtd(*args, **kwargs)
    431 
    432     def __eq__(self, other):

/Users/macark/Documents/hyperspy#879/hyperspy/drawing/figure.pyc in _on_draw(self, *args)
     20         if self.figure:
     21             canvas = self.figure.canvas
---> 22             self._background = canvas.copy_from_bbox(self.figure.bbox)
     23             self._draw_animated()
     24 

AttributeError: 'FigureCanvasMac' object has no attribute 'copy_from_bbox'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/artist.pyc in draw_wrapper(artist, renderer, *args, **kwargs)
     59     def draw_wrapper(artist, renderer, *args, **kwargs):
     60         before(artist, renderer)
---> 61         draw(artist, renderer, *args, **kwargs)
     62         after(artist, renderer)
     63 

/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/figure.pyc in draw(self, renderer)
   1163 
   1164         self._cachedRenderer = renderer
-> 1165         self.canvas.draw_event(renderer)
   1166 
   1167     def draw_artist(self, a):

/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/backend_bases.pyc in draw_event(self, renderer)
   1807         s = 'draw_event'
   1808         event = DrawEvent(s, self, renderer)
-> 1809         self.callbacks.process(s, event)
   1810 
   1811     def resize_event(self):

/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/cbook.pyc in process(self, s, *args, **kwargs)
    561             for cid, proxy in list(six.iteritems(self.callbacks[s])):
    562                 try:
--> 563                     proxy(*args, **kwargs)
    564                 except ReferenceError:
    565                     self._remove_proxy(proxy)

/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/cbook.pyc in __call__(self, *args, **kwargs)
    428             mtd = self.func
    429         # invoke the callable and return the result
--> 430         return mtd(*args, **kwargs)
    431 
    432     def __eq__(self, other):

/Users/macark/Documents/hyperspy#879/hyperspy/drawing/figure.pyc in _on_draw(self, *args)
     20         if self.figure:
     21             canvas = self.figure.canvas
---> 22             self._background = canvas.copy_from_bbox(self.figure.bbox)
     23             self._draw_animated()
     24 

AttributeError: 'FigureCanvasMac' object has no attribute 'copy_from_bbox'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/artist.pyc in draw_wrapper(artist, renderer, *args, **kwargs)
     59     def draw_wrapper(artist, renderer, *args, **kwargs):
     60         before(artist, renderer)
---> 61         draw(artist, renderer, *args, **kwargs)
     62         after(artist, renderer)
     63 

/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/figure.pyc in draw(self, renderer)
   1163 
   1164         self._cachedRenderer = renderer
-> 1165         self.canvas.draw_event(renderer)
   1166 
   1167     def draw_artist(self, a):

/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/backend_bases.pyc in draw_event(self, renderer)
   1807         s = 'draw_event'
   1808         event = DrawEvent(s, self, renderer)
-> 1809         self.callbacks.process(s, event)
   1810 
   1811     def resize_event(self):

/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/cbook.pyc in process(self, s, *args, **kwargs)
    561             for cid, proxy in list(six.iteritems(self.callbacks[s])):
    562                 try:
--> 563                     proxy(*args, **kwargs)
    564                 except ReferenceError:
    565                     self._remove_proxy(proxy)

/Users/macark/anaconda/lib/python2.7/site-packages/matplotlib/cbook.pyc in __call__(self, *args, **kwargs)
    428             mtd = self.func
    429         # invoke the callable and return the result
--> 430         return mtd(*args, **kwargs)
    431 
    432     def __eq__(self, other):

/Users/macark/Documents/hyperspy#879/hyperspy/drawing/figure.pyc in _on_draw(self, *args)
     20         if self.figure:
     21             canvas = self.figure.canvas
---> 22             self._background = canvas.copy_from_bbox(self.figure.bbox)
     23             self._draw_animated()
     24 

AttributeError: 'FigureCanvasMac' object has no attribute 'copy_from_bbox'

**Comment by dnjohnstone** [comment]
Did this problem come out in the wash? i.e. @k8macarthur do you still get these bugs? Or is this PR still necessary?

**Comment by k8macarthur** [comment]
I believe it was a back end qt problem in the end. Changing how the libraries were imported fixed my problem rather than this pull. Sorry I can't be more help.

**Comment by francisco-dlp** [comment]
Is this still relevant @vidartf?

**Comment by vidartf** [comment]
It might be. At least parts of this should be an improvement on the current code base. But if it's not broken?

**Comment by thomasaarholt** [comment]
This fixes my trouble in #1109

**Comment by to266** [comment]
I resubmited this fix in https://github.com/hyperspy/hyperspy/pull/1121

**Comment by francisco-dlp** [comment]
Resubmitted in #1121 which is now merged.

**Pull request closed without merging**
