### PR TITLE
Signal1D/Signal2D merge into master

### PR DESCRIPTION
**Pull request by dnjohnstone**
Following #963 to 0.8.x this is the merge in to master.... I will finish it by the end of the week.

### CODE REVIEW

**Comment by dnjohnstone** [comment]
@francisco-dlp what's the correct thing to do with the .rst files deleted in this PR? I think I might have made a mistake there but I'm unclear why they're in master but not 0.8.x?

**Comment by francisco-dlp** [comment]
Just choose delete when asked during the merging process.

**Comment by dnjohnstone** [comment]
Great - that's what I did, just wanted to check that I'd remembered correctly that they were to be deleted

**Comment by dnjohnstone** [comment]
@francisco-dlp this should now be pretty much there - at least it's passing nosetests on my machine :)

Probably could do with checking plotting....

**Comment by dnjohnstone** [comment]
I don't particularly understand the error from Travis here.... or why I don't get it with anaconda nosetests on my machine?

**Comment by to266** [comment]
Maybe new `numpy`? Try updating the anaconda (`conda update -all`)

**Comment by dnjohnstone** [comment]
@to266 @francisco-dlp this should be pretty close now - on my machine it passes all nosetests and I can get through the EDS tutorials without problems.

The most vulnerable bits of the code to slips are Signal1DTools, Signal2DTools, and things that used to be in misc/spectrum_tools and misc/image_tools - the are vulnerable because they aren't tracked well in this merge because files were removed/renamed and some of it is only tested via plotting stuff. If you know of any changes that were made to those it would be good to know.

I think the current Travis failure is somewhere in here a small update for numpy in one of these tools - but I can't find it at the moment... (also still can't actually make it fail on my machine, which makes it hard to find)

**Comment by francisco-dlp** [comment]
Looks good, but I am afraid that we can't merge this until it passes all the tests...

**Comment by dnjohnstone** [comment]
@francisco-dlp of course - I really can't get my head around this travis one though... and I also don't understand why it's not failing on my machine... I've updated everything in the conda distribution and still nothing....

**Comment by CodeMonkeyJan** [comment]
As promised in #1058 I copied this PR and ran `nose` to see if I can replicate the errors.

At first 11 tests failed, but that was just because I had not installed `mock` yet.

After that nearly all tests ran without a problem. The only one which returned a failure state was the `test_model_navigation_indexer_slice` in `test_fancy_indexing.TestModelIndexing` (but also only roughly one in five times I ran the tests).
The Traceback for that was:

    Failure
    Traceback (most recent call last):
      File "C:\Anaconda3\lib\unittest\case.py", line 58, in testPartExecutor
        yield
      File "C:\Anaconda3\lib\unittest\case.py", line 600, in run
        testMethod()
      File "C:\Anaconda3\lib\site-packages\nose\case.py", line 198, in runTest
        self.test(*self.arg)
      File "C:\Users\Jan\Home\PhD Thesis\Projects\hyperspy-MERGE_0.8.x\hyperspy\tests\model\test_fancy_indexing.py", line 90, in test_model_navigation_indexer_slice
        nt.assert_false(m[0]._active_array[0, 0])
      File "C:\Anaconda3\lib\unittest\case.py", line 671, in assertFalse
        raise self.failureException(msg)
    AssertionError: True is not false

There was a strange situation once, when I tried to rerun this failed test (I'm using PyCharm by the way) and it gave me the following:

    Error
     Traceback (most recent call last):
      File "C:\Anaconda3\lib\unittest\case.py", line 58, in testPartExecutor
        yield
      File "C:\Anaconda3\lib\unittest\case.py", line 600, in run
        testMethod()
      File "C:\Anaconda3\lib\site-packages\nose\failure.py", line 39, in runTest
        raise self.exc_val.with_traceback(self.tb)
      File "C:\Anaconda3\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
        addr.filename, addr.module)
      File "C:\Anaconda3\lib\site-packages\nose\importer.py", line 47, in importFromPath
        return self.importFromDir(dir_path, fqname)
      File "C:\Anaconda3\lib\site-packages\nose\importer.py", line 94, in importFromDir
        mod = load_module(part_fqname, fh, filename, desc)
      File "C:\Anaconda3\lib\imp.py", line 234, in load_module
        return load_source(name, filename, file)
      File "C:\Anaconda3\lib\imp.py", line 172, in load_source
        module = _load(spec)
      File "<frozen importlib._bootstrap>", line 693, in _load
      File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 662, in exec_module
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "C:\Users\Jan\Home\PhD Thesis\Projects\hyperspy-MERGE_0.8.x\hyperspy\tests\model\test_fancy_indexing.py", line 23, in <module>
        from hyperspy._signals.eels import EELSSpectrum
      File "C:\Users\Jan\Home\PhD Thesis\Projects\hyperspy-MERGE_0.8.x\hyperspy\_signals\eels.py", line 27, in <module>
        from hyperspy.signals import Signal1D
      File "C:\Users\Jan\Home\PhD Thesis\Projects\hyperspy-MERGE_0.8.x\hyperspy\signals.py", line 41, in <module>
        from hyperspy._signals.eels import EELSSpectrum
    ImportError: cannot import name 'EELSSpectrum'
    -------------------- >> begin captured logging << --------------------
    hyperspy: DEBUG: Setting Qt API to v2
    hyperspy.gui: DEBUG: Loading hyperspy.gui
    hyperspy.gui: DEBUG: Current MPL backend: Qt4Agg
    hyperspy.gui: DEBUG: Current ETS toolkit set to: qt4
    --------------------- >> end captured logging << ---------------------

    E
    ======================================================================
    ERROR: Failure: ImportError (cannot import name 'EELSSpectrum')
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\nose\failure.py", line 39, in runTest
        raise self.exc_val.with_traceback(self.tb)
      File "C:\Anaconda3\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
        addr.filename, addr.module)
      File "C:\Anaconda3\lib\site-packages\nose\importer.py", line 47, in importFromPath
        return self.importFromDir(dir_path, fqname)
      File "C:\Anaconda3\lib\site-packages\nose\importer.py", line 94, in importFromDir
        mod = load_module(part_fqname, fh, filename, desc)
      File "C:\Anaconda3\lib\imp.py", line 234, in load_module
        return load_source(name, filename, file)
      File "C:\Anaconda3\lib\imp.py", line 172, in load_source
        module = _load(spec)
      File "<frozen importlib._bootstrap>", line 693, in _load
      File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 662, in exec_module
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "C:\Users\Jan\Home\PhD Thesis\Projects\hyperspy-MERGE_0.8.x\hyperspy\tests\model\test_fancy_indexing.py", line 23, in <module>
        from hyperspy._signals.eels import EELSSpectrum
      File "C:\Users\Jan\Home\PhD Thesis\Projects\hyperspy-MERGE_0.8.x\hyperspy\_signals\eels.py", line 27, in <module>
    from hyperspy.signals import Signal1D
      File "C:\Users\Jan\Home\PhD Thesis\Projects\hyperspy-MERGE_0.8.x\hyperspy\signals.py", line 41, in <module>
        from hyperspy._signals.eels import EELSSpectrum
    ImportError: cannot import name 'EELSSpectrum'
    -------------------- >> begin captured logging << --------------------
    hyperspy: DEBUG: Setting Qt API to v2
    hyperspy.gui: DEBUG: Loading hyperspy.gui
    hyperspy.gui: DEBUG: Current MPL backend: Qt4Agg
    hyperspy.gui: DEBUG: Current ETS toolkit set to: qt4
    --------------------- >> end captured logging << ---------------------
    
    ----------------------------------------------------------------------
    Ran 1 test in 0.002s
    
    FAILED (errors=1)

Wasn't the `fancy_indexing` the cause of some Travis errors recently?
I'm not sure if I understand the error correctly, but does it stem from the fact that we try to
import `EELSSignal` from `hyperspy._signals.eels` and there `Signal1D` is imported from the
`hyperspy.signals` proxy module. The proxy module then tries to import `EELSSignal` from
`hyperspy._signals.eels` again. Isn't this a cyclical import? If yes, why isn't this always a
cause for errors and why does it only affect `eels` and not `eds` (which has the same structure).

Replacing `from hyperspy.signals import Signal1D` with `from hyperspy._signals.signal1d import
Signal1D` in line 27 of `eels.py` fixed this problem! Now everything seems to work 100% of the time.

Sadly I could not replicate the failed `test_min_not_in_window` test in `test_eels.py` which seems to be the problem for Travis and AppVeyor. At least the cause for my error was also in the `eels.py`.

Sorry for the long comment and for not being able to help more, I hope the error report helps at least a little...

If it's important, my system is a Lenovo Thinkpad with Windows 7 Professional.

**Comment by dnjohnstone** [comment]
Hi Jan, many thanks for this! I think it is useful - the fancy_indexing thing is a known bug that fails its test at random (whilst very annoying, it doesn't seem to be a critical issue right now).

Interesting that you got it to work, I had the same behaviour locally but it was still failing travis, which confused me.

I think we might need @francisco-dlp at this stage...

**Comment by CodeMonkeyJan** [comment]
Small update:
The first fail still occurs very rarely (the one in `fancy_indexing`), so it's not completely gone, but rerunning the test now at least does not produce the bigger error I described. This randomness is indeed quite annoying :-/...

**Comment by to266** [comment]
https://github.com/dnjohnstone/hyperspy/pull/7

**Comment by dnjohnstone** [comment]
Ok - this has become a total mess....

As I understood it the plan was to merge this in to master before anything else to avoid repeated merge frustrations and the day that we decided that this PR was incredibly close except for the single Travis failure that I couldn't track on my machine because it wasn't failing on my machine.

Unfortunately, for some reason, loads of things have now been merged into both 0.8.x and master before the main Signal1D/Signal2D split was made. You'll see that the diff now stands at about 230 files which is going to make this incredibly difficult to review and this problem will only get worse if people keep merging things in to the master. Don't forget that every time you merge one of those PR's every file touched in both 0.8.x and that PR has to be remerged and since that's nearly everything in 0.8.x this creates a huge amount of work and only increases the likelihood of errors.

At this point I think that it might actually be best to start again with a fresh 0.8.x --> master merge because people have changed such a huge amount since this PR was made.

**Comment by francisco-dlp** [comment]
Currently tests are not passing due to i) external deprecation warnings ii) internal deprecations warnings. i) could be addressed in a different PR but ii) should be addressed in this one. Happily it seems that the non reproducible error is now gone, so it was probably due to a numpy bug.

The internal deprecation warning seems easy to fix : "The method `AxesManager.connect()` has been deprecated and will be removed in HyperSpy 0.10. Please use `AxesManager.events.indices_changed.connect()` instead."

**Comment by to266** [comment]
I've fixed the warning in https://github.com/dnjohnstone/hyperspy/pull/9 however it does not fix the behaviour - the swapped axes do not seem to be correctly connected to the navigation events, and I could not figure it out for now (will try agian tomorrow if noone fixes it by that time)...

**Comment by dnjohnstone** [comment]
@francisco-dlp this is now passing the tests thanks to @to266. 

As regards external deprecation warnings - maybe I don't understand them, but it seems like most of them are not our fault? e.g. travis picks up inspect.getargspec which should become inspect.signature, however, we only used this in one place and I've now made that change so I don't see how it can be us.

**Comment by francisco-dlp** [comment]
According to @to266 (see post above) the warning issue is now fixed but something is still wrong with the connection. Let's wait to hear back from @to266 tomorrow.

**Comment by to266** [comment]
The last issue I had with this is PR'ed here https://github.com/dnjohnstone/hyperspy/pull/10

Once that is merged, I suggest someone merges this ASAP. Any leftover bugs will be much easier to fix in separate PRs

**Comment by dnjohnstone** [comment]
Thanks @to266 for the final fix, I really should learn about events better -- if you're happy with this @francisco-dlp I'd also be happy if this got merged.... I've been using this for all my day to day stuff for the past couple of days and haven't hit any bugs that I haven't already fixed.

PS... myself and Tomas did go through plotting tests as well.

**Pull request merged**
