### PR TITLE
Fix windows traitui5

### PR DESCRIPTION
**Pull request by francisco-dlp**
Workaround/Fix? #765

### CODE REVIEW

**Comment by jat255** [comment]
Works for me on Arch Linux using the following packages:

```
python2-pyface 5.0.0-1
python2-traits 4.5.0-1
python2-traitsui 5.0.0-1
```

Importing the hyperspy magic gives me the following, and everything seems to work alright.
```python
>>> %hyperspy

HyperSpy imported!
The following commands were just executed:
---------------
import os
os.environ['QT_API'] = 'pyqt'
import sip
sip.setapi('QDate', 2)
sip.setapi('QDateTime', 2)
sip.setapi('QTextStream', 2)
sip.setapi('QTime', 2)
sip.setapi('QUrl', 2)
%matplotlib qt4
import numpy as np
import hyperspy.api as hs
import matplotlib.pyplot as plt
from hyperspy.hspy import *
```

**Comment by to266** [comment]
...it's getting ridiculous. We should get rid of traits asap. @vidartf, would switching from `traits` and `traitsui` to `traitlets` and some kind of simple UI (Qt?) be terrible for hyperspyui?

**Comment by vidartf** [comment]
@to266 If it switches to something that is compatible with Qt, it is no problem. But almost everything that supports PyQt on python v2 has to deal with `sip.setapi` at some point, to my experience. See http://wiki.qt.io/Differences_Between_PySide_and_PyQt.

I think for this PR, it should be sufficient to call this:
```python
sip.setapi('QString', 2)
sip.setapi('QVariant', 2)
```
If so, it would at least simplify the code a bit.

**Comment by vidartf** [comment]
PS: Even IPython's qtconsole requires PyQt's v2 API for interoperability, so order is important even then, c.f. https://github.com/ipython/ipython/issues/276.

**Comment by to266** [comment]
`traitsui` is the reason why we are not in python 3.x. Hopefully we won't have to care about the problems once we actually rewrite. 

The problem is that the task would be significantly big, however in the end the undertaker would receive no or very little reward

**Comment by vidartf** [comment]
> `traitsui` is the reason why we are not in python 3.x.

Version 5.0 of `traitsui` builds on 3.4 (https://travis-ci.org/enthought/traitsui/builds/87771060), so as far as I can see that is no longer true. I did some tests previously against the dev branch of `traitsui` to see how compatible hyperspy was, and there is quite a bit more than just running the `2to3` script to get python 3 support.

**Comment by vidartf** [comment]
From the 5.0 changelog:
> What's new in Traits UI 5.0.0
> This release features experimental support for Python 3 with the Qt toolkit!

**Comment by to266** [comment]
Good to know, thanks. I think I just may give it a go....

**Comment by francisco-dlp** [comment]
Thank you for the news. This being the case, there is nothing that stops us from supporting Python 3 anymore. Let's do it!

**Comment by magnunor** [comment]
Nice! Getting HyperSpy over to Python 3 would also make it easier getting it into the Debian repository (https://github.com/hyperspy/hyperspy/issues/455)

**Comment by vidartf** [comment]
Coming back on-topic for this PR:
For now, I'd suggest switching the PR to use
```python
sip.setapi('QString', 2)
sip.setapi('QVariant', 2)
```
as long as that works as I think it will (i.e. that other types inherit API version from QVariant). Then this should go into 0.8.x. If we get support for python3 in 0.9, this can then be removed (but should be kept in the python2 version).

**Comment by to266** [comment]
@vidartf , @francisco-dlp mentioned that only adding the two lines that you suggest is not actually enough - he tried that before.

**Comment by vidartf** [comment]
@to266 Ok, then it might have changed from before, or my memory was simply wrong ;)

**Comment by francisco-dlp** [comment]
@vidartf, most likely you're right but I have to test it in the windows
machine where I faced the problem as enthought 5s didn't yet landed in
Debian and anaconda. I kept on adding `setapi` entries until it stopped
complaining, but I didn't try QVariant. Thanks for the trick.

Francisco

2015-11-25 21:57 GMT+00:00 Vidar Tonaas Fauske <notifications@github.com>:

**Comment by vidartf** [comment]
@francisco-dlp : Update PR to `QVariant`, and then merge?

**Comment by francisco-dlp** [comment]
I've tested what you propose but it doesn't work in my system, should we merge it as it is?

**Comment by vidartf** [comment]
As you can see from the latest CI, moving the code to `hyperspy.api` breaks the build.

**Comment by francisco-dlp** [comment]
It should be fixed now, I''ve moved it to `hyperspy/init.py"

2015-12-18 15:05 GMT+00:00 Vidar Tonaas Fauske <notifications@github.com>:

**Comment by francisco-dlp** [comment]
@vidartf, is this ready to merge?

**Comment by vidartf** [comment]
@francisco-dlp : From my point of view, yes. But #805 confused me a bit. Does #805 supersede this? Undo this? Extended it? I kind of feel I've lost the overview here.

**Comment by francisco-dlp** [comment]
No, none of them. One of the reasons why we used to provide a start script and later a magic was to set up the toolkits properly. With old IPython versions a start script was necessary, but this is not the case any more. We introduced the magic to replace the start script, but, by moving `setapi`  from the magic to `hyperspy.__init__`, we no longer require the magic either. That's the point of the discussion in #805. Regardless of the outcome of that discussion, in my opinion it is right to move `setapi` to `hyperspy.__init__`. If you agree, could you consider merging this branch?

**Comment by vidartf** [comment]
Do we have to add a dependency on `sip` in `setup.py` etc.?

**Comment by francisco-dlp** [comment]
Good point. I would suggest to place the code in a  `try` statement
instead. Do you agree?

2015-12-29 16:20 GMT+00:00 Vidar Tonaas Fauske <notifications@github.com>:

**Comment by vidartf** [comment]
Sure, a `try`/`except ImportError` bracket should fix any issues. I agree that it is a better fix, since `sip` is linked to PyQt only, which is not a requirement.

**Comment by francisco-dlp** [comment]
Done, thanks!

2015-12-29 17:05 GMT+00:00 Vidar Tonaas Fauske <notifications@github.com>:

**Pull request merged**
