### PR TITLE
Fix progressbar showing when it shouldn't

### LINKED ISSUE #1758: m.as_signal progressbar always shows
On eels spectra, s.remove_background(show_progressbar=False) still shows the progressbar.

### PR DESCRIPTION
**Pull request by thomasaarholt**
Fixes #1758.

### CODE REVIEW

**Review by ericpre — DISMISSED** [review]
This doesn't work for the default case (`show_progressbar=None`).

**Comment by thomasaarholt** [comment]
That should do it. Thanks for noticing!

**Comment by ericpre** [comment]
Have you tested it? I am asking this, because when I test it, I get an error.

**Comment by thomasaarholt** [comment]
Sorry, I stupidly assumed it would be fine.

The error lies with how the `_as_signal_iter` method is written. `progressbar` takes `show_progressbar` as an argument for the `position` variable. That's what confused me. I'll have another look tomorrow.

**Pull request merged**
