### PR TITLE
Rectangular Region of Interest (ROI)

### PR DESCRIPTION
**Pull request by francisco-dlp**
This is a reworked version of #393 (I've merged #393 into it) that aims at separating the ROI and plotting code. The widget is taken from #393 but I have taken a different approach to implementing the ROI that does not rely in modifying `DataAxis` and that should make it easier to create new ROIs.

Note that this branch includes #424, #423, #422 and #434.

Usage
--------

```python
>>> s = signals.Spectrum(np.random.random((10, 20, 100)))
>>> roi = utils.roi.RectangularROI(1,3,3,5)
>>> roi(s)
<Spectrum, title: , dimensions: (2, 2|100)>
>>> roi.right = 10
>>> roi(s)
<Spectrum, title: , dimensions: (7, 2|100)>

```

The integration with the widget is not yet user friendly. The following script shows how to do it, any user friendly syntax ideas?

```python

from hyperspy.drawing.widgets import ResizebleDraggableRectangle


roi = utils.roi.RectangularROI(0, 10, 0, 10)
s = signals.Spectrum(np.random.random((10, 20, 100)))
s.axes_manager[0].scale = 0.5
s.axes_manager[0].scale = 0.1
sroi = utils.interactive(roi.__call__, event=roi.events.roi_changed, signal=s)
w = ResizebleDraggableRectangle(s.axes_manager.deepcopy())
s.plot()
s._plot.pointer.close()
w.add_axes(s._plot.navigator_plot.ax)

def update_roi():
    roi.left = w.axes_manager[0].index
    roi.top = w.axes_manager[1].index
    roi.bottom = w.axes_manager[1].index + w.ysize
    roi.right = w.axes_manager[0].index + w.xsize

w.events.changed.connect(update_roi)
ssum = utils.interactive(sroi, sroi.sum, event=sroi.events.data_changed, axis="navigation")
ssum.plot()
ssum.events.data_changed.connect(ssum._plot.signal_plot.update)

```

TODO
--------

- [ ] unittests.
- [ ] docstrings.
- [ ] User guide documentation.
- [ ] Simple syntax to change the ROI interactively and display the result.
- [ ] Fix bug: the bottom left resizers is slightly out of place.
- [ ] Fix bug: currently it is possible to resize and move the widget beyond the right/bottom axis limits.
- [ ] Fix bug: in the widget top/bottom left/right can currently be reversed i.e. it is possible to set left > right and bottom > top.

### CODE REVIEW

**Comment by vidartf** [comment]
Without having read the actual code suggested (will do it after writing this), and with the experience of implementing the previous one in a quick (and dirty) way, this is how I think ROIs would best be implemented:
* ROIs are mainly geometry + drawing/events/interaction (matplotlib code)
* ROIs should also have events, e.g. a simple ```changed``` event wich fires when the region selected by the ROI changes.
* Navigation by ROI would then just be a separate class that connects ROI change with an axes_manager.
* It would be very nice if the same ROI could be added to several plots, e.g. ROIs keep an internal list of matplotlib axes. Correspondingly, the navigator class could keep a list of axes_managers.

**Comment by vidartf** [comment]
Having read through it, I see that most of the stuff I would want is already in place, but I have some comments:
* I see you separate the widget and ROI. That makes sense, as long as the ROI class has an ability to turn off and on suppression of events: You wouldn't want to fire four events for an ROI move just because left, right, top and bottom all change. I'm guessing the ROI could also be made responsible for creating/managing the widget, if the user requests one to be created (boolean property/arg?).
* For the ROIs ```changed``` event, it would be nice if it triggered with arguments: Either a reference to itself, and/or updated coordinates.
* I was not able to understand why when registering signal a ```signal_deepcopy_with_new_data(signal.data)``` is put in the ```out``` part of the tuple. Could you give an example of what this would do/prevent? I'm simply not able to extract it's use by just reading the code.
* Currently it registers signals, which makes it nice and tight for certain operations, but I'm unsure about others: Say you have an image signal, and an image stack. If you would want the ROI to be on both of them, would not the slicing of the stack in the ROIs ```__call__``` fail?
* I think all ROIs should have a common ancestor

I can make a PR for the updated widget code (it would need events too) once the ROI interface has been agreed.

**Comment by francisco-dlp** [comment]
I agree with all of your suggestions. 

> I was not able to understand why when registering signal a > signal_deepcopy_with_new_data(signal.data) is put in the out part of the tuple. Could you give an example of what this would do/prevent? I'm simply not able to extract it's use by just reading the code.

This is to implement interactivity, I use the feature in the second script. However, I don't like this solution. I think it'll be better to provide interactivity using an external function, e.g. a generalized version of the `InteractiveNavSum` class of the second script.

> Currently it registers signals, which makes it nice and tight for certain operations, but I'm unsure about others: Say you have an image signal, and an image stack. If you would want the ROI to be on both of them, would not the slicing of the stack in the ROIs __call__ fail?

Yes, that would fail. A workaround could be to add a "space" argument to `__call__` to select between the navigation and signals spaces.

**Comment by vidartf** [comment]
> This is to implement interactivity

Ah! Now I see what it's supposed to do: The "out" signal is basically a signal who is "navigated" by the ROI? I think this might not always be wanted: What if all I want is e.g. a rectangle to measure some dimensions? I.e. where I don't need the sliced data. As it is, this will automatically use the memory for the sliced data (since slicing makes a copy). I think the solution would be to have ```roi.register()``` take an argument that specifies whether this should be done or not (set the "out" bit of the tuple to None if not). ```__call__(s, register=True)``` would of course always specify this argument as True, as it is used for slicing.

> Yes, that would fail. A workaround could be to add a "space" argument to ```__call__``` to select between the navigation and signals spaces.

The "space" argument would work (alternatively by axes indices/names), but it also needs to be passed when registering (as ```update``` needs it to do its job correctly). Maybe it could default to "navigation"? Or maybe "auto"?

Let me try to make a user friendly syntax for widgets, based on your second script (note, this is the wish, but wouldn't work now):

```python
# Creation, as before
roi = utils.roi.RectangularROI(0, 10, 0, 10)
s = signals.Spectrum(np.random.random((10, 20, 100)))
s.axes_manager[0].scale = 0.5
s.axes_manager[0].scale = 0.1

# ROI registration creates widget by default if matplotlib is 
# interactive and signal has a valid plot
s.plot()
sroi = roi(s, register=True, space="signal")
# AND/OR:
roi.make_widget(s)    # Registers s if not already 
                      # registered, and adds widget 

# As before:
ssum = interactive_nav_sum(sroi)
ssum.plot()
ssum.events.data_changed.connect(ssum._plot.signal_plot.update)
# That last line should be made easier:
# Signal class should have an update_plot function (useful either way), that way
# interactive_nav_sum could connect even without the plot existing (as update_plot
# without a valid plot either plots the signal or does nothing).
```

Then the widget would be updated to not taking an AxesManager, but simply have events that the ROI connects to on widget creation in ```make_widget()```:

```python
# in ROI class:

def on_widget_change(self, widget):
    with self.events.suppress:
        self.left = widget.left  # These would need to be added
        self.right = widget.right
        self.top = widget.top
        self.bottom = widget.bottom
    self.events.changed.trigger(self)

def make_widget(self, signal):
    w = ResizebleDraggableRectangle()
    w.set_axes(signal._plot.navigator_plot.ax)   # Rename add_axes as each
                                                 # patch can only have one axes
    w.events.changed.connect(self.on_widget_change)
    self.widgets[signal] = w
```

**Comment by vidartf** [comment]
Another possible alternative is for Signal to have a collection of ROIs/Markers that are asked to create artists on ```plot()```. This would mean they persist over new calls to plot(), and it improves bookkeeping.

**Comment by francisco-dlp** [comment]
The fact that the signal registration feature was hard to understand fully convinced me that it was simply a poor idea. Looking for a more intuitive, general and simple solution I have created a new `interactive` function (see #434), removed the signal registration feature and updated the second example script to account for the changes. It follows the updated script:

```python

from hyperspy.drawing.widgets import ResizebleDraggableRectangle


roi = utils.roi.RectangularROI(0, 10, 0, 10)
s = signals.Spectrum(np.random.random((10, 20, 100)))
s.axes_manager[0].scale = 0.5
s.axes_manager[0].scale = 0.1
sroi = utils.interactive(s, roi.__call__, event=roi.events.roi_changed, signal=s)
w = ResizebleDraggableRectangle(s.axes_manager.deepcopy())
s.plot()
s._plot.pointer.close()
w.add_axes(s._plot.navigator_plot.ax)

def update_roi():
    roi.left = w.axes_manager[0].index
    roi.top = w.axes_manager[1].index
    roi.bottom = w.axes_manager[1].index + w.ysize
    roi.right = w.axes_manager[0].index + w.xsize

w.events.changed.connect(update_roi)
ssum = utils.interactive(sroi, sroi.sum, event=sroi.events.data_changed, axis="navigation")
ssum.plot()
ssum.events.data_changed.connect(ssum._plot.signal_plot.update)

```

What do you think about the new approach?

> What if all I want is e.g. a rectangle to measure some dimensions? I.e. where I don't need the sliced data.

I think that your issue should be solved now.

> The "space" argument would work (alternatively by axes indices/names)

Yes, I agree, a space is too limiting. I think that an "axes" argument, as you propose, is better; maybe with a default to the first two nav axes?

I like your `on_widget_change` and `make_widget` methods, but I am not so convinced about automatically plotting the widget if there is an active plot because what to plot is not always well defined. If we are slicing the signal axes of a nD image then plot is well defined, but, if we're slicing e.g. the nav axes of a spectrum image one may like to add the ROI to the HAADF or to some elemental maps, not to the "navigator". What about:

    roi.add_widget(im)

where im is the Image instance?

Once the widget is created it can be added to other matplotlib axes with widget.add_axes. However, to add a widget to two images with different pixel sizes we need to create another widget because the `axes_manager` would be different.

I don't think that it is a good idea to remove `axes_manager` from the widget because it determines the step size.

Regarding storing the ROIs in the signal, I think that it is a good idea that should be pretty straightforward to implement given that the ROIs can be recreated from their __repr__ string. So, eventually, we could create a new section in `metadata` to store them.

**Comment by vidartf** [comment]
I'll have comments on the other things later, but just quickly:

> I don't think that it is a good idea to remove axes_manager from the widget because it determines the step size.

Wouldn't the step size always be one index value up/down? Going from index to value can be done with the matplotlib transforms, if needed.

**Comment by francisco-dlp** [comment]
The problem is that the ROIs should operate in the axes units and, therefore, the step is then defined by `DataAxis.scale`. maplotlib's transforms don't know about HyperSpy axes scales...

**Comment by vidartf** [comment]
> What do you think about the new approach?

It's actually quite powerful, but it might be a little opaque at first, so maybe add the following utility on ROI:

```python
def interactive(self, signal):
        return hyperspy.interactive.interactive(signal, self.__call__, 
                                         event=self.events.roi_changed,
                                         signal=signal)
```


>  if we're slicing e.g. the nav axes of a spectrum image one may like to add the ROI to the HAADF or to some elemental maps, not to the "navigator". What about:
>
>  ```roi.add_widget(im) ```
>
> where im is the Image instance?

Well, personally I would like to have the ROI in all of those images, but I see the argument, and agree with the way of adding it.

>Once the widget is created it can be added to other matplotlib axes with widget.add_axes. However, to add a widget to two images with different pixel sizes we need to create another widget because the axes_manager would be different.

We would have to create another widget anyway since one patch can only go in one matplotlib axes. So I would have ROI keep a collection of all its widgets, and be connected to all of them. We would of course have to make sure that the ROI -> widget connection is working as well. As the ROI is the "parent" it would have to be responsible for avoiding infinite recursion w.r.t. events.

Finally: I see you have defined top left corner as origin (bottom having a higher value than top), but matplotlib uses bottom left. Is there already an established convention in hyperspy for bottom/top names? If not, which should we use?

**Comment by vidartf** [comment]
PS: I'll make some PRs with most of this stuff as soon as we make a decision to the bottom/top thing.

**Comment by francisco-dlp** [comment]
I agree with everything, except for your remark regarding MPL image conventions.

Using MPL 0.14, the following command:

    plt.imshow(scipy.misc.lena())

produces this figure:

lena

So, isn't MPL setting the origin at the top/left?

**Comment by vidartf** [comment]
Well, this is where it gets a bit complicated: In "normal" MPL plots, the origin is at bottom left. However, when you plot images, they put origin at top left with inverted y-axis as you show (because that is image convention). I cannot see if they actually use the words top/bottom in code anywhere, but in the docs they use it:
> set_xy(xy)
>      Set the left and bottom coords of the rectangle
>      ACCEPTS: 2-item sequence

This all means, that if we want to have consistent use of the keywords, we need to check where origin is at run-time...

**Comment by vidartf** [comment]
Or we simply say it will always be images when 2D, and define origin as top left of course :)

**Comment by francisco-dlp** [comment]
I vote for the latter.

**Comment by vidartf** [comment]
Alright, I made a PR with most of these changes. It got quite big in the end, but a lot of it is refactoring of the widgets. I'll doc them up later, just want to make sure everything is OK first :)

**Comment by vidartf** [comment]
Not sure if I got everything, but most of it should be done now?

**Comment by vidartf** [comment]
This diff is also quite a bit larger than it should be...

**Comment by francisco-dlp** [comment]
This one should be clean now too. Thanks for spotting the problem @vidartf.

**Comment by francisco-dlp** [comment]
Closing in favour of #843

**Pull request closed without merging**
