### PR TITLE
Release 1.5

### PR DESCRIPTION
**Pull request by francisco-dlp**
Waiting for:

- [x]  #2180 
- [x] #2216 
- [x] #1989 (thomasaarholt#12 needs review)

Also:

- [x] https://github.com/hyperspy/hyperspy_gui_traitsui/pull/21
- [x] https://github.com/hyperspy/hyperspy_gui_traitsui/pull/22
- [x] https://github.com/hyperspy/hyperspy_gui_ipywidgets/pull/21
- [x] https://github.com/hyperspy/hyperspy_gui_ipywidgets/pull/19

### CODE REVIEW

**Comment by dnjohnstone** [comment]
Any chance we could try to get #1497 in to this one too, please?

**Comment by dnjohnstone** [comment]
On a related note - how many of the PRs marked for "release: next minor" are actually planned to be merged for hyperspy-1.5.0? Just those marked in the 1.5 milestone - or all those marked for the next minor. Indeed, when is 1.5.0 due?

In general it would be very helpful if we could find a way to structure and plan the release cycle moving forward. I'm considering upstreaming various features from pyxem to hyperspy for example, but in order to plan our own release cycle we'd need to have a clear hyperspy release cycle that is more structured than the current ad-hoc basis.

Currently I intend to work towards a quarterly minor release as that seems to be about the time it takes us to make a manageable but not insignificant number of changes, at least for the moment.

**Comment by francisco-dlp** [comment]
@dnjohnstone, the target for v1.5 are those with the v1.5 milestone. If things go well, we may be able to release it tomorrow.

I agree that with the growing number of packages that depend on HyperSpy it will be necessary to release more frequently. For that we should streamline the release process.

**Comment by francisco-dlp** [comment]
This branch is building correctly in https://github.com/conda-forge/hyperspy-feedstock/pull/36

Once the PRs in the header are merged, we'll be ready to release.

**Comment by francisco-dlp** [comment]
@ericpre, is this ready to merge?

**Comment by ericpre** [comment]
Yes, it looks good to me!

**Pull request merged**
