### PR TITLE
Update version to 1.0+dev

### PR DESCRIPTION
**Pull request by vidartf**
Identical to #1084, but I have created this via Github's "edit" functionality, so this has never touched my local directory. Let's see what Travis says.

### CODE REVIEW

**Comment by vidartf** [comment]
Same problem it seems. I think we might need to contact Travis here?

**Comment by francisco-dlp** [comment]
(+o+) I've moved things around a little in my last commit to see what happens. If it still fails I'll follow your advice and contact travis by email.

**Comment by vidartf** [comment]
Well this is fun: The build of the branch succeeds, while the PR build does not :-/

**Comment by francisco-dlp** [comment]
travis-ci/travis-ci#6195

**Pull request merged**
