### PR TITLE
more useful axesmanager repr string

### PR DESCRIPTION
**Pull request by to266**
```python
In [1]: import hyperspy.api as hs
import numpy as np
   ...: 

In [2]: s = hs.signals.Signal2D(np.random.rand(10, 11, 12, 13))

In [3]: s.axes_manager
Out[3]: 
<Axes manager, axes: (11, 10|13, 12)>
            Name |   size |  index | offset |  scale |  units 
================ | ====== | ====== | ====== | ====== | ====== 
     <undefined> |     11 |      0 |      0 |      1 | <undefined> 
     <undefined> |     10 |      0 |      0 |      1 | <undefined> 
---------------- | ------ | ------ | ------ | ------ | ------ 
     <undefined> |     13 |        |      0 |      1 | <undefined> 
     <undefined> |     12 |        |      0 |      1 | <undefined> 
```

### CODE REVIEW

**Comment by francisco-dlp** [comment]
This needs a test e.g. simply calling the method would do.

Beside, how hard would it be to implement a repr_html version of the for the notebook?

**Comment by francisco-dlp** [comment]
html repr seems broken at present. In case that it serves as inspiration, [this is how they do it in pandas](https://github.com/pydata/pandas/blob/20dd17a70063387ccca5f7aca3dbefc904d99457/pandas/formats/style.py#L42).

Beside, could you add a test which simply call the __repr__ and __repr_html__ methods just to make sure that at least they don't badly break?

**Comment by to266** [comment]
What do you mean it's broken? Seems to work for me, although it does not look very good with the separator of the two spaces....

I'll try to find a better separator for the two spaces, but if nothing works, I'll just remove the html repr - I'll leave it for someone else.

By the way they use `jinja` for the templates... And that's understandable, it's often the most sensible way to look at some table data - to just write it out. Not sure it's worth all this effort for the `axes_manager`

**Comment by francisco-dlp** [comment]
Yes, I meant the separator issue

axes_manager_html_repr

**Comment by to266** [comment]
Huh, looks like the notebook does not render _all_ html - at least not correctly - I am not able to make one of the lines bolder or change it's color, even though the code is definitely correct, as tested in here 
https://jsfiddle.net/tcwnR/172/

**Comment by francisco-dlp** [comment]
Are you going to do something about it?

**Comment by to266** [comment]
Should I remove the `_repr_html_`?

I could not find a way to make the separator nice, since notebook does not render different color or thickness lines, apparently....

Pandas does not use that, so they're fine. Two tables would be a solution... What do you think?

**Comment by francisco-dlp** [comment]
+1 for two tables

**Comment by francisco-dlp** [comment]
It still looks funny:

am_repr_html

**Comment by francisco-dlp** [comment]
Actually, in Chrome it looks ok.

**Comment by to266** [comment]
The simple tests added. Let me know if there is anything else required from my side

**Pull request merged**
