### PR TITLE
RELEASE v1.2

### PR DESCRIPTION
**Pull request by francisco-dlp**
## TODO - RELEASE

- [x] Merge #1431 if ready.
- [x] Check and fix broken links ``make linkcheck | grep broken``
- [x] Update demos
- [x] Merge #1487 
- [x] Add Python 3.6 tests
    - [x] travis. In progress #1501
    - [x] appveyor
- [x] Update setup.py to avoid dask 0.14
- [x] Create Python installers
- [x] Test Python installers
- [x] Create Windows installers
- [x] Test Windows installers
- [x] Create Release in GitHub
- [x] Update DOI in `README.rst` and `citing.rst`  
- [x] Test Bundle installer
    - [x] with admin rights
    - [x] without admin rights
- [x] Upload docs
- [x] Upload to pypi
- [x] Update conda recipe
- [x] Upload to GH
- [ ] Update website
- [ ] Announce in mailing list

### CODE REVIEW

**Comment by magnunor** [comment]
Merge https://github.com/hyperspy/hyperspy/pull/1467 as well before the release (if people think it is ready)?

**Comment by k8macarthur** [comment]
It would be really nice if #1306 could be included in the next release too? Again if people think it is ready?

**Comment by magnunor** [comment]
@k8macarthur, #1306 would be really nice to have in this release. But it currently needs some work, do you have time do this today (as I think @francisco-dlp want this release today)?

**Comment by magnunor** [comment]
https://github.com/hyperspy/hyperspy/pull/1467 is merged

**Comment by francisco-dlp** [comment]
@magnunor and @k8macarthur  I don't think that there is time to merge #1306 in time for the release today. There are a number of other cool PRs such as this one that are almost ready, so v1.3 should not be too far away.

**Comment by k8macarthur** [comment]
Curse my current time difference, I was asleep... @magnunor thanks for your comments on my commit I'll look through them today.

**Comment by to266** [comment]
https://github.com/hyperspy/hyperspy/pull/1471

This one is trivially simple, would be nice to include :)

**Comment by francisco-dlp** [comment]
Merged. As you've noticed the release didn't happen yesterday as planned but let's make it happen today. It would be nice to fix #1470, #1469, #1455 and #1464 fix for v1.2. If any of you decide to work on these bugs, leave a little post so that we don't overlap our efforts.

**Comment by magnunor** [comment]
The "Update demos" step involves manually going through the demos and making sure they work? I could do that step unless someone else is working on it.

**Comment by francisco-dlp** [comment]
Nobody is working on that AFAIK.

**Comment by magnunor** [comment]
I ended up going through all of them for correcting typos, and I started with the EELS one, but got slightly derailed due to finding a bug (https://github.com/hyperspy/hyperspy/pull/1487).  I'll finish the EELS one, so some else needs to check the others.

**Comment by francisco-dlp** [comment]
Finally everything looks good, so chances are that we'll release today. Just waiting to see if CI passes in conda forge too https://github.com/conda-forge/hyperspy-feedstock/pull/11

**Comment by francisco-dlp** [comment]
Still waiting for CI passes in conda forge too https://github.com/conda-forge/hyperspy-feedstock/pull/11 , otherwise this should be it so, with a bit of luck, we'll release as soon as tests pass in macOS.

**Comment by francisco-dlp** [comment]
Mmm, something is wrong with CI, no tests are triggered here or in https://github.com/conda-forge/hyperspy-feedstock/pull/11, any idea of what's going on?

**Comment by francisco-dlp** [comment]
It seems to be a [known GH issue](https://status.github.com/messages)

**Comment by francisco-dlp** [comment]
In case that somebody is wondering what's going on, [we're waiting for travis](https://github.com/conda-forge/hyperspy-feedstock/pull/11) to tell us if everything is ok in conda forge macOS. Furthermore, we need to setup travis to build py36 wheels, see #1501.

**Comment by francisco-dlp** [comment]
I am giving up for today. travis is still experiencing issues and debugging is very slow. On the up side, it seem that #1501 works well except for the min environment that I couldn't debug due to the lack of log at the moment. Also we're still waiting for travis in conda forge.

**Pull request merged**
