### PR TITLE
Quickfix for #766

### PR DESCRIPTION
**Pull request by vidartf**
#766 had a timing dependent test bug. This should fix it, but please review carefully :)

### CODE REVIEW

**Comment by vidartf** [comment]
Note that while `test_save_load_cycle` compares the `Aquisiton_time` field as well, this should still be correct, as the value from the original file will be kept.

**Comment by francisco-dlp** [comment]
Actually, I'm not sure that setting the Acquisition_time to now is a
good idea as it may be misleading. What about setting it to a default
clearly wrong value instead if the field is required?
Also, now that you're at it, shouldn't `Aquisiton_time field` be
`Acquisition_time`?

**Comment by vidartf** [comment]
Defaulting to UNIX epoch (1970) as default when missing is definitely possible, or the field could be renamed to something like `creation_time`? Not sure what you refer to by `Aquisiton_time field`.

**Comment by francisco-dlp** [comment]
UNIX epoch should be fine.

I was just pointing at a typo: you wrote Aquisition, should be Acquisition. The typo is also present in the code.

**Comment by vidartf** [comment]
Erm, currently `hyperspy.tests.mva.test_decomposition.TestGetExplainedVarinaceRation.test_data` is failing... Other than that I think this is OK now.

**Pull request merged**
