### PR TITLE
Add type-hinting to commonly-used methods

### PR DESCRIPTION
**Pull request by thomasaarholt**
### Description of the change
1. Added "eager" imports under the `TYPE_CHECKING` filter (which is only `True` during e.g. pylance/mypy type checking) so that autocomplete works for the lazy modules imported through `hyperspy.api` and `hyperspy.api_nogui`.
2. Added type-hints for several commonly-used methods. Particularly useful when coding in VSCode, since the pylance engine understands e.g.:

```python
from hyperspy._signals.eels import EELSSpectrum

s = EELSSpectrum([1, 2, 3])
ax = s.axes_manager[0]
# ax.high<TAB> autocompletes to high_value

m = s.create_model()
a = m[0]
# a.na<TAB> autocompletes to name
```
Using the VSCode pylance Type Checking Mode setting "basic" is very useful, as it provides in-editor messages showing mypy errors. It also shows a lot of possible improvements, for instance where we are referencing child-class methods in parent-classes. For instance MVATools referring to entries of `axes_manager` even though this isn't an attribute of the 
MVATools class.

### Progress of the PR
- [x] Change implemented (can be split into several points),
- [ ] add an changelog entry in the `upcoming_changes` folder (see [`upcoming_changes/README.rst`](https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/upcoming_changes/README.rst)),
- [ ] Check formatting changelog entry in the `readthedocs` doc build of this PR (link in github checks)
- [ ] add tests,
- [ ] ready for review.

### CODE REVIEW

**Comment by thomasaarholt** [comment]
@ericpre might be interested in this issue too, regarding VSCode/pylance/pyright not supporting lazy loaded modules: https://github.com/microsoft/pyright/issues/3595

**Comment by thomasaarholt** [comment]
There are a few places where we dynamically add entries to `__all__`, like in hyperspy/signals.py and `hyperspy/components1d.py` (and 2d). VSCode won't be able to autocomplete in those cases, but I think we just have to live with that. These don't work in jupyter notebook either (before running the code):
```python
import hyperspy.components1d.<TAB> # yields no suggestions in jupyterlab or vscode
import hyperspy.signals.<TAB> # same
```

**Comment by ericpre** [comment]
> There are a few places where we dynamically add entries to `__all__`, like in hyperspy/signals.py and `hyperspy/components1d.py` (and 2d). VSCode won't be able to autocomplete in those cases, but I think we just have to live with that. These don't work in jupyter notebook either (before running the code):
> 
> ```python
> import hyperspy.components1d.<TAB> # yields no suggestions in jupyterlab or vscode
> import hyperspy.signals.<TAB> # same
> ```

This works fine with jupyter, a simple way to test it is to run the binder: [Live demos (Binder)](https://mybinder.org/v2/gh/hyperspy/hyperspy-demos/main)

**Comment by thomasaarholt** [comment]
Odd. It works in the binder, but I just tried making a new conda env with hyperspy 1.7.1 and jupyter notebook, and there
`import hyperspy.comp<TAB>` suggests `component`/`components1d`/`components2d`, but `import hyperspy.components1d.<TAB>` doesn't do anything.

**Comment by ericpre** [comment]
> Odd. It works in the binder, but I just tried making a new conda env with hyperspy 1.7.1 and jupyter notebook, and there `import hyperspy.comp<TAB>` suggests `component`/`components1d`/`components2d`, but `import hyperspy.components1d.<TAB>` doesn't do anything.

I have just tried on binder and locally and it works, did you wait enough (2-3s) that the module load after pressing `<TAB>`?

**Comment by ericpre** [comment]
Should this PR be closed in favour of #2986?

**Pull request closed without merging**
