### PR TITLE
Fix matplotlib 3.3.0

### PR DESCRIPTION
**Pull request by ericpre**
Fix issue when specifying legend in `hs.plot.plot_spectra`, which is broken with matplotlib 3.3.0 and this is why travis is hanging.

### Progress of the PR
- [x] fix legend,
- [x] fix deprecation warning,
- [x] ready for review.

### CODE REVIEW

**Review by tjof2 — APPROVED** [review]

**Comment by francisco-dlp** [comment]
LGTM. Just a small question: why not requiring mpl >= 3.3.0 instead of adding logic to maintain compatibility with old versions?

**Comment by ericpre** [comment]
I think we can't support only the last version of matplotlib, if other libraries are not supporting the last version, this would be problematic.

**Comment by francisco-dlp** [comment]
I see how that can be a problem when packaging hyperspy for linux since most distributions' python packages tend to lag a bit behind.

**Comment by tjof2** [comment]
Can we get this into Rnm too to fix Travis?

**Comment by ericpre** [comment]
It is on RnM now.

**Pull request merged**
