### PR TITLE
Model as dict

### PR DESCRIPTION
**Pull request by to266**
as per https://github.com/hyperspy/hyperspy/wiki/HSPEP1%3A-Save-models-in-the-same-hdf5-file-as-the-data

Still lacks user guide entries and tests (any ideas for them are welcome, as none similar are present at the moment)

### CODE REVIEW

**Comment by francisco-dlp** [comment]
I have postponed this to 0.9 as there is not way that we can get such a delicate feature on time for 0.8 (due this week).

**Comment by to266** [comment]
@francisco-dlp , ready for review.

The `whitelist` syntax got changed some more, now supports multiple flags, that can in addition be used for other things (such as flagging certain attributes to be sliced when slicing model (to be impletented later, but the flag is already there))

**Comment by to266** [comment]
I have to check that copies of arrays are stored when 'pickable=True'

**Comment by to266** [comment]
Ready for review / merging

@francisco-dlp , this branch is already fixed wrt your comments in https://github.com/hyperspy/hyperspy/pull/720

**Pull request merged**
