### PR TITLE
Documentation: Add Examples for overlaying quad mesh.

### PR DESCRIPTION
**Pull request by CSSFrancis**
### Description of the change
Added an example for overlaying images. Kind of a fun example with lots of implications if people are interested in running with this. Also I'm kind of loving the Marker change for little things like this. :)

### Progress of the PR
- [x] Change implemented (can be split into several points),
- [ ] update docstring (if appropriate),
- [x] update user guide (if appropriate),
- [x] add an changelog entry in the `upcoming_changes` folder (see [`upcoming_changes/README.rst`](https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/upcoming_changes/README.rst)),
- [ ] Check formatting changelog entry in the `readthedocs` doc build of this PR (link in github checks)
- [ ] add tests,
- [ ] ready for review.

### Minimal example of the bug fix or the new feature
See documentation

### CODE REVIEW

**Comment by CSSFrancis** [comment]
@magnunor You might find this fun/interesting :) 

@ericpre We might want to think about adding a special class for `hyperspy` to make things like this easier in future.  I could see something like an InsetMarker which just takes a square mesh and inlays some signal.  

I also realize this __is__ a weird way to do this in Matplotlib but still kind of fun.

**Comment by CSSFrancis** [comment]
https://github.com/pyxem/pyxem/issues/1031

**Comment by magnunor** [comment]
This is really cool! I tried them, and they indeed work!

Having these as examples is nice, and I think they potentially could be useful for other visualization features. For example, one thing I've been thinking about for a while, is having a `Signal2D` equivalent version of the `Signal1D` "spectrum" . If you have a `Signal1D`, pressing the `e` key on your keyboard gives you a second navigator and the spectrum from this position is plotted in the same window as your main navigator.

Maybe using the transparent overlay would be a way to do this.

**Comment by ericpre** [comment]
There is a variant of the colour wheel where the colour intensity increase from the center to the edge, for example:
https://www.nature.com/articles/s41565-022-01224-y/figures/1

I am wondering if this would be more simple using a polar transform in matplotlib?

**Comment by magnunor** [comment]
I also tested both saving and loading these markers with `.hspy`, which worked nicely!

**Comment by magnunor** [comment]
> There is a variant of the colour wheel where the colour intensity increase from the center to the edge, for example: https://www.nature.com/articles/s41565-022-01224-y/figures/1
> 
> I am wondering if this would be more simple using a polar transform in matplotlib?

A similar colorwheel style is implemented in pyxem: https://github.com/pyxem/pyxem/blob/main/pyxem/utils/pixelated_stem_tools.py#L214

**Comment by CSSFrancis** [comment]
> I also tested both saving and loading these markers with `.hspy`, which worked nicely!

Cool I was wondering if that was going to work :) I thought it should but always good to check.

**Comment by CSSFrancis** [comment]
> There is a variant of the colour wheel where the colour intensity increase from the center to the edge, for example: https://www.nature.com/articles/s41565-022-01224-y/figures/1
> 
> I am wondering if this would be more simple using a polar transform in matplotlib?

@ericpre Probably would be a bit easier but stacking transforms in `matplotlib` always is a bit difficult to understand what's happening.  I find myself wondering "where did my collection go?" a bit too much so I just stuck with cartesian coordinates and made a 360-gon.

**Comment by ericpre** [comment]
Sorry, I use the wrong terminology: it is polar projection that I meant: https://matplotlib.org/stable/gallery/pie_and_polar_charts/polar_demo.html

The one in pyxem looks good: https://pyxem.readthedocs.io/en/stable/tutorials/pyxem-demos/10%20STEM%20DPC%20Analysis%20of%20Magnetic%20Sample.html

**Comment by CSSFrancis** [comment]
@ericpre I wonder if you could make this interactive using hs.interactive?

For example could you link the data from some inset quad mesh to an ROI?  That might be useful if you wanted to integrate part of a navigator and plot the integrated signal as something like a call out. 

I guess this is just a different way of handling something like #3325 but that might be a good first step to see how we could make #3325 a bit more flexible.

**Review by ericpre — APPROVED** [review]

**Comment by ericpre** [comment]
> @ericpre I wonder if you could make this interactive using hs.interactive?

A "changed" events will need to be added to the markers class so that it can be used to redraw the markers when the data changed?

**Pull request merged**
