### PR TITLE
Combine pytest.ini and .coveragerc into setup.cfg

### PR DESCRIPTION
**Pull request by tjof2**
### Description of the change
Consolidates some of the files in the root directory:
- Move `pytest.ini` to `[tool:pytest]` stanza of `setup.cfg`
- Added `-addopts = -ra` to `pytest` such that it prints a summary of all tests that didn't pass (i.e. including skipped and xfailed/xpassed) at the end of the report - I found this helpful when debugging #2358. Here's an example:
```bash
=========================== short test summary info ============================
...
SKIPPED [1] /home/vsts/work/1/s/hyperspy/tests/signal/test_tools.py:1058: LazyS optimization is tested in test_lazy_tranpose_rechunk
XFAIL hyperspy/tests/io/test_hdf5.py::TestLoadingNewSavedMetadata::test_binary_string
  dill is not guaranteed to load across Python versions
XFAIL hyperspy/tests/samfire/test_samfire.py::test_multiprocessed
  Sometimes the number of failed pixels > 3 when using multiprocessing. Unknown reason
==== 2548 passed, 14 skipped, 4 xfailed, 136 warnings in 507.61s (0:08:27) =====
```

- Move `.coveragerc` to `[coverage]` stanza of `setup.cfg`
- Add some [`flake8`](https://pypi.org/project/flake8/) linting options to `setup.cfg` for running `flake8 hyperspy/`

The last one can be removed or ignored if preferred @francisco-dlp , but since we have an open issue for using the `black` code formatter #2316, I thought it might be relevant.

### Progress of the PR
- [x] Change implemented (can be split into several points),
- [x] ready for review.

### CODE REVIEW

**Review by ericpre — COMMENTED** [review]
This looks good to me. Two comments:
- Is it worth documenting it in the dev guide?
- slightly related to this PR, I have noticed that since pytest 5.4, we can't run `pytest --pyargs hyperspy` outside of hyperspy source directory any more without getting an error about the parrallel markers not being registered. Not sure if this is a pytest recent bug or pytest changed the way marker are supposed to be registered...

**Comment by tjof2** [comment]
1) Yes I can document!
2) How often is parallel marker used?

**Comment by ericpre** [comment]
Sorry, I never looked at what the the "parallel" marker is doing and I don't know...
Regarding the documentation, the idea is to avoid spending working out how things are setup and what configuration file is doing what when we have to deal this!

**Comment by tjof2** [comment]
I think I know the error, I'll take a look this morning

**Comment by tjof2** [comment]
> I have noticed that since pytest 5.4, we can't run pytest --pyargs hyperspy outside of hyperspy source directory any more without getting an error about the parrallel markers not being registered. Not sure if this is a pytest recent bug or pytest changed the way marker are supposed to be`registered...

@ericpre I could not reproduce this. Do you have an example warning message? It's probably related to https://docs.pytest.org/en/latest/mark.html#unknown-marks perhaps?

I updated the docs to discuss the configuration of `pytest` and `coverage` as well as `flake8`. This is now ready for review.

**Comment by ericpre** [comment]
On your last commit https://github.com/hyperspy/hyperspy/pull/2381/commits/9300dc8cedd493943df1830f54652b9ffbddeb90, I still have this error:

With pytest 5.4.1 and running `pytest --pyargs hyperspy` in my home directory, I get the following:

```
============================================================================================================================== test session starts ===============================================================================================================================
platform linux -- Python 3.7.7, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
Matplotlib: 3.1.3
Freetype: 2.9.1
PyQt5 5.9.2 -- Qt runtime 5.9.7 -- Qt compiled 5.9.6
rootdir: /home/eric
plugins: forked-1.1.3, mpl-0.11, xdist-1.31.0, memprof-0.2.0, timeout-1.3.3, qt-3.3.0
collecting ... WARNING:hyperspy_gui_traitsui:The traitsui GUI elements are not available.
collected 2559 items / 4 errors / 2555 selected                                                                                                                                                                                                                                  

===================================================================================================================================== ERRORS =====================================================================================================================================
________________________________________________________________________________________________________ ERROR collecting Dev/hyperspy/hyperspy/tests/model/test_model.py ________________________________________________________________________________________________________
Dev/hyperspy/hyperspy/tests/model/test_model.py:1111: in <module>
    class TestAsSignal:
Dev/hyperspy/hyperspy/tests/model/test_model.py:1124: in TestAsSignal
    @pytest.mark.parallel
/opt/miniconda3/lib/python3.7/site-packages/_pytest/mark/structures.py:351: in __getattr__
    2,
E   pytest.PytestUnknownMarkWarning: Unknown pytest.mark.parallel - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
______________________________________________________________________________________________________ ERROR collecting Dev/hyperspy/hyperspy/tests/samfire/test_samfire.py ______________________________________________________________________________________________________
Dev/hyperspy/hyperspy/tests/samfire/test_samfire.py:143: in <module>
    class TestSamfireEmpty:
Dev/hyperspy/hyperspy/tests/samfire/test_samfire.py:155: in TestSamfireEmpty
    @pytest.mark.parallel
/opt/miniconda3/lib/python3.7/site-packages/_pytest/mark/structures.py:351: in __getattr__
    2,
E   pytest.PytestUnknownMarkWarning: Unknown pytest.mark.parallel - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
______________________________________________________________________________________________________ ERROR collecting Dev/hyperspy/hyperspy/tests/signal/test_1D_tools.py ______________________________________________________________________________________________________
Dev/hyperspy/hyperspy/tests/signal/test_1D_tools.py:291: in <module>
    @lazifyTestClass(rtol=1e-4, atol=0.4)
Dev/hyperspy/hyperspy/tests/signal/test_1D_tools.py:308: in TestSmoothing
    [pytest.param(True, marks=pytest.mark.parallel), False])
/opt/miniconda3/lib/python3.7/site-packages/_pytest/mark/structures.py:351: in __getattr__
    2,
E   pytest.PytestUnknownMarkWarning: Unknown pytest.mark.parallel - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
_____________________________________________________________________________________________________ ERROR collecting Dev/hyperspy/hyperspy/tests/signal/test_map_method.py _____________________________________________________________________________________________________
Dev/hyperspy/hyperspy/tests/signal/test_map_method.py:11: in <module>
    @lazifyTestClass(ragged=False)
Dev/hyperspy/hyperspy/tests/signal/test_map_method.py:19: in TestImage
    [pytest.param(True, marks=pytest.mark.parallel), False])
/opt/miniconda3/lib/python3.7/site-packages/_pytest/mark/structures.py:351: in __getattr__
    2,
E   pytest.PytestUnknownMarkWarning: Unknown pytest.mark.parallel - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
================================================================================================================================ warnings summary ================================================================================================================================
Dev/pyUSID/pyUSID/io/reg_ref.py:10
  /home/eric/Dev/pyUSID/pyUSID/io/reg_ref.py:10: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    from collections import Iterable

/opt/miniconda3/lib/python3.7/site-packages/urllib3/connectionpool.py:1004
  /opt/miniconda3/lib/python3.7/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.eelsdb.eu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
    InsecureRequestWarning,

/opt/miniconda3/lib/python3.7/socket.py:660
  /opt/miniconda3/lib/python3.7/socket.py:660: ResourceWarning: unclosed <socket.socket fd=13, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.0.27', 47898), raddr=('91.238.163.174', 443)>
    self._sock = None

/opt/miniconda3/lib/python3.7/site-packages/urllib3/connectionpool.py:1004
  /opt/miniconda3/lib/python3.7/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made to host 'eelsdb.eu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
    InsecureRequestWarning,

/opt/miniconda3/lib/python3.7/socket.py:660
  /opt/miniconda3/lib/python3.7/socket.py:660: ResourceWarning: unclosed <socket.socket fd=13, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.0.27', 47900), raddr=('91.238.163.174', 443)>
    self._sock = None

/opt/miniconda3/lib/python3.7/socket.py:660
  /opt/miniconda3/lib/python3.7/socket.py:660: ResourceWarning: unclosed <socket.socket fd=13, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.0.27', 47904), raddr=('91.238.163.174', 443)>
    self._sock = None

/opt/miniconda3/lib/python3.7/socket.py:660
  /opt/miniconda3/lib/python3.7/socket.py:660: ResourceWarning: unclosed <socket.socket fd=13, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.0.27', 47906), raddr=('91.238.163.174', 443)>
    self._sock = None

-- Docs: https://docs.pytest.org/en/latest/warnings.html
============================================================================================================================ short test summary info =============================================================================================================================
ERROR Dev/hyperspy/hyperspy/tests/model/test_model.py - pytest.PytestUnknownMarkWarning: Unknown pytest.mark.parallel - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
ERROR Dev/hyperspy/hyperspy/tests/samfire/test_samfire.py - pytest.PytestUnknownMarkWarning: Unknown pytest.mark.parallel - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
ERROR Dev/hyperspy/hyperspy/tests/signal/test_1D_tools.py - pytest.PytestUnknownMarkWarning: Unknown pytest.mark.parallel - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
ERROR Dev/hyperspy/hyperspy/tests/signal/test_map_method.py - pytest.PytestUnknownMarkWarning: Unknown pytest.mark.parallel - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 4 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================================================================================= 7 warnings, 4 errors in 41.65s =========================================================================================================================
```

[output_pytest_parallel_marker.txt](https://github.com/hyperspy/hyperspy/files/4539145/output_pytest_parallel_marker.txt)

**Comment by tjof2** [comment]
@ericpre  can you try again with the latest commit? I think this solves it.

**Comment by ericpre** [comment]
Yes, it does fix it!
It is surprising that you can't reproduce it... the thing which make it failed is to run the pytest from outside the hyperspy source directory.

**Comment by tjof2** [comment]
@ericpre   was able to reproduce it eventually - running it from my home directory didn't work since `hyperspy` is a valid directory in my home folder. 

I think this PR is now complete?

**Comment by ericpre** [comment]
Yes, this is nice, I like the flake8 docstring plugins and after the next release (when the `RnM` is merged is the `RnP` branch), we should fix all the formatting issues and make a test on travis which fail if there are warnings...

**Comment by tjof2** [comment]
Black takes a --check argument I think which is a super-simple way to verify it (not docstrings though)

**Pull request merged**
