### PR TITLE
clarifications on integrate/sum for binned/non-uniform axes  

### LINKED ISSUE #2735: integrate1D of binned signals
For binned signals, `integrate1D` currently uses `sum` to perform the integration. In principle, this is a simplified version of the rectangle rule (Riemann sum: https://en.wikipedia.org/wiki/Riemann_sum), where the signal intensity is assumed to be constant over the complete interval associated with an axis point.

However, for uniform axes, this simplification means that `scale == 1` is assumed. Otherwise the result of `sum` is not really the `integral`, but in fact `integral/scale`.

For non-uniform axes, using the `sum` function does not really make sense mathematically. To calculate an integral using the rectangle rule, the data would first need to be multiplied with `np.gradient(axis)`, before the sum is performed.

I would propose to implement a new function `integrate_rectangle` or `integrate_riemann` that basically calculates:
- for uniform axes: `sum(data)*scale`
- for non-uniform axes: `sum(data*np.gradient(axis))`

This function would be called by `integrate1D` when integrating over a binned axis.

### PR DESCRIPTION
**Pull request by jlaehne**
### Description of the change
Based on the discussion in #2735, I did some small clarifications to the docstrings and warnings concerning the inegration/summation of binned axes in view of the non-uniform axes implementation.

### Progress of the PR
- [X] Change implemented,
- [X] update docstring,
- [X] update user guide,
- [X] add tests,
- [X] ready for review.

### CODE REVIEW

**Review by ericpre — COMMENTED** [review]
Could you also mentioned this in the user guide: https://hyperspy.readthedocs.io/en/stable/user_guide/signal.html#binned-and-unbinned-signals?

**Comment by jlaehne** [comment]
Yes, we should definitely update the binned signal section of the user guide.

**Comment by ericpre** [comment]
The user guide link above is the doc of the release version. I should have shared the one of this branch (https://hyperspy--2737.org.readthedocs.build/en/2737/user_guide/signal.html#binned-and-unbinned-signals) or the one for `RELEASE_next_minor`: https://hyperspy.readthedocs.io/en/latest/user_guide/signal.html#binned-and-unbinned-signals, which is very similar.

Maybe without going too much in details of the meaning of `binned` axis, maybe it is worth given the example of the `integrate1D` method, what is different and it's reasoning? Rewording the content of the docstring or what @francisco-dlp explained in https://github.com/hyperspy/hyperspy/issues/2735#issuecomment-836743647 should be good.

**Comment by jlaehne** [comment]
OK, I updated the user guide to include EDS as an example of a binned signal and I added a small paragraph on the integration of binned signals. I would consider this PR as finished (closing #2735), but would keep the item in the todo list of #2398 open in case @francisco-dlp or someone else has another idea of how to further improve the documentation of binned signals.

**Review by ericpre — APPROVED** [review]
Thanks!

**Pull request merged**
