### PR TITLE
fix: lxml dependancy

### PR DESCRIPTION
**Pull request by sem-geologist**
add lazy loading to hyperspy/io_plugins/__init__

### CODE REVIEW

**Comment by francisco-dlp** [comment]
Almost perfect. The tests fail if lxml is not installed, they should be skipped instead.

**Comment by sem-geologist** [comment]
I dont get it why when test things?

**Comment by francisco-dlp** [comment]
The bcf unittests still assume that you can import it. If you can't they fail. If lxml is not present, the bcf tests should be skipped.

**Comment by sem-geologist** [comment]
is there any other format which would do that?

**Comment by sem-geologist** [comment]
@francisco-dlp  I hope the changes will satisfy you

**Comment by francisco-dlp** [comment]
Great, thanks!

**Pull request merged**
