### PR TITLE
set default encoding to utf8

### PR DESCRIPTION
**Pull request by to266**
as per http://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte general suggestion.

### CODE REVIEW

**Comment by to266** [comment]
I just noticed a bug, so not ready yet...

**Comment by to266** [comment]
Should be OK now (sorry for multiple not spurious commits)

**Comment by francisco-dlp** [comment]
Could you describe the bug that this PR attempts to fix?

**Comment by to266** [comment]
metadata of [this](https://mega.co.nz/#!h09U2Q7A!d1Twm1u6A48HzCfl6N8BFHAvIsxxkfJ-XkQnkr3S2z4) file is not displayed, the PR fixes the issue

**Comment by francisco-dlp** [comment]
Could you send the original file?

**Comment by to266** [comment]
sure, [here](http://cook.msm.cam.ac.uk/~to266/NW2_Spim4_UV1_70um_grat300-1_centre380nm_slit500um_10ms_300x80_Bin4_CCD_XRAY.dm3) is one example

**Comment by francisco-dlp** [comment]
But this one doesn't present the problem...

**Comment by to266** [comment]
Huh, good point. If you estimate poissonian noise variance and then try to print the metadata, though, then the problem is there:

```python

In [1]: s = load('NW2_Spim4_UV1_70um_grat300-1_centre380nm_slit500um_10ms_300x80_Bin4_CCD_XRAY.dm3')

In [2]: s.metadata
Out[2]: 
├── General
│   ├── original_filename = NW2_Spim4_UV1_70um_grat300-1_centre380nm_slit500um_10ms_300x80_Bin4_CCD_XRAY.dm3
│   └── title = NW2_Spim4_UV1_70µm_grat300-1_centre380nm_slit500µm_10ms_300x80_Bin4_CCD_XRAY
└── Signal
    ├── binned = True
    ├── record_by = spectrum
    ├── signal_origin = 
    └── signal_type = EELS

In [3]: s.estimate_poissonian_noise_variance()

In [4]: s.metadata
Out[4]: <repr(<hyperspy.misc.utils.DictionaryTreeBrowser at 0x1b30a2b0>) failed: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 50: ordinal not in range(128)>

```

**Pull request merged**
