### PR TITLE
Uppercase acronyms

### PR DESCRIPTION
**Pull request by francisco-dlp**
Use uppercase for ``algorithm`` when the name of the algorithm is an acronym *and* (the algorithm is not likely to be removed in the near future *or* the algorithm name changed to lowercase in #2383).

### Progress of the PR
- [x] Change implemented (can be split into several points),
- [x] update docstring (if appropriate),
- [x] update user guide (if appropriate),
- [x] add tests,
- [x] ready for review.

### CODE REVIEW

**Review by tjof2 — APPROVED** [review]

**Comment by tjof2** [comment]
Why not do `algorithm = algorithm.upper()` before subsequent comparison?

**Comment by francisco-dlp** [comment]
I don't get what you mean, would you like to accept both lower and upper?

**Comment by tjof2** [comment]
> I don't get what you mean, would you like to accept both lower and upper?

Is it a _breaking_ API change? i.e. could someone have old code that uses the lowercase names? Accepting lower and upper would mean their code still works?

Otherwise, ignore me!

**Comment by francisco-dlp** [comment]
I think that it must be a breaking one, otherwise we'll get into bad habits ;)

**Comment by tjof2** [comment]
> I think that it must be a breaking one, otherwise we'll get into bad habits ;)

Sure! Maybe https://github.com/hyperspy/hyperspy/blob/6ef773e19eaf6c19024f8dd580367927f7565a59/hyperspy/learn/mva.py#L537-L538 could return a list of valid string arguments in that case? Perhaps it could return the parameter list from the docstring:

```
raise ValueError(f"'algorithm={algorithm}' not recognised. Expected one of [list of string arguments, custom object]")
```

**Review by tjof2 — APPROVED** [review]

**Comment by tjof2** [comment]
LGTM assuming tests pass.

**Comment by francisco-dlp** [comment]
One more commit is on the way.

**Pull request merged**
