### PR TITLE
Corrected some typos in the development guide

### PR DESCRIPTION
**Pull request by jlaehne**
Typos and improved readability in development guide

### Progress of the PR
- [x] Change implemented (can be split into several points),
- [x] update user guide (if appropriate)

### CODE REVIEW

**Comment by magnunor** [comment]
Why was this pull request closed?

**Comment by jlaehne** [comment]
> Why was this pull request closed?

I must have deleted the associated branch by mistake.

**Comment by magnunor** [comment]
Looks good to me!

**Comment by magnunor** [comment]
The failing tests are unrelated to this pull request.

**Pull request merged**
