### PR TITLE
Improve pytest setuptools integration

### PR DESCRIPTION
**Pull request by ericpre**
Makes setup.py more consistent (see #2020) following [pytest good practices recommandation].(https://docs.pytest.org/en/latest/goodpractices.html#integrating-with-setuptools-python-setup-py-test-pytest-runner)

- [x] add support for `python setup.py test` to run the test suite -see [setuptools documentation](https://setuptools.readthedocs.io/en/latest/setuptools.html#test-build-package-and-run-a-unittest-suite),
- [x] ready for review.

### CODE REVIEW

**Comment by francisco-dlp** [comment]
Would it be good to:

* Modify the Dev Guide to document this way of running the test
* Add the --mpl option?

**Comment by ericpre** [comment]
Adding `--mpl` should be possible but this feature will be deprecated soon, see https://github.com/pytest-dev/pytest/issues/3523... but there may be alternative in the future. I put this on hold for now.

**Comment by dnjohnstone** [comment]
Is this still relevant?

**Comment by tjof2** [comment]
Agree with @dnjohnstone  - @ericpre  is this, and the related issue #2020, still relevant? Or can the issue and PR both be closed.

**Comment by tjof2** [comment]
Sorry @ericpre that was meant to be sent as a pull request, not a push...!

**Comment by ericpre** [comment]
In order to improve and simplify all these (testing, packaging, etc.), I suspect that it may be good looking at using `pyproject.toml`:
- https://snarky.ca/what-the-heck-is-pyproject-toml
- https://docs.pytest.org/en/latest/customize.html#pyproject-toml
- https://black.readthedocs.io/en/stable/pyproject_toml.html

**Comment by jlaehne** [comment]
Any update on this one? Should it be included in 1.6.2?

**Comment by ericpre** [comment]
I have left this one on hold, because I think that the build tool/configuration are still fluid at the moment... Closing it for now.

**Pull request closed without merging**
