### PR TITLE
Fix exec permission

### PR DESCRIPTION
**Pull request by francisco-dlp**
### Description of the change

Remove exec permissions from multiple files for fixing #1816.

### Progress of the PR
- [x] Change implemented (can be split into several points),
- [x] ready for review.

### CODE REVIEW

**Comment by thomasaarholt** [comment]
Lots of files changed - I assume this is because their file permissions have been changed?

**Comment by francisco-dlp** [comment]
Yes, that's right.

**Comment by ericpre** [comment]
This looks good to me, @Dhanesh95, are you happy with this?

**Comment by dhaneshsabane** [comment]
@ericpre 

Seems legit. Thanks @francisco-dlp for working on this!

**Pull request merged**
