### PR TITLE
orpca now consistent with old implementation

### PR DESCRIPTION
**Pull request by to266**
a quick fix for https://github.com/hyperspy/hyperspy/issues/1557

No tests for now.. But the class / function should probably be made consistent in some other PR anyway (currently class takes the transpose of the function. The function is left purely to keep the API, no other reason actually..), so I'll leave the tests for that.

### CODE REVIEW

**Comment by thomasaarholt** [comment]
Thanks @to266, that was quick! :D

**Comment by thomasaarholt** [comment]
@to266 ORPCA is still not working for me. I think you have fixed one bug but exposed another? If I do 
```python
s.decomposition(True, "ORPCA", 20)
s.get_decomposition_model(5)
s.plot()
```
then every pixel has the same factor, but in varying intensity.

**Comment by thomasaarholt** [comment]
One more thing - As the decomposition progresses, I see the ram being used increasing steadily, from about 3.5 GB (which is just the signal loaded into memory) to 6 GB. At the end it drops down to 3.9 GB. I haven't watched this before, but is that supposed to be happening?

**Comment by to266** [comment]
Yes, it's supposed to happen.

The ORPCA does not work for you because you probably did not read the documentation:
```python
s = hs.signals.Signal1D(np.random.rand(100,99,98)).as_lazy()
s.decomposition(7, algorithm='ORPCA', normalize_poissonian_noise=True)
```

**Comment by thomasaarholt** [comment]
I was comparing non-lazy signals when doing the above. Sorry about the confusion with the other issue. The ram-usage was what made me investigate the decomposition of lazy signals. (At work I've been downgraded to a PC with 8 GB of ram, which is the upper limit for working with several GB spectrum images).

I've double and triple checked now, and the following code produces a spectrum image `sc` with only one component, on my computer:

```python
%matplotlib qt4

import hyperspy.api as hs
import os

path = r"C:\Users\thomasaar\Documents"
name = "EELS Spectrum Image 0eV"
ext = ".dm3"

path = os.path.join(path, "")

s = hs.load(path + name + ext)
s.align_zero_loss_peak(True)
s.decomposition(normalize_poissonian_noise=True, algorithm="ORPCA", output_dimension=7)

sc = s.get_decomposition_model()
sc.plot()
```

**Comment by to266** [comment]
I think this is just a peculiarity of ORPCA. 
In the quick example (both lazy and normal) that I had before it seems that identical bug is present from the first sight too, but actually the procedure to reconstruct the model for any of the non-bss decompositions is exactly the same. Thus if you get "reasonable" factors and loadings from `get_decomposition_factors` and its friends, the model will be equally reasonable.

The issue is that with `normalize_poissonian_noise=True` ORPCA only picks up one significant component, and even reconstructing the full data model with all components looks almost identical to just the first one. The simplest way to verify this is by looking at the loading coefficients. In my case the first one has max value of 1.9e-4, next is 1e-9, followed by 1e-20, etc. I guess to both normalize and get reasonable components you'll have to tweak the ORPCA parameters.

**Comment by thomasaarholt** [comment]
Okay, that's good to be clear on. I'm a bit surprised to be honest, as I can't remember this being the case when I was using ORPCA to noise reduce some EELS Line SIs, but I am very likely mistaken.

I too see the same decreasing loading coefficients. In any case, don't bother with this now, I am happy using the other algorithms for now :) You write your thesis ;)

**Comment by thomasaarholt** [comment]
(For later)
Something has certainly changed. I just installed hyperspy 1.0.1, and there ORPCA works in the manner I would expect. Running exactly the same notebook, I get a far better decomposition model back with the older version. This is probably due to a change of defaults "under the hood", but it would be good to highlight them and, unless you have a good reason, maybe change them back?

The warnings on default settings are the same, but in different order (except for what I assume is renaming of nsamples and nfeatures.

```python
WARNING:hyperspy.learn.rpca:No method specified. Defaulting to 'CF' (closed-form solver)
WARNING:hyperspy.learn.rpca:Nuclear norm regularization parameter is set to default: 1 / sqrt(nsamples)
WARNING:hyperspy.learn.rpca:Sparse regularization parameter is set to default: 1 / sqrt(nsamples)
WARNING:hyperspy.learn.rpca:No initialization specified. Defaulting to 'qr' initialization
WARNING:hyperspy.learn.rpca:Number of training samples for 'qr' method not specified. Defaulting to 10 samples
```

and the new:

```python
WARNING:hyperspy.learn.rpca:No method specified. Defaulting to 'CF' (closed-form solver)
WARNING:hyperspy.learn.rpca:No initialization specified. Defaulting to 'qr' initialization
WARNING:hyperspy.learn.rpca:Number of training samples for 'qr' method not specified. Defaulting to 10 samples
WARNING:hyperspy.learn.rpca:Nuclear norm regularization parameter is set to default: 1 / sqrt(nfeatures)
WARNING:hyperspy.learn.rpca:Sparse regularization parameter is set to default: 1 / sqrt(nfeatures)
```

**Comment by tjof2** [comment]
@thomasaarholt  Notice the difference between:

Old: `Sparse regularization parameter is set to default: 1 / sqrt(nsamples)`
**and** 
New: `Sparse regularization parameter is set to default: 1 / sqrt(nfeatures)`

The default parameter of `1/sqrt(...)` should use the number of features, not the number of samples (since this is in theory unknown when doing an online decomposition of course!), but at some point (probably related to the transposed signal bug...) I got them the wrong way round.

@to266 is right of course, parameter choice is crucial for ORPCA, you can't just set a number of components and expect a good result like PCA, due to the nature of the problem being solved. If the matrix is scaled between 0 and 1, then it just so happens `1/sqrt(nfeatures)` is a very good default choice. 

The normalization for Poisson noise will change the range of values so it's no longer [0,1], and this will affect the parameter choice. It would be nice to know in advance how much the normalization has scaled the matrix by, so you could scale the regularization parameters under the hood and avoid this issue, but it's not clear how you normalize for Poisson noise in an online manner.

Lastly, please try the SGD method (or Momentum version) with the values suggested in the docs, and let me know how well they work in comparison. The CF solver is actually a bit terrible in practice due to the matrix inverse involved, but it provides a nice exact answer for theoretical analysis of the type one might write in a thesis...

**Comment by francisco-dlp** [comment]
@to266  and @thomasaarholt, is this ready?

**Comment by thomasaarholt** [comment]
Afaik, this works as it should.

**Comment by to266** [comment]
I believe so

**Comment by thomasaarholt** [comment]
Merge ahead.

**Pull request merged**
