### PR TITLE
Enh signal nearest nearest points

### PR DESCRIPTION
**Pull request by to266**
TODO
--------

- [ ] Add documentation to `Signal` docstring
- [ ] Add documentation to User Guide

### CODE REVIEW

**Comment by francisco-dlp** [comment]
Nice. This needs to be documented in the `Signal` docstring and the User Guide.

**Comment by francisco-dlp** [comment]
What's the status of this?

**Comment by to266** [comment]
It's used internally by SAMFire (not with the API of this PR though). If there is someone interested in this, I could try updating, but at present I would just close this

**Comment by dnjohnstone** [comment]
I think this can be closed now?

**Pull request closed without merging**
