### PR TITLE
Add parameter to normalise spectra in `hs.plot.plot_spectra`

### PR DESCRIPTION
**Pull request by ericpre**
### Progress of the PR
- [x] Add parameter to normalise spectra in `hs.plot.plot_spectra`,
- [x] update docstring (if appropriate),
- [n/a] update user guide (if appropriate),
- [x] add an changelog entry in the `upcoming_changes` folder (see [`upcoming_changes/README.rst`](https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/upcoming_changes/README.rst)),
- [x] Check formatting changelog entry in the `readthedocs` doc build of this PR (link in github checks)
- [x] add tests,
- [x] ready for review.

### Minimal example of the bug fix or the new feature
```python
import hyperspy.api as hs
import numpy as np

s = hs.signals.Signal1D(np.arange(100)) + 100
s2 = s * 1000

ax = hs.plot.plot_spectra([s, s2], style="cascade", normalise=True)
```

### CODE REVIEW

**Review by jlaehne — APPROVED** [review]

**Comment by jlaehne** [comment]
Very useful addition. It would also be nice (though not necessarily in this PR) to be able to:
1.  normalize at a different `x` positions than the maximum (e.g. thinking of EDX spectra where you might want to normalize on a certain element and not necessarily the one giving the highest signal).
2. normalize to the average signal in a ROI (e.g. for noisy signal where normalisation might otherwise be to a noise spike).

**Comment by ericpre** [comment]
Yes, this is a good idea to allow setting a window for the normalisation.
Regarding the syntax, maybe we can use the same syntax as `isig`?

**Comment by jlaehne** [comment]
Well, I guess a `signal_range` as in the [`remove_background`](http://hyperspy.org/hyperspy-doc/current/reference/api.signals/Signal1D.html#hyperspy.api.signals.Signal1D.remove_background) function would make sense?

**Comment by ericpre** [comment]
I wIll leave using a signal range for the normalisation for another PR.

**Pull request merged**
