### PR TITLE
Remove advice about the bundle

### PR DESCRIPTION
**Pull request by mwalls**
Since this is no longer the way to get the latest version (if I've understood) I don't think telling people to use the bundle is a good idea.
Incidentally on the "News" page, the links to the bug fixes and enhancements seem to be wrong. They imply that none of either have occurred in this release. I wanted to change that but could not find the file about release 1.3.1.
Maybe I'm jumping the gun and this is all in hand, My apologies if so...

### Requirements
* Read the [developer guide](http://hyperspy.org/hyperspy-doc/current/dev_guide.html).
* Filling out the template; it helps the review process and it is useful to summarise the PR.
* This template can be updated during the progression of the PR to summarise its status. 

*You can delete this section after you read it.*

### Description of the change
A few sentences and/or a bulleted list to describe and motivate the change:
- Change A.
- Change B.
- etc.

### Progress of the PR
- [ ] Change implemented (can be split into several points),
- [ ] update docstring (if appropriate),
- [ ] update user guide (if appropriate),
- [ ] add tests,
- [ ] ready for review.

### Minimal example of the bug fix or the new feature
```python
>>> import hyperspy.api as hs
>>> import numpy as np
>>> s = hs.signals.Signal1D(np.arange(10))
>>> # Your new feature...
```
Note that this example can be useful to update the user guide.

### CODE REVIEW

**Comment by ericpre** [comment]
They will a bundle released very soon, it needs one last tweak... and yes indeed the link in the website is broken! :/ Thanks for spotting the mistake.

**Comment by mwalls** [comment]
Ok, but then I'm not sure I understand the statement: "Starting with this version, the HyperSpy WinPython Bundle distribution is no longer released in sync with HyperSpy." I may have missed a discussion about this. Will the bundle still always exist, but just a bit later? Is there some reason why the bundled version will now systematically be released after the unbundled? If so, the text on the "install.rst" page  should have at least a remark to that effect?

**Comment by ericpre** [comment]
This is related to the hyperspy split and the hyperspy-extensions. The idea would be to release a bundle when it is needed: changes in the python scientific stack, hyperspy, hyperspyUI, or any other hyperspy-extension may required to release a bundle without requiring a hyperspy release.

**Comment by mwalls** [comment]
OK I'm way out of date. But I think the text could be clearer for new and/or non-expert users. Just not sure I'm the person to write it. Maybe I'll have a talk to Francisco...

**Comment by ericpre** [comment]
The bundle have been released, see:
https://github.com/hyperspy/hyperspy-bundle/releases

**Comment by ericpre** [comment]
Closing since this have been clarified. Reopen if this is still not clear.

**Pull request closed without merging**
