### PR TITLE
Add support for non linear axes

### PR DESCRIPTION
**Pull request by francisco-dlp**
This adds support for non-linear axes. Although it is still work in progress, I think that the main functionality is already here, including slicing support. Please let me know what you think.

Usage
--------

```python

s = signals.Spectrum(np.random.random((64, 1000)))
s.axes_manager[0].__init__(axis=np.arange(64)**10, navigate=True)
s.plot(navigator="spectrum")

````

index
index

TO DO
---------

- [ ] unittests
- [ ] Fix image plotting that relies on DataAxis.scale
- [ ] Search the code and fix all functions that rely on DataAxis.{scale, offset}
- [ ] Increase the hdf5 version number when saving non-linear axes. HyperSpy < 0.8 won't be able to read these files.
- [ ] User Guide documentation
- [ ] Improve syntax
- [ ] Fix performance bug (probably a trigger infinite loop)
- [ ] Raise exception when axes is unsorted

### CODE REVIEW

**Comment by pburdet** [comment]
Nice function. I tried it, it works well. I plan to use it for signal such as X-ray lines intensity return by function such as `.get_lines_intensity`. The energy axis is given by the position of each peak of intensity.

```python

intensities = s.get_lines_intensity()
ax = [s._get_line_energy(xr) for xr in s.metadata.Sample.xray_lines]
intensities.axes_manager[0].__init__(axis=ax, navigate=True)

````

Few points:

- Maybe a more user friendly name would be nice, `define_axis_value`
- Unsorted axis are confusing
- The display is a bit confusing, see following images

figure_stack_of_intensities_ag_la_navigator

Something like that would be clearer

figure_13

I notice some bugs:

- `.__init__(axis=` does not accept `list`
- Applying `.__init__` erase the axis name and units
- I cannot plot the signal if navigator is an image

**Comment by pburdet** [comment]
By the way, there was a discussion on the subject in issue #110

**Comment by francisco-dlp** [comment]
Thank you for the feedback. I have edited the TO DO list to include your concerns. 

Indeed, calling the `DataAxis` constructor is not the proper way to amend an instance. We should  have a method for that.

**Comment by francisco-dlp** [comment]
This branch was automatically closed when we renamed `master` `RELEASE_next_major` and it cannot be reopened. Could you resubmitted it to RELEASE_next_minor instead?

**Comment by ericpre** [comment]
Resubmitted in #1927.

**Pull request closed without merging**
