### PR TITLE
Add update instructions

### LINKED ISSUE #2618: Add update instructions
Some suggestion from @NathalieBrun in https://gitter.im/hyperspy/hyperspy?at=5ff87239252c0a6dedf9de1d to improve the installation instruction in the user guide:
- add section about updating hyperspy
- specify version

Since a couple of month, `conda-forge` is fully independent of anaconda `defaults` channel, and using `conda-forge` only channel will simplify a *lot* updating pacakges on all platforms because these two channels are not fully compatible, there may some corner case with issues and in some situation conda may struggle to resolve the dependencies incompatibilities...

Recommending users to install the hyperspy-bundle or [miniforge](https://github.com/conda-forge/miniforge) over miniconda/anaconda will avoid having the anaconda `defaults` channel and the issues related to it.
The only remaining advantage of using the anaconda distribution is the [`anaconda-navigator`](https://docs.anaconda.com/anaconda/navigator/). Since it is not open-source, it can't de distributed through conda-forge and this means that since it is built against qt, it doesn't always play well with packages of the `conda-forge` and can cause trouble with solving environment. There alternative such as [nb_conda](https://github.com/Anaconda-Platform/nb_conda) or [gator](https://github.com/mamba-org/gator), which will be a good alternative once it has mature enough!

### PR DESCRIPTION
**Pull request by ericpre**
Closes #2618.

### Progress of the PR
- [x] Add update instruction in the user guide,
- [x] add entry to `CHANGES.rst`,
- [x] ready for review.

### CODE REVIEW

**Comment by ericpre** [comment]
@NathalieBrun, based on the suggestions your made on gitter, I have updated the installation section of the user. Could you please check the follow page and comment if necessary?

https://hyperspy--2621.org.readthedocs.build/en/2621/user_guide/install.html

**Comment by NathalieBrun** [comment]
Hello 
thanks for taking into account my questions. 

I have other questions that maybe could be useful in the user guide : 

- if you have an HyperSpy bundle installation can you update it using "conda update ... "? Some people told me to simply uninstall it then reinstall the new version, is it OK to do so? 

- in my case I had to specify the current version to update, is it a bug in my previous installation (made with Anaconda Navigator, cf 3rd question)? You could indicate in the User Guide that specify the version can solve an issue, even if you want to update with the current version. 

- is it not recommended to do the installation with Anaconda Navigator (which is very convenient to manage environments and versions of the different packages) ? 

Best regards 
Nathalie Brun 



De: "Eric Prestat" <notifications@github.com> 
À: "hyperspy/hyperspy" <hyperspy@noreply.github.com> 
Cc: "Nathalie Brun" <nathalie.brun@u-psud.fr>, "Mention" <mention@noreply.github.com> 
Envoyé: Mardi 19 Janvier 2021 18:56:40 
Objet: Re: [hyperspy/hyperspy] Add update instructions (#2621) 





[ https://github.com/NathalieBrun | @NathalieBrun ] , based on the suggestions your made on gitter, I have updated the installation section of the user. Could you please check the follow page and comment if necessary? 

[ https://hyperspy--2621.org.readthedocs.build/en/2621/user_guide/install.html | https://hyperspy--2621.org.readthedocs.build/en/2621/user_guide/install.html ]

**Comment by ericpre** [comment]
> - if you have an HyperSpy bundle installation can you update it using "conda update ... "? Some people told me to simply uninstall it then reinstall the new version, is it OK to do so?

Yes, this should work fine if your hyperspy bundle is not the portable one or <=2019.07.28 - see https://github.com/hyperspy/hyperspy-bundle/releases for details.

Uninstalling and reinstalling will definitively work! In the past, updating was not as easy and trouble free as of today, and I guess this is why people will choose this route!

> - in my case I had to specify the current version to update, is it a bug in my previous installation (made with Anaconda Navigator, cf 3rd question)? You could indicate in the User Guide that specify the version can solve an issue, even if you want to update with the current version.

This isn't an expected behaviour but there may be various reasons for this - most likely you had other dependencies in your environment preventing hyperspy to update, but I would imagine that this is a corner case.

> - is it not recommended to do the installation with Anaconda Navigator (which is very convenient to manage environments and versions of the different packages) ?

There are "integration issues" with Anaconda navigator: it works well _only_ with the anaconda distribution and it doesn't always work well with `conda-forge` which is the community and main repository for scientific packages and the one we rely on.
Instead, I think, that we should recommend alternative to the Anaconda navigator, as mentioned in https://github.com/hyperspy/hyperspy/issues/2618#issue-782300951.

**Comment by NathalieBrun** [comment]
Thanks a lot I think everything is clear now. 
Best regards 
Nathalie Brun 


De: "Eric Prestat" <notifications@github.com> 
À: "hyperspy/hyperspy" <hyperspy@noreply.github.com> 
Cc: "Nathalie Brun" <nathalie.brun@u-psud.fr>, "Mention" <mention@noreply.github.com> 
Envoyé: Mercredi 20 Janvier 2021 15:30:49 
Objet: Re: [hyperspy/hyperspy] Add update instructions (#2621) 







    * if you have an HyperSpy bundle installation can you update it using "conda update ... "? Some people told me to simply uninstall it then reinstall the new version, is it OK to do so? 




Yes, this should work fine if your hyperspy bundle is not the portable one or <=2019.07.28 - see [ https://github.com/hyperspy/hyperspy-bundle/releases | https://github.com/hyperspy/hyperspy-bundle/releases ] for details. 

Uninstalling and reinstalling will definitively work! In the past, updating was not as easy and trouble free as of today, and I guess this is why people will choose this route! 
BQ_BEGIN


    * in my case I had to specify the current version to update, is it a bug in my previous installation (made with Anaconda Navigator, cf 3rd question)? You could indicate in the User Guide that specify the version can solve an issue, even if you want to update with the current version. 

BQ_END


This isn't an expected behaviour but there may be various reasons for this - most likely you had other dependencies in your environment preventing hyperspy to update, but I would imagine that this is a corner case. 
BQ_BEGIN


    * is it not recommended to do the installation with Anaconda Navigator (which is very convenient to manage environments and versions of the different packages) ? 

BQ_END


There are "integration issues" with Anaconda navigator: it works well only with the anaconda distribution and it doesn't always work well with conda-forge which is the community and main repository for scientific packages and the one we rely on. 
Instead, I think, that we should recommend alternative to the Anaconda navigator, as mentioned in [ https://github.com/hyperspy/hyperspy/issues/2618#issue-782300951 | #2618 (comment) ] .

**Review by jlaehne — APPROVED** [review]
LGTM

**Pull request merged**
