### PR TITLE
Fix get lines intensity model

### PR DESCRIPTION
**Pull request by ericpre**
### Description of the change
This PR changes `get_lines_intensity` of `EDSModel` to behave in the same way as its `EDSSpectrum` counterpart. It allows the following:

```python
from hyperspy.datasets.example_signals import EDS_TEM_Spectrum
kfactors = [1.450226, 5.075602]  # For Fe Ka and Pt La

s = EDS_TEM_Spectrum()
s.add_elements(['Cu'])  # to get good estimation of the background
m = s.create_model(True)
m.set_signal_range(5.5, 10.0)  # to get good fit
m.fit()
intensities_m = m.get_lines_intensity(['Fe_Ka', "Pt_La"])
quant_model = s.quantification(intensities_m, method='CL',
                               factors=kfactors)

# Background substracted EDS quantification
s2 = EDS_TEM_Spectrum()
s2.add_lines()
bw = s2.estimate_background_windows(line_width=[5.0, 2.0])
intensities = s2.get_lines_intensity(background_windows=bw)
atomic_percent = s2.quantification(intensities, method='CL',
                                   factors=kfactors)

np.testing.assert_allclose([q.data for q in quant_model],
                           [q.data for q in atomic_percent],
                           rtol=0.25E-1)
```

### Progress of the PR
- [x] Change output shape  of `get_lines_intensity` of `EDSModel`,
- [x] Change input parameter of `get_lines_intensity` of `EDSModel`,
- [x] Fix `quantification` when quantifying fewer numbers of X-ray line than the X-ray lines present in the metadata,
- [x] Fix bug with `navigation_mask` in `quantification` for single spectrum,
- [x] update docstring (if appropriate),
- [x] add tests,
- [x] ready for review.

### CODE REVIEW

**Comment by francisco-dlp** [comment]
Looks good, but I have the impression that this breaks the API. Shouldn't it go to RnM is that's the case?

**Comment by ericpre** [comment]
Yes, it does break the API but it can be regarded as a bug too.

**Comment by ericpre** [comment]
Fixes #2139.

**Comment by thomasaarholt** [comment]
I don't want to get into the whole discussion about what sort of nav/signal shape `.get_lines_intensity` should return, but there is hs signal shape inconsistency here:

```python
from hyperspy.datasets.example_signals import EDS_TEM_Spectrum
s = EDS_TEM_Spectrum()
nav = hs.signals.Signal1D([1,2,3,4]).T

spectra = [s, s*nav] # single spectrum and spectrum with nav dimension

for s in spectra:
    m = s.create_model(True)
    l1 = m.get_lines_intensity(['Fe_Ka'])[0]
    l2 = s.get_lines_intensity(['Fe_Ka'])[0]

    print(l1.axes_manager.navigation_shape, l1.axes_manager.signal_shape)
    print(l2.axes_manager.navigation_shape, l2.axes_manager.signal_shape)
    print('')

--
() (1,)
(1,) ()

(4,) ()
(4,) ()
```

**Comment by viviannh81** [comment]
Hi, I am new here and have some difficulties with get_lines_intensity for EDS_TEM quanfitication.
I am working on a spectra containing 6 elements and I would just like to have the intensities of them.
I have followed the "curve fitting" instruction in the documentation but it does not give me the counds for each intensities but only "<BaseSignal, title: Intensity of Fe_Ka at 6403.90 eV from , dimensions: (|1)>" for all x-ray lines. 
I've also tried to use s.quantifiication directly, but it gives "list index out of range" and I wasn't able to make this work...
Can someone help me, please?

**Comment by jat255** [comment]
@viviannh81 can you please ask in the [gitter chat](https://gitter.im/hyperspy/hyperspy)? It's a better format for interactive help. It sounds like your sample may not have had the right elements defined, but hard to say without more information.

**Pull request merged**
