### PR TITLE
Fix quant scaling error

### PR DESCRIPTION
**Pull request by k8macarthur**
Fix to the quantification function so that the units of the scaling are checked before determining electron dose. Otherwise it raises a ValueError.

### CODE REVIEW

**Comment by k8macarthur** [comment]
This is written to fix part of #1726 .

**Comment by francisco-dlp** [comment]
Should this go to Rnp instead?

Wouldn't it be better to use pint to fix this for good i.e. support all length units?

**Comment by ericpre** [comment]
I am finishing the conversion of scale and units using pint, so, once this is done, it would be easy to convert an axis to the desired units.

**Comment by ericpre** [comment]
If we wait for #1730 to be merged into next_minor, this one should also go to next_minor!

**Comment by k8macarthur** [comment]
Ok, I'll wait on your pull then @ericpre  assuming you would be able to have a function that simply converts everything to 'nm'?

**Comment by ericpre** [comment]
Yes, if you wait for #1730, you will have a method of `DataAxis` to convert to the unit of your choice!

**Comment by k8macarthur** [comment]
I'll revisit this when #1730 is accepted as I expect this correction wont fit anymore...

**Comment by ericpre** [comment]
#1730 has been merged.

**Comment by ericpre** [comment]
@k8macarthur, you can revisit this PR, now!

**Comment by k8macarthur** [comment]
@ericpre  Great! I had a look at this today. I tried using s.axes_manager[0].convert_to_units()  but it says this function doesn't exist. Am I using this right?

**Comment by ericpre** [comment]
The following works fine for me:
```python
import hyperspy.api as hs
s = hs.datasets.artificial_data.get_core_loss_eels_line_scan_signal()
s.axes_manager

<Axes manager, axes: (12|400)>
            Name |   size |  index |  offset |   scale |  units 
================ | ====== | ====== | ======= | ======= | ====== 
  Probe position |     12 |      0 |       0 |       1 |     nm 
---------------- | ------ | ------ | ------- | ------- | ------ 
Electron energy  |    400 |        |   4e+02 |       1 |     eV 

s.axes_manager[0].convert_to_units('µm')
s.axes_manager

<Axes manager, axes: (12|400)>
            Name |   size |  index |  offset |   scale |  units 
================ | ====== | ====== | ======= | ======= | ====== 
  Probe position |     12 |      0 |       0 |   0.001 |     um 
---------------- | ------ | ------ | ------- | ------- | ------ 
Electron energy  |    400 |        |   4e+02 |       1 |     eV 
```

**Comment by ericpre** [comment]
You need to have hyperspy >= 1.4, other than that I don't see why it would not work.

**Comment by k8macarthur** [comment]
I think my update of local branches didn't work for some reason... fixed now :)

**Comment by ericpre** [comment]
Superseded by #2090.

**Pull request closed without merging**
