### PR TITLE
Remove preferences.General.default_toolkit, Fixes #903

### LINKED ISSUE #903: importing hyperspy with no toolkit
the usual `import hyperspy.api as hs` crashes if run headless (on python2, did not test for python3)

### PR DESCRIPTION
**Pull request by francisco-dlp**
Fixes #903

### CODE REVIEW

**Comment by to266** [comment]
Looks like it does not work

**Comment by francisco-dlp** [comment]
I forgot to mention that, for this to work, the mpl backend must something that doen't require a toolkit e.g. "Agg" so the following should work in a headless system:

```python

import matplotlib
matplotlib.rcParams["backend"] = "Agg"
import hyperspy.api as hs

```

**Comment by to266** [comment]
Ok, that works. I would add instructions to the user-guide for this

**Comment by francisco-dlp** [comment]
Done.

**Pull request merged**
