### PR TITLE
Split IO - RosettaScIO

### PR DESCRIPTION
**Pull request by francisco-dlp**
### Description of the change
Split HyperSpy's IO plugins into a separate package RosettaSCIIO. See #1978 for the related discussion.

### Progress of the PR
- [ ] Change implemented (can be split into several points)
    - [x] Move all plugins to a separate folder, with its own setup.py, that must be installed separately.
    - [x] Move each plugin to a folder of its own
    - [x] Move all IO tests to rsciio
    - [x] Enable lazy loading of the plugins by moving the specifications to yamls files.
    - [ ] Make rosettasciio fully independent of HyperSpy
        - [ ] Create per plugin mapping yaml that maps the original metadata to hyperspy's metadata
        - [ ] Don't use ``DictionaryTreeBrowser``
        - [ ] Move ``misc.io`` code to ``rsciio``
    - [ ] Move User Guide IO chapter to rsciio

- [ ] update docstring (if appropriate),
- [ ] update user guide (if appropriate),
- [ ] add tests,
- [ ] ready for review.

### CODE REVIEW

**Comment by dnjohnstone** [comment]
Having recently split a package (diffsims) out of another (pyxem) I think this PR might be about to hit some problems - I guess the plan remains to do the splitting "internally" and then to use git filter-branch to separate out things and then make a new repo for rsiio? As discussed in #1978 

I tried to do that for diffsims and the net result was that I effectively lost all commit history for the relevant files because git didn't seem to track things well when I moved all the files in to their own new directory within the code. (see here for where I was trying to do that https://github.com/pyxem/pyxem/pull/407) It may be that there is some git wizardry that can avoid this issue but both myself @pc494 looked for it and didn't find it.

In the end what we did was to simply make the new repo as pyxem/diffsims then branch the whole code base into there and then delete the code that was not intended for diffsims. Then we releaed diffsims as standalone and went back and did the opposite deletion from the pyxem/pyxem repo whilst importing everything from diffsims. This does mean that there are some apparent contributors to the split off repo who didn't actually write any code in it any more but I think this is much better than the alternative where it seemed it would look as though I had written all of the package alone.

The other advantage is that doing the initial deletion of things to get the new independent split package working on its own was pretty quick and in any case on a totally removed timeline from the original repo.

Just sharing in case this is helpful - if there was a more elegant way to do that, I would be curious.

**Comment by francisco-dlp** [comment]
@dnjohnstone, thanks for sharing your (bad) experience with ``git filter-branch``. That was indeed the plan. We've used it already (following the procedure detailed a blog post from the IPython team) to split the GUI packages and it worked fine then. But that was some years ago, maybe things have changed. For the moment the plan is indeed to split the code internally as done here, and split it into different repositories once we're sure that everything is working.

**Comment by dnjohnstone** [comment]
> @dnjohnstone, thanks for sharing your (bad) experience with `git filter-branch`. That was indeed the plan. We've used it already (following the procedure detailed a blog post from the IPython team) to split the GUI packages and it worked fine then. But that was some years ago, maybe things have changed. For the moment the plan is indeed to split the code internally as done here, and split it into different repositories once we're sure that everything is working.

Ok - probably it's my stupidity then :) do you have the link to the blog post you followed so that I could learn something from it?

**Comment by ericpre** [comment]
A few other relevant links on this topic at:
https://github.com/hyperspy/hyperspy/issues/1978#issuecomment-462840257
https://github.com/hyperspy/hyperspy/issues/1978#issuecomment-462844714

**Comment by jlaehne** [comment]
The handling of the metadata is an important point that was also part of the discussion in https://github.com/LumiSpy/lumispy/issues/53#issuecomment-806205848

On a sidenote, the German condensed matter physics community is working on Nexus application definitions for a large variety of non-synchrotron measurement techniques: https://fairmat-experimental.github.io/nexus-fairmat-proposal/d122a69ce0c953805e60a662e9580ee2c4a6fae7/index.html
As HyperSpy/RosettaScIO already provides a nexus reader (and they are aware of it) it would in the mid-term make sense to develop it into the python IO tool for this community and one could hopefully source some developer time from them for that if the basics are ready.

**Comment by francisco-dlp** [comment]
Closing in favor of #2972

**Comment by francisco-dlp** [comment]
🔗 Cross-referencing: The metadata handling improvements discussed in this PR now have a formal proposal — [hyperspy-proposals PR #1](https://github.com/hyperspy/hyperspy-proposals/pull/1).

The proposal defines:
- **Declarative YAML migrations** to replace the ad-hoc EM migration code that RosettaSciIO's split left in `_hierarchical.py`
- **Streamlined v4.0 encoding** (JSON metadata, compact axes) to simplify the IO layer
- **Producer metadata** (`metadata.producer`) replacing the separate `original_metadata` container

Please review and provide feedback by **July 29, 2026**.

**Pull request closed without merging**
