### PR TITLE
Fix issue with figure rendering for signal1D.

### LINKED ISSUE #1988: plot from hs.interactive not updating with events
From the [docs](http://hyperspy.org/hyperspy-doc/current/user_guide/tools.html#region-of-interest-roi):
```
%matplotlib notebook
import hyperspy.api as hs
import scipy.misc
im = hs.signals.Signal2D(scipy.misc.ascent())
im.plot()
roi = hs.roi.RectangularROI(left=30, right=500, top=200, bottom=400)
im_roi = roi.interactive(im, color="red")
roi_hist =hs.interactive(im_roi.get_histogram,
                         event=im_roi.axes_manager.events.\
                               any_axis_changed,
                         recompute_out_event=None)
roi_hist.plot()
```
This should show the following behaviour:
image_with_rect_roi

However, dragging around does not change the plot at all. 

Manually calling roi_hist.plot() after moving the ROI shows a changed plot, so data in `roi_hist`is being updated, but is not being shown on the plot.

### PR DESCRIPTION
**Pull request by ericpre**
Fixes #1988.

### CODE REVIEW

**Comment by francisco-dlp** [comment]
Any chance to submit this to Rnp?

**Comment by francisco-dlp** [comment]
LGTM, I'll just wait for travis to agree.

**Comment by ericpre** [comment]
Appveyor is fine: https://ci.appveyor.com/project/ericpre/hyperspy/build/1.0.457

**Comment by thomasaarholt** [comment]
Great, thanks for the quick work!

**Pull request merged**
