### PR TITLE
Fix to atomic-to-weight function

### PR DESCRIPTION
**Pull request by k8macarthur**
Fix to issue #1796

### CODE REVIEW

**Comment by thomasaarholt** [comment]
Should the file "ysk1a5qt.4xt.txt" be merged with this?

**Comment by k8macarthur** [comment]
Well spotted! Oops...

**Comment by ericpre** [comment]
I think this should go to next_patch. Also having all these merges with upstream make the history log is bit messy. Could you please checkout from next_patch and open another PR?

**Comment by k8macarthur** [comment]
I'm happy to try that but it seems like the release_next_patch is really behind the release_next_minor

**Pull request closed without merging**
