### PR TITLE
Fix typo in logger method and calibrate

### LINKED ISSUE #1110: Signal1d.calibrate raises error
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-41-5427191647f2> in <module>()
----> 1 sc.calibrate()

/home/fjd29/Python/hyperspy3/hyperspy/decorators.py in wrapper(*args, **kwargs)
     54     def wrapper(*args, **kwargs):
     55         if preferences.General.interactive is True:
---> 56             return cm(*args, **kwargs)
     57         else:
     58             raise NoInteractiveError

/home/fjd29/Python/hyperspy3/hyperspy/_signals/signal1d.py in calibrate(self)
    627         """
    628         self._check_signal_dimension_equals_one()
--> 629         calibration = SpectrumCalibration(self)
    630         calibration.edit_traits()
    631 

NameError: name 'SpectrumCalibration' is not defined

### PR DESCRIPTION
**Pull request by francisco-dlp**
Fixes #1110

### CODE REVIEW

**Comment by thomasaarholt** [comment]
If this is good, can we add it to master? I'd actually like to calibrate some old data I have.

**Comment by thomasaarholt** [comment]
Actually, ended up checking it out in git. I hadn't used it before now - if I wanted to just calibrate the signal by a translation in the energy axis, how should I got about it? Say that I need to shift a peak that is currently centered on 500eV to 520eV?

**Comment by francisco-dlp** [comment]
I would simply change the "offset" attribute of the axis e.g.:

```python

s.axes_manager.signal_axes[0].offset += 20

```

**Comment by thomasaarholt** [comment]
Excellent, thanks!

**Pull request merged**
