### PR TITLE
able to save lists, tuples and binary strings in hdf5

### PR DESCRIPTION
**Pull request by to266**
Without tests so far, but fixes https://github.com/hyperspy/hyperspy/issues/378

TODO
--------

- [x] unittests

### CODE REVIEW

**Comment by to266** [comment]
Ready for merge

**Comment by pburdet** [comment]
Great, I'm using that all the time in a hacky way on my working branch.

Documentation would be nice. What about? It makes more sense with a higher dimension object, but...

```python

s = utils.example_signals.EDS_SEM_Spectrum()
s.metadata.Sample.intensities = s.get_lines_intensity()
s.save('EDS_Spectrum.hdf5')

s = load('EDS_Spectrum.hdf5')
s.metadata.Sample.intensities

```

**Comment by to266** [comment]
Done!

**Comment by pburdet** [comment]
Good

**Pull request merged**
