### PR TITLE
First draft of dev-guide

### PR DESCRIPTION
**Pull request by dnjohnstone**
With reference to #782 I have hacked out a first draft for a developer guide to help people get started with contributing to HyperSpy.

Feedback on content much welcomed.

On a practical note - I don't actually know how to add links and images into a .rst file properly so guidance on that would be great!

### CODE REVIEW

**Comment by vidartf** [comment]
Neat!
The thing I feel is missing the most though, is a quick mention of the github pattern. You link to the github page, but I think it is much easier to include a short list of steps ourselves (and it does not rely on what github does with their front-page), e.g. that the contribution pattern is:
 * Setup git/github if you don't have it
 * *Fork* hyperspy on gihub.
 * *Checkout* your fork locally.
 * Create a new *branch* where you will create your changes.
 * *Push* the local changes to your github fork.
 * Create a *pull request* to the official hyperspy project.

Also: Adding a little note saying that it is impossible to ruin the official fork without write access (being on the dev team), can help people be more confident in playing around :)

**Comment by vidartf** [comment]
PS: For Windows/Mac users, I would also add a recommendation to install and use [GitHub Desktop](https://desktop.github.com/)!

**Comment by dnjohnstone** [comment]
Thanks @vidartf -- I've added the things you suggested.

Also think I got my head round the syntax for adding web links and a figure (although perhaps eps is not the best file format... what is?)

**Comment by tjof2** [comment]
This looks good as a first draft, perhaps check the formatting of of the links (and a few typos here and there...).

In general, I feel it's a little heavy on the Git part, and a little light on the Python/HyperSpy part, and it could cover in more the detail the ways in which one can contribute, which could include (not an exhaustive list!)

+ Bugs
+ Feature requests
+ Writing unit tests
+ Writing documentation
+ Adding new features

Also, some sort of thought process to follow when considering whether to contribute would be useful:

+ How does my feature fit in to HyperSpy?
+ Is it something others will find useful?

Obviously one answer is to just ask! But a sentence or two wouldn't go amiss. For reference, I quite like [the JQuery page](https://contribute.jquery.org/open-source/).

As a secondary point (since this might not be the appropriate place for this...), as someone for whom Python is very new, I find this intimidating:

> HyperSpy follows the Style Guide for Python Code - these are just some rules for consistency that you can read all about in the Python Style Guide.

I mean, I know what that *means*, but it doesn't really demystify how I can get started in contributing!

**Comment by dnjohnstone** [comment]
Ok - thanks for that.... I think your first points are probably easy to add in as you describe them.

As regards the Style Guide... Perhaps the easiest way to minimise that issue is to point people in the direction of good Python developer environments? These handle a lot of the style points and also often check using the checker when you save -- would that do?

**Comment by dnjohnstone** [comment]
@thomasaarholt your opinion might be valuable here -- would this be useful to you?

**Comment by tjof2** [comment]
My second point re:style guide was more that I think this section could be expanded a little. e.g. the basic environment of HyperSpy - a summary of the main classes? Otherwise us procedural Fortran folks get lost very quickly.

Then a reference to the style guide for more information...

**Comment by vidartf** [comment]
@tjof2 : The python style guide is basically only deals with how the code looks (number of lines between function definitions, space around assignment operators while not around '=' in argument list). I think what you were asking for is what we plan to put in the Quickstart guide?

**Comment by vidartf** [comment]
> Perhaps [...] point people in the direction of good Python developer environments?

+1. Good IDEs solve so many problems...

**Comment by dnjohnstone** [comment]
That was my impression too @vidartf - I think what @tjof2 wants is the "code map"/"quickstart guide" planned separately in #782 --- I know @to266 has made a very nice visual recently that might serve as a starting point for this if he agrees?

**Comment by tjof2** [comment]
I more meant a sentence, rather than an expansive section (which as you rightly say is the Quickstart guide). I just think that a reference to the style guide without much else is too cryptic, as a beginner. Something along the lines of:

"HyperSpy is built around (brief description). For more information, see Quickstart / Python style guide"

would be friendlier.

**Comment by to266** [comment]
@dnjohnstone you mean [this](https://www.youtube.com/watch?v=h1s7ZK8ajRw) ? Obviously you are free to use it, however I'm not sure it's as useful as it might seem from the first glance :)

**Comment by vidartf** [comment]
> @dnjohnstone you mean this ?

Fun! But I guess the interesting bit would be a detailed view of the last frame?

**Comment by tjof2** [comment]
@dnjohnstone @vidartf  on reflection, "Get good habits" is fine as a section,  but more attention should be drawn to the Python bit than it is currently -- since Git is something that can be learnt outside of HyperSpy, a stronger focus on **HyperSpy** would help, IMO

**Comment by dnjohnstone** [comment]
@francisco-dlp am I right in thinking that you want to do something on this before I do any more? Or would you like me to update some things in line with the comments above?

**Comment by francisco-dlp** [comment]
Yes, you're right. However, thinking about it, this is already very good as a dev guide for the researcher-no-experience-with-github kind of contributor, so I'll merge it and I'll open another PR to complement this with extra info with a different focus.

**Pull request merged**
