### PR TITLE
fix: bcf hitachi; enh: multi-hypermap index

### PR DESCRIPTION
**Pull request by sem-geologist**
The fix to #1751 and more future-proof.

### CODE REVIEW

**Comment by ericpre** [comment]
I am getting the following error when loading the test file provided by @thor0411:

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-9f6e242204ee> in <module>()
----> 1 hs.load('test.bcf')

~/Dev/hyperspy/hyperspy/io.py in load(filenames, signal_type, stack, stack_axis, new_axis_name, lazy, **kwds)
    241             objects = [load_single_file(filename, lazy=lazy,
    242                                         **kwds)
--> 243                        for filename in filenames]
    244 
    245         if len(objects) == 1:

~/Dev/hyperspy/hyperspy/io.py in <listcomp>(.0)
    241             objects = [load_single_file(filename, lazy=lazy,
    242                                         **kwds)
--> 243                        for filename in filenames]
    244 
    245         if len(objects) == 1:

~/Dev/hyperspy/hyperspy/io.py in load_single_file(filename, signal_type, **kwds)
    284                                 reader=reader,
    285                                 signal_type=signal_type,
--> 286                                 **kwds)
    287 
    288 

~/Dev/hyperspy/hyperspy/io.py in load_with_reader(filename, reader, signal_type, **kwds)
    293     lazy = kwds.get('lazy', False)
    294     file_data_list = reader.file_reader(filename,
--> 295                                         **kwds)
    296     objects = []
    297 

~/Dev/hyperspy/hyperspy/io_plugins/bcf.py in file_reader(filename, select_type, index, downsample, cutoff_at_kV, instrument, lazy)
   1214             downsample=downsample,
   1215             cutoff_at_kV=cutoff_at_kV,
-> 1216             lazy=lazy)
   1217 
   1218 

~/Dev/hyperspy/hyperspy/io_plugins/bcf.py in bcf_hyperspectra(obj_bcf, index, downsample, cutoff_at_kV, lazy)
   1255     for index in indexes:
   1256         obj_bcf.persistent_parse_hypermap(index=index, downsample=downsample,
-> 1257                                       cutoff_at_kV=cutoff_at_kV, lazy=lazy)
   1258         eds_metadata = obj_bcf.header.get_spectra_metadata(index=index)
   1259         hyperspectra.append({'data': obj_bcf.hypermap[index].hypermap,

~/Dev/hyperspy/hyperspy/io_plugins/bcf.py in persistent_parse_hypermap(self, index, downsample, cutoff_at_kV, lazy)
    901                                        downsample=dwn,
    902                                        cutoff_at_kV=cutoff_at_kV,
--> 903                                        lazy=lazy)
    904         self.hypermap[index] = HyperMap(hypermap,
    905                                         self,

~/Dev/hyperspy/hyperspy/io_plugins/bcf.py in parse_hypermap(self, index, downsample, cutoff_at_kV, lazy)
    954                 res = da.from_delayed(value, shape=shape, dtype=dtype)
    955             else:
--> 956                 res = value.compute()
    957             return res
    958         else:

/opt/anaconda3/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
     96             Extra keywords to forward to the scheduler ``get`` function.
     97         """
---> 98         (result,) = compute(self, traverse=False, **kwargs)
     99         return result
    100 

/opt/anaconda3/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    203     dsk = collections_to_dsk(variables, optimize_graph, **kwargs)
    204     keys = [var._keys() for var in variables]
--> 205     results = get(dsk, keys, **kwargs)
    206 
    207     results_iter = iter(results)

/opt/anaconda3/lib/python3.6/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, **kwargs)
     73     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     74                         cache=cache, get_id=_thread_get_id,
---> 75                         pack_exception=pack_exception, **kwargs)
     76 
     77     # Cleanup pools associated to dead threads

/opt/anaconda3/lib/python3.6/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    519                         _execute_task(task, data)  # Re-execute locally
    520                     else:
--> 521                         raise_exception(exc, tb)
    522                 res, worker_id = loads(res_info)
    523                 state['cache'][key] = res

/opt/anaconda3/lib/python3.6/site-packages/dask/compatibility.py in reraise(exc, tb)
     58         if exc.__traceback__ is not tb:
     59             raise exc.with_traceback(tb)
---> 60         raise exc
     61 
     62 else:

/opt/anaconda3/lib/python3.6/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    288     try:
    289         task, data = loads(task_info)
--> 290         result = _execute_task(task, data)
    291         id = get_id()
    292         result = dumps((result, id))

/opt/anaconda3/lib/python3.6/site-packages/dask/local.py in _execute_task(arg, cache, dsk)
    269         func, args = arg[0], arg[1:]
    270         args2 = [_execute_task(a, cache) for a in args]
--> 271         return func(*args2)
    272     elif not ishashable(arg):
    273         return arg

/opt/anaconda3/lib/python3.6/site-packages/dask/compatibility.py in apply(func, args, kwargs)
     45     def apply(func, args, kwargs=None):
     46         if kwargs:
---> 47             return func(*args, **kwargs)
     48         else:
     49             return func(*args)

~/Dev/hyperspy/hyperspy/io_plugins/unbcf_fast.pyx in hyperspy.io_plugins.unbcf_fast.parse_to_numpy (hyperspy/io_plugins/unbcf_fast.c:6598)()

TypeError: parse_to_numpy() got an unexpected keyword argument 'index'
```
I had issues with checking out this branch and re-compiling the CPython code:
- in my case, the `unbcf_fast.c` was not updated. I deleted it and the post-checkout created a new `unbcf_fast.c`.
- all files seem to be have been updated during the post-checkout but the error is still exactly the same.

@sem-geologist, can you load the test file?

**Comment by sem-geologist** [comment]
you have to delete both .c and .so (or dll? if on windows), and recheckout or redo build_ext.
It is problem of post-git checkout which I have to find mood and proper way to fix.
as pyx file was changed too. I had same error, before recompiling from scratch

**Comment by ericpre** [comment]
Indeed, after removing both files it works. Comparing the log shows that it did an additional step:
```
Compiling hyperspy/io_plugins/unbcf_fast.pyx because it changed.
[1/1] Cythonizing hyperspy/io_plugins/unbcf_fast.pyx
```
The modification times of both files changed after the checkout, so I naively thought that the files were up-to-date...

**Comment by sem-geologist** [comment]
@ericpre , Wait a moment, this is not a marathon! I PR only working core code, didn't had time to fill PR page, document some new code, change relevant parts in the hyperspy's docstrings and documentation.
I think I should open new PR to do that.

**Comment by ericpre** [comment]
Sorry, I reviewed it and found it good enough to go!!

**Comment by sem-geologist** [comment]
My brain is not used to such fast merge :P

**Pull request merged**
