### PR TITLE
Added raspberry pi installation instructions

### PR DESCRIPTION
**Pull request by thomasaarholt**
### Description of the change
@gerardgilliland explains in #1775 how to install hyperspy on a raspberry pi. It is absolutely worthwhile to include in the docs, which I have done here. It is essentially a copy/paste of what @gerardgilliland has written.

### CODE REVIEW

**Comment by gerardgilliland** [comment]
Thomas,

Thank you.

Gerard

**Comment by francisco-dlp** [comment]
I am not fully comfortable with merging this unless somebody who uses HyperSpy in a RPi volunteers to keep the information up-to-date. As a side note, installing package as root using pip is usually not recommend. Removing ``sudo`` and adding the ``--user`` flag should help with this.

**Comment by ericpre** [comment]
I am also a bit sceptical about these steps, even if they may work OK, I think they should be improved. I may have a look at it at some point.

**Comment by thomasaarholt** [comment]
That's fine. Leaving it here in case anyone wants to improve upon it.

**Comment by gerardgilliland** [comment]
I believe francisco-dlp and ericpre both have valid comments. I know that keeping information up to date is always a valid concern and it always comes later than the user thinks it should. I can't test the --user vs sudo change at this time.  I agree with thomasaarholt leave it for now but if you want to improve it that would be great.

**Comment by gerardgilliland** [comment]
thomasaarholt,
I checked Raspberry Pi version release date: 2018-03-14
I asked myself the leading question: if not now, when?
So… I installed Raspbian NOOBS Version: 2.7.0
Attempted to use --user instead of sudo per francisco-dlp
Reverted to sudo, got new errors in Notebook.
Sometimes it's hard to recognize progress.
Peace,
Gerard


Assumptions: microSD card > 8GB (8GB causes out of memory 32GB recommended), NOOBS, and wi-fi installed and operable
NOOBS Version: 2.7.0 Release date: 2018-03-14
https://www.raspberrypi.org/downloads/noobs/
all hyperspy files are loaded directly on raspberry pi via terminal
i.e. keyboard, monitor, and wi-fi exist on the raspberry pi
hyperspy version 1.3

Attempt --user instead of sudo.  There were no errors in the install process

From the terminal:

```
pi@raspberrypi:~`` $ sudo apt-get update
pi@raspberrypi:~ $ # install ftp so I can transfer files -- not related to hyperspy
pi@raspberrypi:~ $ sudo apt-get install pure-ftpd 
pi@raspberrypi:~ $ sudo reboot
pi@raspberrypi:~ $ sudo apt-get install python3-pip
pi@raspberrypi:~ $ # if not already the latest version then reboot 
pi@raspberrypi:~ $ pip3 install --user hyperspy
pi@raspberrypi:~ $ pip3 install --user jupyter
pi@raspberrypi:~ $ pip3 install --user numpy --upgrade
pi@raspberrypi:~ $ # pip3 install --user h5py doesn't resolve the error.
pi@raspberrypi:~ $ sudo apt-get install python3-h5py
pi@raspberrypi:~ $ pip3 install --user hyperspy_gui_ipywidgets
pi@raspberrypi:~ $ sudo reboot
```

Attempt to run  jupyter notebook:

```
pi@raspberrypi:~`` $ jupyter notebook
bash: /home/pi: Is a directory

```
the error ...
'is a directory' error when trying to pass a directory name into a function
So i did a search on jupyter 
`search:///?recursive=1&show_hidden=1&name=jupyter&name_ci=1`
and found two jupyter folders and this following script named jupyter

```

#!/usr/bin/python3

# -*- coding: utf-8 -*-
import re
import sys

from jupyter_core.command import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

{
  "load_extensions": {
    "jupyter-js-widgets/extension": true
  }
}


```
One of the jupyter folders 
`/home/pi/.local/etc/jupyter/nbconfig/notebook.d`
contained: widjetsnbextension.json:

```
{
  "load_extensions": {
    "jupyter-js-widgets/extension": true
  }
}

```

the other jupyter folder lead me to:
`/home/pi/.local/share/jupyter/nbextensions/jupyter-js-widgets`
extension.js - a long script that starts out verifying installed modules
and
extension.js.map that is empty.

So I think I need to tell bash where jupyter is and what I want to do with it.
But I don't know how to.
And maybe I am wrong with understanding of 
bash: /home/pi: Is a directory
And maybe I should have placed the folders under /home/pi -- but I didn't.


Plan B: Attempting to repeat last December with sudo to see if it still works with version 2.7.0

previously loaded: (above)

```
pi@raspberrypi:~ $ sudo apt-get update
pi@raspberrypi:~ $ # install ftp so I can transfer files -- not related to hyperspy
pi@raspberrypi:~ $ sudo apt-get install pure-ftpd 
pi@raspberrypi:~ $ sudo reboot
pi@raspberrypi:~ $ sudo apt-get install python3-pip
pi@raspberrypi:~ $ # if not already the latest version then reboot 

```

starting here:
```
pi@raspberrypi:~ $ sudo pip3 install hyperspy
pi@raspberrypi:~ $ sudo pip3 install jupyter
pi@raspberrypi:~ $ sudo pip3 install numpy --upgrade
pi@raspberrypi:~ $ sudo apt-get install python3-h5py
pi@raspberrypi:~ $ sudo pip3 install hyperspy_gui_ipywidgets
pi@raspberrypi:~ $ sudo reboot

```
I did not run the following and and then run hyperspy to test if h5py was still erroring. 
`pi@raspberrypi:~ $ # sudo pip3 install h5py` doesn't resolve the error.
When I ran the "fix" from my previous install (in December), it downloaded code 
When I run the following now, I get 

```
pi@raspberrypi:~ $ sudo apt-get install python3-h5py
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-h5py is already the newest version (2.7.0-1).
0 upgraded, 0 newly installed, 0 to remove and 38 not upgraded.


```
So, I suspect the python3-h5py problem got fixed between versions.
and thus 
```
pi@raspberrypi:~ $ # sudo pip3 install h5py doesn't resolve the error.
pi@raspberrypi:~ $ sudo apt-get install python3-h5py

```
can be removed from the process
which leaves:
Fix the -- user problem (or my problem in not understanding it) OR use sudo

Install from the terminal:
```
pi@raspberrypi:~ $ sudo apt-get update
pi@raspberrypi:~ $ # install ftp so I can transfer files -- not related to hyperspy
pi@raspberrypi:~ $ sudo apt-get install pure-ftpd 
pi@raspberrypi:~ $ sudo reboot
pi@raspberrypi:~ $ sudo apt-get install python3-pip
pi@raspberrypi:~ $ # if not already the latest version then reboot 
pi@raspberrypi:~ $ sudo pip3 install hyperspy
pi@raspberrypi:~ $ sudo pip3 install jupyter
pi@raspberrypi:~ $ sudo pip3 install numpy --upgrade
pi@raspberrypi:~ $ sudo pip3 install hyperspy_gui_ipywidgets
pi@raspberrypi:~ $ sudo reboot

```

To run hyperspy in notebook with Raspberry Pi: 
`pi@raspberrypi:~ $ jupyter notebook`
Click “New” in the Notebook
Select Python 3
It creates a new Untitled.ipynb file and enables existing and displays new buttons
Enter The following example.
You will have [numbers] instead of the >>> command prompt.

```
>>> # matplotlib backends:
    # inline -- show inline images (small)
    # nbagg -- show inline images same size as notebook
    # tk -- show external images
    # notebook -- show inline images (larger than inline)
>>> %matplotlib tk
>>> import hyperspy.api as hs
>>> import numpy as np
>>> import matplotlib.pyplot as plt
>>> dat = plt.imread("YourFile.jpg") # put the file in /home/pi
>>> dat.shape # for each y, x, and RGB
>>> img = hs.signals.Signal2D(dat) # return signal array of your data
>>> # show y-axis x 3 columns of colors and a 0 to 255 color scale and a graph with sum values for each y when color
>>> img.plot(colorbar=True, scalebar=False, axes_ticks=True, cmap='RdYlBu_r', saturated_pixels=0)
>>> dat = (0.21 * dat[:,:,0] + 0.71 * dat[:,:,1] + 0.07 * dat[:,:,2]).astype('uint8') # convert to gray
>>> dat.shape # now it is gray
>>> img = hs.signals.Signal2D(dat) # pass the grey array to the 2D signal
>>> plt.imshow(dat) # tie the array to matplotlib - grey image with signal caption
>>> # show image with pseudo colors and a 0 to 255 color scale
>>> img.plot(colorbar=True, scalebar=False, axes_ticks=True, cmap='RdYlBu_r', saturated_pixels=0)
>>>

```
The notebook ran and produced the plots as described but also produced the following errors:
error following the line: 

```
>>> import hyperspy.api as hs
      /home/pi/.local/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from float to np.floating is deprecated. In future, it will be treated as np.float64 == np.dtype(float).type. from ._conv import register_converters as _register_converters
      The Bruker composite file reader can not be loaded because the lxml library is not installed. To enable it install the Python lxml package.
      WARNING:hyperspy.api:The traitsui GUI elements are not available, probably because the hyperspy_gui_traitui package is not installed. 

```

because installing hyperspy_gui_traitui package caused more problems in December and I sucessfully get plots so I am not worried. I would need to load lxml if I was doing Bruker files.

error following the line: 

```
>>> img.plot(colorbar=True, scalebar=False, axes_ticks=True, cmap='RdYlBu_r', saturated_pixels=0)
      /home/pi/.local/lib/python3.5/site-packages/hyperspy/io.py:341: FutureWarning: Conversion of the second argument of issubdtype from complex to np.complexfloating is deprecated. In future, it will be treated as np.complex128 == np.dtype(complex).type. 
        if np.issubdtype(dtype, complex):
      /home/pi/.local/lib/python3.5/site-packages/hyperspy/signal.py:1990: FutureWarning: Conversion of the second argument of issubdtype from complex to np.complexfloating is deprecated. In future, it will be treated as np.complex128 == np.dtype(complex).type.
      if np.issubdtype(navigator().dtype, complex):


```
I didn't get this error on 2.4.5 version (in December) 
It looks like something that will cause problems in the future.

**Comment by thomasaarholt** [comment]
Closing as this is probably outdated and I have no way to check.

**Comment by gerardgilliland** [comment]
Thomas,

Closed is ok with me.

Gerard

**Pull request closed without merging**
