### PR TITLE
attempt to use ipywidgets progressbar option in prefereces

### PR DESCRIPTION
**Pull request by to266**

### CODE REVIEW

**Comment by francisco-dlp** [comment]
Maybe this could make it into Rnp too?

**Comment by to266** [comment]
Rebased

**Comment by thomasaarholt** [comment]
To review this, I sorta need to know what it is supposed to do :) Or at least how this changes from previous behaviour.

**Comment by to266** [comment]
As per the title, this adds "attempt to use ipywidgets progressbar" option in prefereces. If it's ticked, it preserves the current behaviour, if not - it uses the "text" format that is compatible with terminals or if ipywidgets are not installed.

**Pull request merged**
