### PR TITLE
Signal operations over all navigation or signal axes

### PR DESCRIPTION
**Pull request by francisco-dlp**
Currently, the only way to e.g. sum over all navigation or signal axes is to sum the axes one by one. Because this is a common task I  thought on implementing this shortcut:

```python
In [1]: im = signals.Image(np.random.random((2, 3, 4, 5, 6)))

In [2]: im
Out[2]: <Image, title: , dimensions: (4, 3, 2|6, 5)>

In [3]: im.sum(axis="navigation")
Out[3]: <Image, title: , dimensions: (|6, 5)>

In [4]: im.sum(axis="signal")
Out[4]: <Signal, title: , dimensions: (4, 3, 2|)>

```

Also, integrating over the navigation space is now the default.

There is a drawback though: if an axis name is "signal" or "navigation" it won't be clear if the user wants to sum over the axis or the "space". A workaround would be to use "_signal_" and "_navigation_" instead. Any better idea?

TODO
--------

- [ ] Write unittest
- [ ] Implement the feature in other methods that may benefit from it if any
- [ ] Update docstrings
- [ ] Update User Guide
- [ ] Reserve "signal" and "navigation" axis names.
- [ ] Pass axes tuple.

### CODE REVIEW

**Comment by pburdet** [comment]
Nice idea. I think .mean() .max() and .min() would benefit from this shortcut

**Comment by vidartf** [comment]
Yes, please! :) I agree that name collisions are an issue, which could possibly be solved by an enum?

**Comment by vidartf** [comment]
After having used this for a while, I say this is reeeeally useful day-to-day. Reserving the names is a small price to pay. 

In terms of the implementation, why not simply have this as the function body for `Signal._apply_function_on_data_and_remove_axis()`?
```python
def _apply_function_on_data_and_remove_axis(self, function, axis, out=None):
    s = out or self._deepcopy_with_new_data(self.data)
    iaxes = self._get_iaxes(axis)
    for ax in reversed(iaxes):
        s.data = function(s.data, axis=ax)
        s._remove_axis(ax)

    if out is None:
        return s
    else:
        out.events.data_changed.trigger()

def _get_iaxes(self, axis):
    if axis == "navigation":
        return sorted([ax.index_in_array for ax in self.axes_manager.navigation_axes])
    elif axis == "signal":
        return sorted([ax.index_in_array for ax in self.axes_manager.signal_axes])
    else:
        return [self.axes_manager[axis].index_in_array]
```
It's more compact + easier to read, and by not assigning like this `s.data[:] = data`, the data type is converted as dictated by the function, i.e. what happens if you pass a single axis. I might be missing some other behavior though?

**Comment by francisco-dlp** [comment]
I like your implementation. Pull request it and I'll merge it.

What do you think about using "_nav_" and "_sig_" instead of "navigation" and "signal"?

**Comment by vidartf** [comment]
Sure, I'll do it when I come to the computer next. Regarding nav/sig:
Normally in the use I've had, I almost always do it over navigation which
is the default, so then I don't care about the actual name. The few
instances where I want to do it over the signal space, I want the code to
be as self-documenting / easy to read as possible (the same goes if I
decide to explicitly state it for navigation space). Then for me it comes
down to which of these two (four) are best:

```python
s.mean ("sig")
s.mean ("signal")

# Or explicitly:
s.mean (axis="sig")
s.mean (axis="signal")

```
I think I prefer "signal", but that might just be because I'm used to it by
now :P

**Comment by vidartf** [comment]
I've created a PR with the mentioned changes. The code pasted above should serve as a guide for merging this with #424.

Regarding the current PR, while I feel maybe the `diff`/`derivate` functions could be extended to use this (using e.g. N-D sobel), and definitely `integrate_simpson` / `integrate1D` (rename latter as `integrate`?), I don't think these need to be included in the current PR. As such I can't think of any extra functions for the "Implement the feature in other methods that may benefit from it if any" step above.

**Comment by vidartf** [comment]
PS: Currently this code has parts of #424 included (first commit), so heads-up when merging.

**Comment by vidartf** [comment]
We should probably also consider extracting the docstring for the `axis` argument, as we've done in #424 / francisco-dlp/hyperspy#27.

**Comment by to266** [comment]
I've PR'ed an alternative, as this implementation was not quite flexible for my own needs... Let me know if I forgot something

**Comment by francisco-dlp** [comment]
I like your alternative very much. If @vidartf agrees I'm for closing this PR.

**Comment by francisco-dlp** [comment]
Closed in favour of #823

**Pull request closed without merging**
