### PR TITLE
Add support for extension with src layout

### PR DESCRIPTION
**Pull request by ericpre**
Alternative to #3446 based on observation from https://github.com/hyperspy/hyperspy/pull/3446#issuecomment-2408549099.

### Progress of the PR
- [x] Add support for extension with src layout,
- [n/a] update docstring (if appropriate),
- [n/a] update user guide (if appropriate),
- [x] add an changelog entry in the `upcoming_changes` folder (see [`upcoming_changes/README.rst`](https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/upcoming_changes/README.rst)),
- [x] Check formatting changelog entry in the `readthedocs` doc build of this PR (link in github checks)
- [n/a] add tests,
- [x] ready for review.

### CODE REVIEW

**Comment by ericpre** [comment]
@hakonanes, can you please have a look at this approach?

**Comment by hakonanes** [comment]
Tested, works for my `hspy_ext_src_layout` example package in both editable and non-editable mode. Thanks!

When can I anticipate this to be released?

**Comment by jlaehne** [comment]
> When can I anticipate this to be released?

See https://github.com/hyperspy/hyperspy/issues/3451

**Review by jlaehne — APPROVED** [review]

**Comment by jlaehne** [comment]
Looks good, though three tests are failing - but partly seems to be the kikuchipy test suit.

Do you want to add a changelog entry?

**Comment by ericpre** [comment]
> Do you want to add a changelog entry?

Yes, done!

**Comment by hakonanes** [comment]
Fantastic, thank you both for a speedy fix!

**Pull request merged**
