### PR TITLE
Update Zenodo DOI

### PR DESCRIPTION
**Pull request by francisco-dlp**

### CODE REVIEW

**Comment by to266** [comment]
You seem to have missed a couple of "and"s

[here](https://zenodo.org/record/54004/export/hx) is the formatted text

**Comment by jat255** [comment]
A silly thing, but I'm not sure where else to put this...

For consistency with my "scientific" persona, could we change my name to "Joshua A. Taillon"?

**Comment by francisco-dlp** [comment]
@jat255, I'll change your name in the bibtex citation entry. However, Zenodo takes this info from your GitHub profile, so, to change it there you'll have to amend you name in GitHub.

**Comment by francisco-dlp** [comment]
Done.

**Pull request merged**
