### PR TITLE
Bugfix signal rebin variance

### PR DESCRIPTION
**Pull request by to266**
Improved signal.rebin to rebin the variance too (as "geometric average")

### CODE REVIEW

**Comment by francisco-dlp** [comment]
I think that it is simpler than that, simply binning the variance should do. You would need to calculate the geometric average if it was the std.

**Comment by francisco-dlp** [comment]
bump

**Comment by to266** [comment]
Though wrong branch to merge into - should I close this PR and open a correct one?

**Comment by francisco-dlp** [comment]
Sure.

**Pull request closed without merging**
