### PR TITLE
Francisco dlp clone enh plot arguments

### PR DESCRIPTION
**Pull request by to266**
Starting point (and replaces) #489 

@jat255 , I think I fixed all the bugs you mentioned, but let me know if anything else is missing.
@pburdet , could you review the code changes and merge once the documentation is added?

The most notable change from #489 and previous versions, is that the percentile is now calculated sanely - it now gives the part  of datapoints that will __not__ be saturated (i.e. percentile of 0.9 leaves 5% of points black and 5% white (i.e. saturated) ). It does not tak into account the values of the points, only the number of them.

I believe before a bug was left, and since there was no way to specify values of percentiles and the default was sane, noone noticed.

### CODE REVIEW

**Comment by pburdet** [comment]
Nice! 

I hit a bug when I'm doing that:

```python
im = signals.Image(np.random.random((10,64, 64)))
im.plot(auto_contrast=False)
```

I'm expecting that `vmin` and `vmax`  are calculated on the current image and keept for the others images.

Also If `vmin` or `vmax` are provided, the `userWarning` is raised the first time but not afterwards. 

```python
im = signals.Image(np.random.random((10,64, 64)))
im.plot(vmin=0, vmax=1.)
```

Could `auto_contrast` be `False` if `vmin` or/and `vmax` are provided?

**Comment by to266** [comment]
Done

**Comment by vidartf** [comment]
> Also If vmin or vmax are provided, the userWarning is raised the first time but not afterwards.

That is standard behavior for python warnings as far as I can tell. Not sure exactly how to change this behavior.

**Comment by to266** [comment]
if interested:
http://stackoverflow.com/a/22661838/3589924

anyway we decided to keep it as it is

**Comment by pburdet** [comment]
That's true, thanks

**Comment by vidartf** [comment]
Thanks for the link. I agree with keeping it as it is, as changing warning behavior should be done by the end user.

**Pull request merged**
