### PR TITLE
Release v.1.4.1

### PR DESCRIPTION
**Pull request by francisco-dlp**

### CODE REVIEW

**Comment by francisco-dlp** [comment]
conda-forge builds in https://github.com/conda-forge/hyperspy-feedstock/pull/24

**Comment by francisco-dlp** [comment]
Tests are passing in conda-forge/hyperspy-feedstock#24, so I think that we're ready to release.

@ericpre, have you tested the bundle? Any chance to add a Py37 bundle?

@sem-geologist, will you have time to pull your branch for @ericpre repository for this release? (We can wait for your contribution a few days).

**Comment by ericpre** [comment]
> @ericpre, have you tested the bundle? Any chance to add a Py37 bundle?

See https://github.com/hyperspy/hyperspy_gui_ipywidgets/issues/12 and  https://ci.appveyor.com/project/ericpre/hyperspy-bundle/builds/19658254

Regarding python 3.7:
https://github.com/hyperspy/hyperspy-bundle/issues/32

> @sem-geologist, will you have time to pull your branch for @ericpre repository for this release? (We can wait for your contribution a few days).

I can make a new PR which you could review? It would be quicker.

**Comment by francisco-dlp** [comment]
I would suggest to wait to hear from @sem-geologist before taking over his branch.

**Comment by ericpre** [comment]
The bundle built with this branch can be downloaded from the following jobs on appveyor (see the artifacts tab):
https://ci.appveyor.com/project/ericpre/hyperspy-bundle/builds/19658966

**Comment by ericpre** [comment]
I have found another bug doing random testing in the bundle... I started to fix it but I haven't finished yet. To reproduce:
```python
s = hs.datasets.example_signals.EDS_TEM_Spectrum()
s.remove_background() # using the power law background
```

**Comment by francisco-dlp** [comment]
Good catch! I am surprised that nobody has reported that issue.

**Comment by ericpre** [comment]
This is a metadata issue which only occurs when removing a power law background to an EDS signal... so this is only happen when doing random and not very sensible things! :smile: 
They may be other occurrence though...

**Comment by ericpre** [comment]
Metadata issue fixed in #2076.

**Comment by sem-geologist** [comment]
@ericpre, @francisco-dlp , as I understand, there would be little difference if I would re-PR branch, or if the copy of branch would be pushed by @ericpre . The commits are mine, and so they will be preserved as that even if it is going through the copy of branch being pushed by @ericpre . I think I could do it rightly only at Monday (however I have quite busy plans, and can't guaranty) as I had left the working git tree at work. So @ericpre , please just proceed with re-PR that branch, so You would not have to wait for me.

**Pull request merged**
