### PR TITLE
New eds model

### PR DESCRIPTION
**Pull request by pburdet**
New `eds_model` as proposed in #390

Example
-----------

```python

    >>> m = create_model(st)
    >>> m.fit()
    >>> m.fit_background()
    >>> m.calibrate_energy_axis('resolution')
    >>> m.calibrate_xray_lines('energy',['Au_Ma'])
    >>> m.calibrate_xray_lines('sub_weight',['Mn_La'],bound=10)

```

TO DO
--------

- [x] DOCstring
- [x] test
- [x] doc
- [x] Add 'scale' and 'offset' options to calibrate_energy_axis
- [x] Add 'width' options to calibrate_xray_lines
- [x] Get line intensity method

### CODE REVIEW

**Comment by jrminter** [comment]
I checked this out using a .rpl file from a DTSA-II model of Al embedded in Cu. I used this code:

```
m = hs.create_model(specMax)
m.fit()
m.fit_background()
m.calibrate_energy_axis('resolution')
m.calibrate_xray_lines('energy',['Al_Ka'])

m.plot()
```

It worked as expected, with the exception of the following deprecation warning:

```
C:\Apps\Anaconda\lib\site-packages\numpy\core\fromnumeric.py:2507: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  VisibleDeprecationWarning)
```

**Comment by dnjohnstone** [comment]
Looking to resurrect this pull request as it's useful functionality - in my experience it's pretty common for the database x-ray lines to be a touch off of experimental observation which is the main thing this resolves.

It also looks quite complete to me? What is still needed?

**Comment by francisco-dlp** [comment]
It seems that it is just waiting for someone to review it...

**Comment by dnjohnstone** [comment]
Ok - thanks @francisco-dlp 

@pburdet can we force you out of 'commercial retirement' a moment for input on the numerous pull requests from you that are very close to completion please? There's some excellent stuff in here and it's very clear with a current encounter I'm having with EDS that the functionality you've added is really valuable. The issue is that in the time since these requests were made there have been substantial changes to model fitting, more of which are coming in the next couple of weeks, which will cause conflicts that will need resolving... I'm happy to make these merges in a fork and pull-request to your personal repository so that this can come through your pull request, but that will need you to have time to merge my pull request etc... Would you like me to do it that way or shall we follow another scheme that doesn't require your input?

@to266 would appreciate your input on this as well as I know you're keen to get some of this stuff merged and tied up.

**Comment by to266** [comment]
Sure, I can help. You'll just have to let me know what needs doing :)

**Comment by dnjohnstone** [comment]
Ok - I think the simplest plan is to create a new version re-based on the current master and make a new pull request to merge from... Do we agree? If so I'm happy to do that.

**Comment by jeinsle** [comment]
Sounds like a logical path.

J

Sent from my Sony Xperia™ smartphone

---- dnjohnstone wrote ----

**Comment by to266** [comment]
I'd say go ahead. Since you will be rebasing, the authorship of the original commits will still belong to @pburdet. If you reference this PR in the new one, who did what will be obvious and still clear

**Pull request merged**
