### PR TITLE
Set version back to dev

### PR DESCRIPTION
**Pull request by francisco-dlp**

### CODE REVIEW

**Comment by francisco-dlp** [comment]
I don't understand anything. travis was happy with the branch (see [this](https://travis-ci.org/francisco-dlp/hyperspy/builds/117999595)) but unhappy with the pull request... Appveyor passes (it only fails because of #914)

**Comment by vidartf** [comment]
If the issue is line endings, then I suspect the AppVeyor git checkout converts line endings to CRLF(?). 

Why it works in your branch and not the PR... No idea. What happens if you manually check out a branch that is known to work, and then redo the changes (luckily this quite a simple PR)?

**Comment by dnjohnstone** [comment]
Did anyone ever work out what was causing a problem here? It's totally bemusing to me...

**Comment by vidartf** [comment]
I would recommend nuking the branch and redoing the change (shouldn't be too much typing involved ;) ). As the issue haven't really showed up anywhere else (?), I think we don't have to solve this particular mystery (unless you're very curious).

**Comment by francisco-dlp** [comment]
Closing following @vidartf suggestion.

**Pull request closed without merging**
