### PR TITLE
Added basic class for hologram images

### PR DESCRIPTION
**Pull request by CodeMonkeyJan**
As mentioned in #1058 I separated the HologramImage class. This PR is mainly to keep this feature separated, in and off itself it is quite empty and holds mainly the documentation. I'm not sure how to proceed from here, @woozey will be the one who would make the first significant function for this class. How should he pick up from here?

### CODE REVIEW

**Comment by dnjohnstone** [comment]
I think the obvious way is for @woozey to add you as a remote to his git then he can pull this branch to his local machine, add some functions and then make a pull request to @CodeMonkeyJan. Once that pull request is merged it will appear in this one automatically and can be reviewed here. Only other solution I see is to just merge this and then work off the master - that would be up to @francisco-dlp really though.

**Comment by CodeMonkeyJan** [comment]
I'll talk to him personally, I think by now I know how to set up a remote. After he pulled my `NEW_hologram_image_class` branch I can just close this PR, right? (Or even before, as he will pull from my fork anyway).

**Comment by CodeMonkeyJan** [comment]
I forgot that `HologramImage` depends on `WaveImage`, so it has to include the class and everything else. I talked to @woozey and he now has this PR as his starting point. He will add his functions and then send a PR of his own which then could be discussed.

**Comment by CodeMonkeyJan** [comment]
@woozey now has his own PR #1079 which contains my skeletal structure and documentation. Thus, I will close this PR now.

**Pull request closed without merging**
