### PR TITLE
Multi ICA improvement

### PR DESCRIPTION
**Pull request by jat255**
Hello,

I have written a function for myself that I thought might be of use to others. It is a helper function that will automatically run through varying numbers of components and different ICA algorithms, automatically saving the results. This is useful so a user can easily run a number of ICA runs and inspect the differences immediately, rather than having to manually run each algorithm and such. 

I've tried to match the style of the other HyperSpy functions, and make the function as robust as possible. Any discussions/suggestions are welcome, and hopefully this function is of use to others.

Thanks,
Josh

### CODE REVIEW

**Comment by jat255** [comment]
Also, I apologize if there's some other procedure for contributing pull requests, but I wasn't sure where to submit the code, so please let me know if I should do this some other way.

Happy new year!

**Comment by francisco-dlp** [comment]
We are the ones who should apologize for not having a "how to contribute" guide, but you don't seem to need it as you did it just right.

Thank you for your contribution. HyperSpy needs to facilitate the exploration of the parameter space of the BSS and decomposition methods and this is a good starting point. Your solution is undoubtedly useful, but it let me wondering if a different approach wouldn't be better in the long run. You `multi_ica` method does three things:

1) Run the `blind_source_separation_method` with different number of components and algorithms.
2) Store the result of 1) in separate files. 
3) Plot the result of 1) and save the figures.

The reason why `multi_ica` is useful is that, currently, storing and plotting the result of multiple runs of `blind_source_separation` is not straightforward and, therefore, a method that accomplishes the task is welcome. An alternative approach would be to make it easier to perform these individual tasks. For example, currently HyperSpy only stores internally the result of the last `blind_source_separation` run i.e. every `blind_source_separation` run overwrites the result of previous one. However, if it appended the results instead and we add to `plot_spectra` the feature that [you suggested](https://groups.google.com/d/msg/hyperspy-users/7K-VKYyn-5g/GsnhKmRxmvgJ) it'll be possible to perform the task as follow:

```python
for algorithm in ["FastICA", "CuBICA"]:
    n in range(2,6):
        s.blind_source_separtion(n, algorithm=algorithm) # Each run appends the new results and all the args and kwargs
        
s.save("my_data_with_all_bss_results")

bss_factors = s.get_bss_factors(registers="all") # a list of all stored bss factors. The title of the signals contains all the relevant parameters.
        
utils.plot.plot_spectra(bss_factors, style="mosaic")
```

What do you think?

**Comment by jat255** [comment]
What coincidence! I just suggested this method (saving all the BSS results in one file) in the [user group](https://groups.google.com/forum/#!topic/hyperspy-users/P3jIRoc8yXk).

I think that doing it this way is a great idea. It will keep folders cleaner of all the individual files and everything. I'm not sure how this would be handled internally. I suppose get_bss_factors would now return a list of Signals as opposed to just a single Signal? I'm not sure where in the code the BSS results are stored internally, but it doesn't seem like too big of a change. I'm all for it, and will help where I can.

**Comment by francisco-dlp** [comment]
Thank you for offering help. Currently the bss results are stored in `Signal.learning_results`. `learning_results` is an instance of the `LearningResults` class. However, I think that we should start seriously considering to change the structure of the decompostion/bss code because the current one is starting to be too limiting. We'll have to discuss this thoroughly  in a separate issue. Of course, you're very welcome to join the discussion.

**Comment by francisco-dlp** [comment]
I have moved this to the recipes milestone because the code can be useful as it is while we work on the more general approach discussed above.

**Pull request closed without merging**
