### PR TITLE
Bug fix load stack

### PR DESCRIPTION
**Pull request by bm424**
Fix for the bug in loading where `stack` had conflicting defintitions.

### CODE REVIEW

**Comment by bm424** [comment]
#900

**Comment by francisco-dlp** [comment]
This bug is not present in 0.8.x, how is it possible?

**Comment by to266** [comment]
I kind-of-fixed it when porting to python3 most likely.

**Comment by to266** [comment]
it may not be true, I just remember having to sort out some merge conflicts, and it involved this issue. Could have been a different branch too, but any way I see no reason not to merge this

**Comment by francisco-dlp** [comment]
Yes, let's merge it. However, let's not label the issue as a bug as there was not bug in the 0.8.3 release.

**Pull request merged**
