### PR TITLE
Add fix for lazy s.map and nav chunks with size of 1

### LINKED ISSUE #2748: Mapping of lazy signals with chunksize 1 at the last axis of the navigation axis
Mapping of lazy signal seems not working if the chunk of the last axis of the navigation axes is 1 or (size mod chunk) is 1:

```python
import numpy as np
import dask.array as da
import hyperspy.api as hs

def f(p):
    return np.array([1,2,3])

s = hs.signals.Signal2D(da.random.random((10, 15, 32, 32))).as_lazy()
s.rechunk(nav_chunks=(1, 1))
ss = s.map(f, inplace=False, parallel=False, ragged=True)
ss.compute()
```
Same for `nav_chunks=(1, 2)` 
```python
s.rechunk(nav_chunks=(1, 2))
ss = s.map(f, inplace=False, parallel=False, ragged=True)
ss.compute()
```
It gives 
```python
IndexError: tuple index out of range
```
when computing the dask array. This will print out all failed chunks at the last dimension of the navigation axis.
```python
for k in range(1,16):
    try:
        s.rechunk(nav_chunks=(1, k))
        ss = s.map(f, inplace=False, parallel=False, ragged=True)
        ss.compute()
    except IndexError:
        print(k)
```
gives
```python
1
2
7
14
```

Is this the expected behaviour?

### PR DESCRIPTION
**Pull request by magnunor**
Fix for https://github.com/hyperspy/hyperspy/issues/2748

(Also relevant for https://github.com/hyperspy/hyperspy/pull/2703)

### CODE REVIEW

**Comment by magnunor** [comment]
Ready for review when/if the tests pass

**Comment by magnunor** [comment]
The failing tests seems to be due to unrelated issues. For the macos, some compile error with gcc. And for the Windows_Python38 some image comparison?

So this is ready for review!

**Comment by jlaehne** [comment]
LGTM.

The same tests are currently failing elsewhere too, probbaly need to be fixed in the actions setup.

**Comment by francisco-dlp** [comment]
LGTM too.

**Pull request merged**
