### PR TITLE
Bugfix saving unicode

### PR DESCRIPTION
**Pull request by to266**
solves https://github.com/hyperspy/hyperspy/issues/695

### CODE REVIEW

**Comment by francisco-dlp** [comment]
This deserves unittests...

**Comment by to266** [comment]
Added

**Comment by francisco-dlp** [comment]
When there are a mixture of strings and unicode in the list everything is casted to unicode on loading:

```python

>>> s = hs.signals.Signal(range(10))
>>> s.metadata.test = [u"Al", "B"]
>>> s.save('test')
The test.hdf5 file was created
>>> load("test.hdf5").metadata
├── General
│   └── title = u''
├── Signal
│   ├── binned = False
│   ├── record_by = spectrum
│   ├── signal_origin = u''
│   └── signal_type = u''
└── test = [u'Al', u'B']

```

I just wanted to leave this here for the record, I don't think that this is harmful and possibly there is no reasonable way to fix it anyway...

**Comment by vidartf** [comment]
Just wanted to note that this behavior is what would be expected for python3 either way.

**Pull request merged**
