### PR TITLE
Interactive crop_image

### PR DESCRIPTION
**Pull request by thomasaarholt**
### Description of the change
I've written a method for interactive cropping that plots a signal (unless it already is plotted), and then displays a rectangle centered a quarter of the way into the image. I find it rather cumbersome if I just want to get a slightly smaller image to have to plot it, and then read off the coordinates number by number and then crop using `s.isig` or `s.crop_image`.
image

We already have two methods that are related:
`s.crop()` and `s.crop_image`. I don't really see why we have these, since .isig and.inav do the same thing in a general manner, unless their intention is to save memory in some manner.

### Progress of the PR
- [x] Change implemented
- [x] update docstring
- [ ] update user guide
- [ ] add tests,
- [ ] ready for review.

### Minimal example of the bug fix or the new feature
```python
#%matplotlib notebook | widget | qt # your favourite backend here
import hyperspy.api as hs
s = hs.datasets.example_signals.object_hologram()
s.crop_image_interactive()
```

### CODE REVIEW

**Comment by francisco-dlp** [comment]
> I don't really see why we have these, since .isig and.inav do the same thing in a general manner, unless their intention is to save memory in some manner.

The reason is that the `crop` method predates `isig` i.e. there is no good reason at all for this. Maybe something to add to the to-deprecate list in #2251?

**Comment by jlaehne** [comment]
Probably it is a question of how my gui is set up, but I do not get a button to apply the cropping.

Also, is it restricted to certain types of signals? If I load an arbitrary signal image, I get `AttributeError: 'Signal1D' object has no attribute 'crop_image_interactive'`

**Comment by thomasaarholt** [comment]
@jlaehne This is a 2D signal crop method which will only work on the signal dimension. If you're doing this on a spectrum image, try doing (`s.T.crop_image_interactive()`).

**Comment by jlaehne** [comment]
OK, but wouldn't it make sense to implement such a interactive cropping tool in a more general way that could work also on e.g. the navigation image of a 1D signal spectral map, ...?

**Comment by thomasaarholt** [comment]
Yes, absolutely. I initially stepped away from this because A) `crop` was taken and B) I just wanted a crop_image method.

I can rewrite it to handle 1D and 2D signals, as well as try to handle signal/navigation as input parameters. I guess I'll then plot `s.T.sum()` and then use the respective 1D/2D crop feature, and then pass those coordinates to `isig`/`inav`. 

I'll then rename it `s.interactice_crop()`. 

Sound OK?

**Comment by ericpre** [comment]
I think before considering adding such feature, we should first implement adding a roi interactively, as mentioned in other PRs (for example https://github.com/hyperspy/hyperspy/pull/1785). There are a few PRs which requires this (https://github.com/hyperspy/hyperspy/pull/1791, https://github.com/hyperspy/hyperspy/pull/1785) and once this is done properly, it should be easy to implement the feature of this PR.
There is some discussion on this in https://github.com/hyperspy/hyperspy/pull/2182.

**Pull request closed without merging**
