### PR TITLE
Fix Kramers-Kronig Analysis bug

### PR DESCRIPTION
**Pull request by thomasaarholt**
@SlytherinEELS showed that the kramers kronig analysis failed on single spectra. That should be fixed now, but I would prefer if we could test it + write a test.

### CODE REVIEW

**Comment by francisco-dlp** [comment]
I've labeled it as WIP because the test is missing.

**Comment by thomasaarholt** [comment]
I'm going to need someone else to help write a test - I've not done any kramers-kronig before.

**Comment by francisco-dlp** [comment]
The fix looks good. I'll merge it without the test and open an issue about the missing test.

**Comment by francisco-dlp** [comment]
Here is the test issue #1633

**Pull request merged**
