### PR TITLE
Update metadata stage camera

### PR DESCRIPTION
**Pull request by ericpre**
See #1396.

- [x] Add Stage metadata (x, y, z, tilt_a, tilt_b, rotation)
- [x] Add Camera node (Name, exposure)

### CODE REVIEW

**Comment by woozey** [comment]
It seems that corresponding changes in doc files and doc strings are missing...

**Comment by ericpre** [comment]
For the user doc, this is done in #1563, what doc string should be changed?

**Comment by woozey** [comment]
Great!
Sorry, my mistake, the doc strings look good as well))

**Comment by ericpre** [comment]
Ok, thanks. I made a separate PR to avoid making #1396 too confusing by changing loads of files.

**Comment by ericpre** [comment]
Closing because merge into #1563.

**Pull request closed without merging**
