### PR TITLE
ENH: Addition of reverse_decomposition_component method

### PR DESCRIPTION
**Pull request by jat255**
Added a `reverse_decomposition_component` that is very similar to `reverse_bss_component`. Useful if you need to reverse the results of an NMF decomposition, for instance.

TO DO
--------
- [x] Add unittests.

### CODE REVIEW

**Comment by francisco-dlp** [comment]
Why would you need to do that? NMF should always give you positive loadings and factors.

**Comment by jat255** [comment]
Yes, that's definitely true, but in my (limited) experience, there have been times when even a positive result does not make much sense physically. Take for instance the following example. This is from an EELS SI of two oxide particles (on the left) surrounded by an epoxy matrix. 

I did the NMF decomposition, which first gave this signal as one of the components:
pr441_1

You can see that there is a "reverse peak" at the expected O-_K_ edge, and that the loading is strongest in the epoxy region, rather than in the oxide, which is unexpected.

Reversing this component with the method I've added quickly corrects this:
pr441_2
Showing that this component is relatively uniform across these two different oxide particles.

Since the method doesn't harm anything and adds some functionality that was missing, I don't see the harm in including it, but I'll certainly defer to your judgement for that. While I've been using the code, I had used the `reverse_bss_component` method, and just expected that there would be one for the decomposition factors as well, and was surprised when that wasn't the case. If it's offered for one, it should be for the other, too.

**Comment by francisco-dlp** [comment]
I agree with your argument: it doesn't make any harm and it may be useful in some cases. To be ready to merge this needs unittests. I know that its BSS equivalent doesn't have unittests, but this is because it is an old method from the times when we were not writing tests and it needs fixing. 

I don't fully agree with you interpretation of the NMF component of your example, but, if you like, given that this is not a software issue, we can discuss this by email.

**Comment by jat255** [comment]
Ok, I'll write up the test cases now.

**Comment by jat255** [comment]
Test cases seem to check out okay. Please let me know if these are sufficient, or how you would improve them. I have never done test cases in python, so this is a bit new to me, but I tried to follow the  examples given in the other test files.

**Pull request merged**
