### PR TITLE
Release 1.6.2

### PR DESCRIPTION
**Pull request by ericpre**
See [releasing guide](https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/releasing_guide.md).

### Progress of the PR
- [x] Update changelog,
- [x] replace python 3.7 by 3.9 (relax a test tolerance to pass with python 3.9)
- [x] bump version number,
- [x] merge #2701 (it is included in this PR get the test suite with sympy 1.8),
- [x] merge #2691,
- [ ] ready for review.

### Check build packages
- [x] check conda-forge build, see https://dev.azure.com/ericpre/hyperspy-feedstock/_build/results?buildId=1465&view=results
- [x] release workflow https://github.com/ericpre/hyperspy/actions/runs/733912898

### CODE REVIEW

**Comment by ericpre** [comment]
One more PR to avoid trouble with latest version of matplotlib: #2704

**Comment by ericpre** [comment]
We should be good to go now!

**Comment by francisco-dlp** [comment]
Looks great to me!

**Comment by ericpre** [comment]
The doc is now up to date: https://hyperspy.org/hyperspy-doc/current/index.html

**Pull request merged**
