### PR TITLE
Use the nightly merge action

### LINKED ISSUE #1711: Cascading merges from RELEASE_next_patch --> ..._minor --> ..._major
As a quality of life improvement, it would be nice to have commits in the `RELEASE_next_patch` automatically merged into `RELEASE_next_minor` (the same goes for the commits in `RELEASE_next_minor` being automatically merged into `RELEASE_next_major`).

This way, all bugfixes and additional features are always present in the branches of higher order, without the need to manually merge for every small patch.

Webhooks seem to be a valid strategy of achieving this (see: https://developer.github.com/v3/repos/hooks/).
This blogpost may also help:
https://www.atlassian.com/blog/git/git-automatic-merges-with-server-side-hooks-for-the-win

### PR DESCRIPTION
**Pull request by ericpre**
Use https://github.com/marketplace/actions/nightly-merge to merge RnP into RnM. Fix #1711.

I have tested it in my fork (with `allow_forks` enabled) and it works fine, see:
- https://github.com/ericpre/hyperspy/actions/runs/219147454 for the CI
- https://github.com/ericpre/hyperspy/commit/2268a66687eec6c34871ea1284ce07881d6d9b63 for the commit

### CODE REVIEW

**Review by tjof2 — APPROVED** [review]

**Comment by tjof2** [comment]
Fantastic!

**Comment by ericpre** [comment]
If this works fine: it should merge RnP into RnM at 0:00 UTC! When there is a conflict, the workflow fails and github send an email about the failing workflow.

**Comment by francisco-dlp** [comment]
What about adding a new one for Rnm -> non_uniform_axes?

**Comment by ericpre** [comment]
> What about adding a new one for Rnm -> non_uniform_axes?

Yes, good idea! 

There is currently a merge conflict between RnP and RnM (fix of the RnP version), we can leave it as it for the next run and check tomorrow that it behaves as expected.

**Pull request merged**
