### PR TITLE
Add 'line_width' in the plot_spectra function

### PR DESCRIPTION
**Pull request by MartialD**
Update utils.py
Add the line_width command in the plot_spectra function and sub function

### CODE REVIEW

**Comment by francisco-dlp** [comment]
The tests are not passing because this changes the default linewidth from mpl default (1) to 2. I think that it'll be better to keep the current default. Also adding a little test to check that the new arguments is well taken into account would be a good idea.

**Comment by ericpre** [comment]
What's about adding a `**kwargs_plot` to pass to `matplotlib.axes.Axes.plot`? In the `plot_spectra` function, there is already a `**kwargs`, which is passed to `matplotlib.pyplot.figure` or `matplotlib.pyplot.subplots`.

**Comment by MartialD** [comment]
@ericpre : It is a good idea, but  **kwargs (acting on matplotlib.pyplot.figure or subplot) already have a 'linewidth' parameters (acting on the frame), how can we differentiate 'linewidth' in **kwargs and **kwargs_plot?

**Comment by francisco-dlp** [comment]
Actually, I think that for a function that plots spectra it makes more sense to pass the extra kwargs to plot rather than figure. This would be a API change i.e. it'll go to hyperspy 2.0, which is due as soon as we split hyperspy (hopefully in the next 6 months). 

So, what about:

* ``**kwargs`` go to mpl plot
* new ``fig_kwargs`` takes a dictionary and goes to mpl fig

**Comment by ericpre** [comment]
Yes, indeed, my previous comment was not very pertinent, since it is not possible to have two **kwargs at the same time... but a pattern similar to [signal plot](https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/drawing/mpl_he.py#L162), as @francisco-dlp suggested, would do the job!

**Pull request closed without merging**
