### PR TITLE
Release v1.3.2

### PR DESCRIPTION
**Pull request by francisco-dlp**
Rnp with #1995 merged in and bumped patch version.

### CODE REVIEW

**Comment by francisco-dlp** [comment]
@ericpre, have you tried building a bundle with this somewhere?

**Comment by ericpre** [comment]
I ran a build yesterday to check that it is working fine, which was the case but it was using the release version (1.3.1) from pypi.

**Comment by francisco-dlp** [comment]
It would be interesting to know how it performs when pointing it to this branch, especially now that we know that dask must be upgraded by pip.

**Comment by ericpre** [comment]
This build should be pointing to this branch:
https://github.com/ericpre/hyperspy-bundle/releases/tag/2018.07.03

**Comment by francisco-dlp** [comment]
Fingers crossed, thanks!

**Comment by ericpre** [comment]
@francisco-dlp, do you want to update this branch with the last few PR merges, so the bundle is built with the last version?

**Comment by francisco-dlp** [comment]
OK. The bundle for 32bits has just finished successfully,  what looks promising :)

**Comment by francisco-dlp** [comment]
Done.

**Comment by francisco-dlp** [comment]
I've just updated the change list. All the tests pass in conda forge and the Py35 bundles, so it looks good!

**Comment by francisco-dlp** [comment]
In case that somebody want to try installing the new version with pip, I've just uploaded it to https://test.pypi.org/project/hyperspy/

To install it:

```bash
pip install --upgrade hyperspy --index-url https://test.pypi.org/simple/
```

**Pull request merged**
