### PR TITLE
Use ValidNumberElements instead of TotalNumberElements

### PR DESCRIPTION
**Pull request by ercius**
### Description of the change
This patch fixes loading FEI SER data where the acquisition was stopped before it was finished. SER files indicate this by the value in header['ValidNumberElements'] which was not previously used. Instead, the code used header['TotalNumberElements'] which may not match the file size. This is documented in  #1928 and some other related issues such as #2133 .

### A few sentences and/or a bulleted list to describe and motivate the change:
- Use header['ValidNumberElements'] for the dataOffsetArray size.
- Use header['ValidNumberElements'] for the data array size
- Crop series data (e.g. image series) instead of setting all values not acquired to 0 or NaN

### Progress of the PR
**Note: Need to remove printing statements, but they are useful for review.**
- [X] Change implemented (can be split into several points),
- [x] Add tests
- [X] Ready for review.

### Minimal example of the bug fix or the new feature
```python
>>> import hyperspy.api as hs
>>> from pathlib import Path
>>> imPath = Path('./hyperspy/tests/io/FEI_old/03_Scanning Preview_1.ser')
>>> im = hs.load(imPath.as_posix())
>>> print('image series data shape = {} and should be == (5, 128, 128)'.format(im.data.shape))
>>> sPath = Path('./hyperspy/tests/io/FEI_old/X - Au NP EELS_2.ser')
>>> s = hs.load(sPath.as_posix())
>>> print('spectra series data shape = {} and should be == (1, 2048)'.format(s.data.shape))
```

### CODE REVIEW

**Comment by ericpre** [comment]
@ercius, could you please review https://github.com/ercius/hyperspy/pull/1 and merge it if you are happy with the changes?

**Comment by ercius** [comment]
This looks good to me. Ill merge it.

**Comment by francisco-dlp** [comment]
This looks good to me except for the new way of dealing with the missing data. Previously it kept the original dimensions and filled the array with nans or zeros depending on the dtype. Now the array is cropped and/or squeezed. I think that this can lead to issues, for example, when trying to load and stack a number of files that should have the same dimensions. If they contain invalid data because something went wrong during acquisition that stacking operations will fail. Wouldn't it be better to add this new behaviour as an option that could be ``False`` by default?

**Comment by ericpre** [comment]
> This looks good to me except for the new way of dealing with the missing data. Previously it kept the original dimensions and filled the array with nans or zeros depending on the dtype. Now the array is cropped and/or squeezed. I think that this can lead to issues, for example, when trying to load and stack a number of files that should have the same dimensions. If they contain invalid data because something went wrong during acquisition that stacking operations will fail. Wouldn't it be better to add this new behaviour as an option that could be False by default?

Yes, it makes sense, this is now done with a default behaviour set to load only the valid data. I think this is the most common use case, particularly when acquiring data in "preview" mode it can save creating unnecessarily large dataset.

**Comment by ercius** [comment]
I agree with this. Many users acquire data in 'preview' mode with a large
series size. There should be the ability to turn it off, but only loading
valid data should the default behavior.

**Comment by francisco-dlp** [comment]
@ercius, the thing is that we cannot change the default behaviour in a patch or minor version. That's way I suggest to keep the default as it was.

**Comment by ericpre** [comment]
OK, default value of `only_valid_data` is changed to False with a mention that this default value will be changed to True in 2.0.

**Pull request merged**
