### PR TITLE
Fix #3361 `plot_images` axes ticks

### LINKED ISSUE #3361: Inconsistent axes ticks with Signal2D.plot and plot_images
#### Describe the bug
When plotting a signal using `plot_images`, the axis ticks and scales are different than using `Signal2D.plot`. 
`Signal2D.plot` has the centers of the pixels as the ticks, whereas `plot_images` uses the edges.
Furthermore, for an axis with negative scale, the ticks gets flipped in `plot_images`. This would be fine for me, if the data was also flipped.

#### To Reproduce
```python
from hyperspy.axes import UniformDataAxis
from hyperspy.signals import Signal2D
from hyperspy.utils.plot import plot_images
import numpy as np

data = np.random.random((4,4))

positive_axis = UniformDataAxis(scale= 1, size=4, name="positive", units="px")
negative_axis = UniformDataAxis(scale=-1, size=4, name="negative", units="px")

s = Signal2D(data, axes=[positive_axis, negative_axis])

plot_images([s], label=["plot_images"])
s.plot(axes_ticks=True)
```
bilde
bilde

#### Expected behavior
Both outputs should look identical

#### Python environment:
 - HyperSpy version: 2.0.1
 - Python version: 3.12

#### Additional context
Add any other context about the problem here. If necessary, add screenshots to help explain your problem.

### PR DESCRIPTION
**Pull request by viljarjf**
### Description of the change
Fixes #3361 by changing the extent of the image plots in `hyperspy.utils.plot_images` to be consistent with `Signal2D.plot`

### Progress of the PR
- [x] Change implemented (can be split into several points),
- [x] Fix any failing image tests
- [ ] update docstring (if appropriate),
- [ ] update user guide (if appropriate),
- [x] add an changelog entry in the `upcoming_changes` folder (see [`upcoming_changes/README.rst`](https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/upcoming_changes/README.rst)),
- [x] Check formatting changelog entry in the `readthedocs` doc build of this PR (link in github checks)
- [x] add tests,
- [x] ready for review.

### Minimal example of the bug fix or the new feature
```python
from hyperspy.axes import UniformDataAxis
from hyperspy.signals import Signal2D
from hyperspy.utils.plot import plot_images
import numpy as np

data = np.random.random((4,4))

positive_axis = UniformDataAxis(scale= 1, size=4, name="positive", units="px")
negative_axis = UniformDataAxis(scale=-1, size=4, name="negative", units="px")

s = Signal2D(data, axes=[positive_axis, negative_axis])

plot_images([s], label=["plot_images"])
s.plot(axes_ticks=True)
# Axes ticks should be identical
```
bilde
bilde

### CODE REVIEW

**Comment by viljarjf** [comment]
I need some help with generating new images to make the tests pass. I am able to generate them with `pytest --mpl-generate-path=hyperspy/tests/drawing/plot_signal2d`, and I could remove the ones which did not belong in that folder with `git clean -f`, but now some of the images are completely different. `test_plot_autoscale.png` used to be a 2D viridis image, but is now a red "Two gaussians signal" lineplot. Clearly, I am doing something wrong

**Comment by ericpre** [comment]
There are several tests from different test files with `test_plot_autoscale` in the name, maybe there is a mix up between these?

What I do usually to update a few test images, I run the test, check that I am happy with the new one and use it to overwrite the baseline (rename the file and copy to the right folder).

**Comment by viljarjf** [comment]
It seems the text in the images are shifted by a pixel or two for the newly generated images. Has something like this happened before?

**Comment by ericpre** [comment]
@viljarjf, which version of matplotlib are you using? It needs to be the same version as defined in https://github.com/hyperspy/hyperspy/blob/5816c40412725aa6a836d6f05f3c47ea6aae8d85/conda_environment_dev.yml#L7

This is mentioned in https://hyperspy.org/hyperspy-doc/dev/dev_guide/testing.html#plot-testing but not very visible... This should be improved in https://github.com/hyperspy/hyperspy/pull/3365.

**Comment by viljarjf** [comment]
Thank you @ericpre, that seems to have been the issue

**Review by ericpre — APPROVED** [review]
This is good! I added a test to increase the coverage for the case of plotting images with non-uniform axis.

**Pull request merged**
