### PR TITLE
Tidy up exspy

### PR DESCRIPTION
**Pull request by ericpre**
Follow up of #3202 and https://github.com/hyperspy/exspy.

### Progress of the PR
- [x] Remove exspy folder,
- [x] fix loading GUI toolkey when exspy is not installed,
- [x] fix test requiring `exspy`,
- [n/a] update docstring (if appropriate),
- [n/a] update user guide (if appropriate),
- [n/a] add an changelog entry in the `upcoming_changes` folder (see [`upcoming_changes/README.rst`](https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/upcoming_changes/README.rst)),
- [n/a] Check formatting changelog entry in the `readthedocs` doc build of this PR (link in github checks)
- [x] add tests,
- [x] ready for review.

### CODE REVIEW

**Comment by ericpre** [comment]
@CSSFrancis, when you get a chance, can you review this PR please? Then we can rebase the last few PRs and make a rc release?

**Review by CSSFrancis — COMMENTED** [review]
@ericpre the changes all look good to me but  is there a reason exspy is not a requirement to run the test suite? There are still couple of tests with will import or skip exspy and those are not currently tested here.

**Comment by ericpre** [comment]
I think that this should be test by https://github.com/hyperspy/hyperspy/actions/workflows/tests_extension.yml, I will update this workshop accordingly.

**Comment by ericpre** [comment]
> I think that this should be test by https://github.com/hyperspy/hyperspy/actions/workflows/tests_extension.yml, I will update this workshop accordingly.

Actually, this is incorrect, the integration test workflow tests run the test suite of the extension and doesn't run the test suite of hyperspy. At the same time, the test suite of hyperspy shouldn't depends on extension, so it may be better to move these tests to `exspy`?

**Comment by ericpre** [comment]
In any case, this will be tested daily in https://github.com/hyperspy/hyperspy-extensions-list/actions.

**Comment by CSSFrancis** [comment]
> Actually, this is incorrect, the integration test workflow tests run the test suite of the extension and doesn't run the test suite of hyperspy. At the same time, the test suite of hyperspy shouldn't depends on extension, so it may be better to move these tests to `exspy`?

I think for now this is fine!  As long as they are tested somewhere we can always go back and move the tests later.

**Review by CSSFrancis — APPROVED** [review]

**Pull request merged**
