### PR TITLE
Allow specifying of `cmap` when plotting decomposition factors

### PR DESCRIPTION
**Pull request by bm424**
For some reason the `cmap` parameter for `plot_decomposition_factors` wasn't there, despite being in the documentation. I can't think of any good reason for this so here's a quick fix.

### CODE REVIEW

**Comment by francisco-dlp** [comment]
Thanks, it's fine to merge, but, could you resubmit to next_patch?

**Comment by to266** [comment]
This merges a bunch of other things as well - you'll have to cherry-pick the commit on the new base, or something...

**Comment by thomasaarholt** [comment]
If you don't know how to do that, it's probably easier just to copy the code you changed, open a new branch off `hyperspy:RELEASE_next_patch`, paste the changes there and submit a new PR.

**Comment by francisco-dlp** [comment]
Merged manually, thanks!

**Pull request closed without merging**
