### PR TITLE
DOCENH: Added installation instructions specific to Arch Linux to installation user_guide page

### PR DESCRIPTION
**Pull request by jat255**
Added a section explaining which packages are needed to get up to speed with hyperspy in Arch Linux (mostly for my own reference, but should be useful for others, as well).

### CODE REVIEW

**Comment by to266** [comment]
Hi,

I myself use anaconda so I haven't tested these (let me know if I should), however a couple of things I noticed are (correct me if I'm wrong):
1. `ipython` is just a python3 implementation of ipython (and we currently don't use python3 in hyperspy at all). `ipython2` should be enough I think.
2. `python-traits` package does not exist in either the official repos or AUR
3. `pandas` package (while extremely useful) is not actually a requirement for hyperspy, nor is it used anywhere in the code
4. are you sure that you specifically need to specify all of the following packages, when they should just be installed as dependencies of `ipython2`? (`python2-jinja`, `python2-pygments`, `python2-pyzmq`, `python2-tornado`, `python2-sip`, maybe some others..?)

**Comment by jat255** [comment]
Hi Tomas, thanks for the comments.

1. You're correct about `ipython` vs `ipython2`. I've removed this one.
2. You're also correct about `python-traits`. It was a typo when I was copy/pasting. `python2-traits` is all that's needed.
3. `pandas` is pulled in as a dependency of `python2-statsmodels`.
4. If you want to have functionality of the notebook and qtconsole, then yes, these packages are needed. They are all "optional" dependencies of `ipython2`, so they're not pulled in by default.

Here is a detailed accounting of each package:
```
Package						Required by
----------------			--------------
python2 					hyperspy
python2-numpy				hyperspy
python2-matplotlib			hyperspy
python2-pip 				hyperspy (for installation)
python2-traits 				hyperspy
python2-traitsui 			hyperspy
python2-h5py 				hyperspy
python2-scikit-learn		hyperspy
python2-nose 				hyperspy
python2-statsmodels 		hyperspy
python2-pillow 				python2-matplotlib (optional for tiff export)		
python2-pyqt4 				python2-matplotlib
python2-pyqt5 				python2-matplotlib
python2-scipy 				python2-statsmodels and python2-scikit-learn
python2-pandas				python2-statsmodels
python2-setuptools			python2-pip (and others)
									
ipython2					hyperspy
python2-jinja 				ipython2 (for nb)
python2-pyzmq 				ipython2 (for nb and qtConsole)
python2-pyqt4 				ipython2 (qtConsole)
python2-tornado 			ipython2 (for nb)
python2-sip 				ipython2 (for qtConsole)
python2-pygments			ipython2 (for qtConsole)
```

I would suggest that in the case that some requirements/dependencies are changed in the packaging, we should include this entire list in the documentation. It doesn't really change the number of packages that are installed, and I don't think the end-user will really mind.

I've also added a way to install from a list of packages that I've added to the `doc` folder.

**Comment by to266** [comment]
Cool, thanks for clarification!

Perhaps somewhat unrelated, but have you considered creating an AUR package for hyperspy? I thought about it before, but was probably the only archlinux user of hyperspy. Now, however, it might be useful.. Probably not for a developer, but at least for a "bleeding edge" user.

So I guess I will try to write it, and link it here at some point (either the github link or the complete package) once it's not just an idea. Obviously if you start first, I'll just contribute :)

**Comment by jat255** [comment]
I think that's a great idea! That way it could be up to date with the latest commits to master, for instance. 

I have never created an AUR package though, so I'd be happy to let you take the lead on that one.

**Comment by to266** [comment]
Hi,

can you please test it? Thanks :)

https://aur.archlinux.org/packages/hyperspy-git/

**Comment by jat255** [comment]
I just tested this out on a fresh VM without any hyperspy packages installed, and it worked like a charm! Thanks for making it!

**Pull request merged**
