### PR TITLE
Fix deprecation warning

### PR DESCRIPTION
**Pull request by ericpre**
### Progress of the PR
- [x] Fix DeprecationWarning docstring,
- [x] Fix `binned` VisibleDeprecationWarning when running the test suite (save a new file or catch warning),
- [x] Fix `_map_iterate` VisibleDeprecationWarning when running the test suite,
- [x] ready for review.

DeprecationWarning docstring:
```python
../_components/pes_voigt.py:87
  /home/eric/Dev/hyperspy/hyperspy/_components/pes_voigt.py:87: DeprecationWarning: invalid escape sequence \c
    """This is the legacy Voigt profile component dedicated to photoemission

../_components/pes_voigt.py:161
  /home/eric/Dev/hyperspy/hyperspy/_components/pes_voigt.py:161: DeprecationWarning: invalid escape sequence \c
    """ Voigt component for photoemission spectroscopy data analysis.
```

binned` VisibleDeprecationWarning:
```python
hyperspy/tests/component/test_component_print_current.py: 16 warnings
hyperspy/tests/drawing/test_plot_markers.py: 7 warnings
hyperspy/tests/drawing/test_figure.py: 1 warning
hyperspy/tests/drawing/test_plot_model.py: 2 warnings
hyperspy/tests/drawing/test_plot_signal2d.py: 2 warnings
hyperspy/tests/drawing/test_plot_signal_tools.py: 1 warning
hyperspy/tests/io/test_hdf5.py: 9 warnings
hyperspy/tests/io/test_nexus_hdf.py: 22 warnings
hyperspy/tests/model/test_edsmodel.py: 2 warnings
hyperspy/tests/signals/test_eds_sem.py: 2 warnings
hyperspy/tests/signals/test_find_peaks1D_ohaver.py: 4 warnings
hyperspy/tests/signals/test_eels.py: 31 warnings
hyperspy/tests/signals/test_hologram_image_statistics.py: 8 warnings
hyperspy/tests/signals/test_eds_tem.py: 1 warning
  /home/eric/Dev/hyperspy/hyperspy/misc/utils.py:493: VisibleDeprecationWarning: Use of the `binned` attribute in metadata is going to be deprecated in v2.0. Set the `axis.is_binned` attribute instead. 
    warnings.warn('Use of the `binned` attribute in metadata is '

hyperspy/tests/component/test_component_print_current.py: 16 warnings
hyperspy/tests/drawing/test_plot_markers.py: 7 warnings
hyperspy/tests/drawing/test_figure.py: 1 warning
hyperspy/tests/drawing/test_plot_model.py: 2 warnings
hyperspy/tests/drawing/test_plot_signal2d.py: 2 warnings
hyperspy/tests/drawing/test_plot_signal_tools.py: 1 warning
hyperspy/tests/io/test_hdf5.py: 4 warnings
hyperspy/tests/io/test_nexus_hdf.py: 22 warnings
hyperspy/tests/model/test_edsmodel.py: 2 warnings
hyperspy/tests/signals/test_eds_sem.py: 2 warnings
hyperspy/tests/signals/test_find_peaks1D_ohaver.py: 4 warnings
hyperspy/tests/signals/test_eels.py: 16 warnings
hyperspy/tests/signals/test_hologram_image_statistics.py: 8 warnings
hyperspy/tests/signals/test_eds_tem.py: 1 warning
  /home/eric/Dev/hyperspy/hyperspy/io.py:516: UserWarning: Loading old file version. The binned attribute has been moved from metadata.Signal to axis.is_binned. Setting this attribute for all signal axes instead.
    warnings.warn('Loading old file version. The binned attribute '
```

`_map_iterate` VisibleDeprecationWarning:
```python
hyperspy/tests/signals/test_map_method.py::TestLazyMap::test_map_iterate_array
  /home/eric/Dev/hyperspy/hyperspy/_signals/lazy.py:600: VisibleDeprecationWarning: Passing arrays as keyword arguments can be ambigous. This is deprecated and will be removed in HyperSpy 2.0. Pass signal instances instead.
```

### CODE REVIEW

**Comment by francisco-dlp** [comment]
I think that it would be good to keep the old hdf5 files to make sure that we don't break opening them in the future. The same goes for ``binned``: there must be thousand of files with ``binned`` in metadata in the wild, so it'll be good to keep it in the test files to make sure that we handle them properly.

**Comment by ericpre** [comment]
I have kept some of the old file to make sure we can still open them, but I agree that it would be better to keep all old files, because there are most likely to be overlooked than more recent file version - even if normally, when changing file specification, we would make sure that the old one still work!

**Comment by ericpre** [comment]
There are two eels files, I had to update, because `binned` is also in the `original_metadata` and it doesn't play well with `pytest.warns`.

**Review by jlaehne — APPROVED** [review]

**Comment by jlaehne** [comment]
LGTM

**Pull request merged**
