### PR TITLE
Fix fei tests

### PR DESCRIPTION
**Pull request by francisco-dlp**
Fix the name of single navigation axis that was sometimes set to ``y`` instead of ``x``. Note that this does not implement setting the axis name to ``Position`` for oblique scan as proposed by @ericpre  in #1414.

(This branches from #1413, for a clean diff see last commit.)

### CODE REVIEW

**Comment by ericpre** [comment]
Yes, it does the job, without complicating the code!

**Comment by to266** [comment]
This needs a rebase/merge of the original pytest branch. Actually any reason why this is a patch, whereas #1413 goes to minor? Don't we want to patch the tests and then "trickle down" to minor/major?

**Comment by francisco-dlp** [comment]
Sorry, I mislabeled it.

**Comment by to266** [comment]
...Is there a way to force github to refresh the changes? Maybe you could rebase this on next_minor in order to show a clean diff?

**Comment by francisco-dlp** [comment]
Only the label was wrong, I branched it from #1413. The diff will be cleaner was that one gets merged.

**Comment by to266** [comment]
I merged #1413 before the last comment and hoped so too, but there we go.

**Comment by francisco-dlp** [comment]
Merging Rnm into it did it.

**Pull request merged**
