### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by francisco-dlp**

### CODE REVIEW

**Comment by ericpre** [comment]
It looks good so far. It does two build because of one "on branch" and one "on PR", but this is normal.

Shall we close #2363 and merge this one? If so, better to be merged into `RnP` instead of `RnM`.

**Comment by francisco-dlp** [comment]
I suggest you merge this one in #2363 and close this one.

**Comment by ericpre** [comment]
Since this branch is based on `RnM`, I have updated #2363 to be able to merge it in `RnP`.

**Comment by ericpre** [comment]
Done in #2363.

**Pull request closed without merging**
