### PR TITLE
some typos and a suggestion or two

### PR DESCRIPTION
**Pull request by mwalls**
I've put the note I suggested about  in issue #1628 about binning in the general fitting part. It is not specific to Samfire. I have not changed the Samfire part. Not sure if Tomas would prefer to do it. In the change about bounded fitting, I would have put a link to the table, instead of saying "see above", but not sure how to.

### CODE REVIEW

**Comment by francisco-dlp** [comment]
@mwalls, I have just added the link to the table as you wanted in your own branch. To update your local branch:

```
git pull

```

If you are happy with it I am happy to merge it. Otherwise, feel free to improve it.

**Comment by mwalls** [comment]
OK thanks. A long time since I did "git pull" so can't remember where to do it from, but go ahead!

**Comment by francisco-dlp** [comment]
From the same place where you do "git push".

**Comment by francisco-dlp** [comment]
Thanks!

**Comment by mwalls** [comment]
I don't do "git push". Or haven't for ages. To propose my changes I push a "create pull request" button on the site where I'm now typing. (Github). I don't see a git pull button. I tried doing it in a terminal called gitbash but is told me to f off.

**Comment by francisco-dlp** [comment]
That's smart. In the web interface there is no need to git pull. In case that you need to get back to git again, down here people seem to like using [GitKraken](https://www.gitkraken.com/) these days.

**Comment by mwalls** [comment]
Can"t keep up! Already got Git, gitbash, github, githup desktop and god knows what else...
Never mind.

**Pull request merged**
