### PR TITLE
fix problem with EELS background subraction

### PR DESCRIPTION
**Pull request by mwalls**
There is currently a problem when fast =False. The signal range has to be put back to the full range to create the model across the whole range.

### CODE REVIEW

**Comment by thomasaarholt** [comment]
Could you include a minimum working example? It isn't entirely clear to me when fast=False is a problem.

**Comment by mwalls** [comment]
I gave some in issue #1786 a few months ago. The background to subtract was sometimes not extrapolated beyond the fitting region when fast = False

**Comment by mwalls** [comment]
Magnus had also come across it before. I noticed it first when trying to run his EELS analysis tutorial from the site. For a while we thought the fitting routine was starting from crazy values of A and r, but it turns out it's the subtraction of the background that is not working properly. I think it's that when you create the signal to be subtracted using `model.as_signal(..)` (line 1030 in the original code) you should have set all the "channel switches" to True (reset_signal_range seems to do this) . Otherwise the model is only converted to a signal for those which are true to begin with, and those are just the ones that are included in `set_signal_range`. Why the current code actually works randomly for some lines in the line-spectrum is still a mystery to me. 
Hope this is a bit clearer. Thanks for any comments!

**Comment by magnunor** [comment]
Yeah, I often get this during workshops, and it is really annoying. 

See https://github.com/hyperspy/hyperspy/issues/1728 for a way of replicating it.

**Comment by thomasaarholt** [comment]
Looking at the file change you've done, I realise the problem.

Maybe a better solution would be to get the signal range the model currently has, and then set the signal range to those values after fitting, instead of resetting it?

**Edit:**
Looking at the [method](https://github.com/hyperspy/hyperspy/blob/9e939d848da387c0415d8543fa5966a6a36268f2/hyperspy/models/model1d.py#L461), it would take a bit more effort to implement.

There exists no record of the signal_range previously set, so even if one created a `m.get_signal_range()`, there's currently nowhere to get it from.

Two options I see:
(A): leave it as it is. 
(B): create a property `m._signal_range` which holds the current signal range (default `(None, None)`), then update `m.reset_signal_range()` and `m.set_signal_range` to respect it. Finally create a `m.get_signal_range()`, and change PR to:

```python
if not fast:
    current_signal_range = model.get_signal_range()
    model.set_signal_range(signal_range[0], signal_range[1])
    model.multifit(show_progressbar=show_progressbar)
    model.set_signal_range(current_signal_range)
```

**Comment by mwalls** [comment]
Not sure I follow you. My understanding is that line 1028 sets the range over which to fit the background. This is of course a limited range before the edge(s). So far so good. The problem is exactly that the signal range used to make the new signal to be subtracted is then only that short range. The rest of the new signal created by the command 'model.as_signal' is filled with nans, not the extrapolated part of the fitted power law function, which is what we really want.  We need all the channels to be included in the new signal, not just the fitted region ones?

**Comment by thomasaarholt** [comment]
Okay, then I misunderstood the issue.

**Comment by francisco-dlp** [comment]
LGTM, thanks!

**Comment by francisco-dlp** [comment]
Merged manually to Rnp because it branched out from Rnm.

**Pull request merged**
