### PR TITLE
Add handling for CL metadata in DM reader

### PR DESCRIPTION
**Pull request by jlaehne**
### Description of the change
Added import of various CL specific metadata fields to DM reader

### Progress of the PR
- [X] Change implemented (can be split into several points),
- [x] update docstring (if appropriate),
- [x] update user guide (if appropriate),
- [x] add tests,
- [x] ready for review.

### CODE REVIEW

**Comment by jlaehne** [comment]
Note that #2095 touches this PR. For the moment, I have not implemented microscope specific metadata under an `SEM` node, but simply set the `acquisition_mode` parameter to `SEM` instead of `STEM/TEM` under the `TEM` node. Current metadata structure would require a separate node, but I think the proposal from #2095 would make sense and would result in the metadata going one level up or the `TEM` being renamed to a more general `EM` to separate it from detector specific information under `Acquisition_instrument`.

**Comment by jlaehne** [comment]
How do I get a `codecov` for this PR?

**Comment by ericpre** [comment]
`codecov` comes from a build on travis and I am afraid that it is not working well at the moment. Until yesterday, there was a failure with latest h5py version and as of this morning there is still a failure introduced in #2437.
On top of that, travis significantly reduced their capacity of their free tier offer recently and there is now a massive queue: https://www.traviscistatus.com

**Comment by ericpre** [comment]
@jlaehne, the coverage is working now!

**Comment by jlaehne** [comment]
Mac build was aborted, did not fail.

**Pull request merged**
