### PR TITLE
Fix plotting test for matplotlib 3 

### PR DESCRIPTION
**Pull request by ericpre**
Recent changes in matplotlib 3 break plotting test and matplotlib was pinned to 2.2.3 for testing. Follow up of #2065.

### Progress of the PR
- [x] Remove broken `mpl_cleanup`,
- [x] now use `mpl_test_settings` autuse fixture for testing,
- [x] update tests,
- [x] update baseline images (small changes in bounding box calculation in matplotlib),
- [x] update developer guide,
- [x] ready for review.

### CODE REVIEW

**Comment by francisco-dlp** [comment]
Looks good. Any idea of why appveyor is unhappy?

**Comment by ericpre** [comment]
I don't know, the failure are unrelated to this PR... Once #2102 passes CI and is merged, I can slove the merge conflict in the appveyor yml and see if it was just a temporary failure or not.

**Comment by francisco-dlp** [comment]
Merging since the errors are unrelated to the PR.

**Comment by ericpre** [comment]
I gave a go at improving the English US locale issue handling...

**Comment by francisco-dlp** [comment]
What's the point of the latest commit? When did we start depending on pywinpty?

**Comment by ericpre** [comment]
This comes from:
```
Collecting pywinpty>=0.5; os_name == "nt" (from terminado>=0.8.1->notebook>=4.4.1->widgetsnbextension~=3.4.0->ipywidgets>=6.0->hyperspy_gui_ipywidgets>=1.1.0->hyperspy==1.4.2.dev0)
```

`pip install .[dev]` install optional dependencies, including the GUI ones. We should possibly not install the GUIs optional dependencies and instead it would be better to test their installation on windows in their respective repositories.

**Comment by francisco-dlp** [comment]
I see, but that looks like a workaround for an external issue. I suggest  instead to:

* Report the issue to the pywinpty developers (they may like to provide wheels in pypi)
* Revert the latest commit and merge, since fixing this external issue is unrelated to this PR

**Comment by ericpre** [comment]
I reverted the last commit and removed installation of GUIs.
pywinpty wheels issue has already been reported, https://github.com/spyder-ide/pywinpty/issues/116.

**Pull request merged**
