### PR TITLE
fix goodness_test updating in workers

### PR DESCRIPTION
**Pull request by to266**
Fixes https://github.com/hyperspy/hyperspy/issues/1288

### CODE REVIEW

**Comment by francisco-dlp** [comment]
Requires updating with current RELEASE_next_patch

**Comment by to266** [comment]
...Actually it seems the required fix was added with some earlier PR, so this one does not add anything.

Or is it just my github bugged?

**Comment by francisco-dlp** [comment]
I suggest merging anyway for the record (and the fun of merging an empty PR).

**Comment by to266** [comment]
Have fun!

**Pull request merged**
