### PR TITLE
Add extra_requires to setup.py

### PR DESCRIPTION
**Pull request by francisco-dlp**
Make it easy to install extra dependencies. Currently three options are available:

* bcf: bcf reader dependencies.
* learning: machine learning features.
* gui-jupyter: jupyter widgets
* all: install all extra dependencies.

### CODE REVIEW

**Comment by francisco-dlp** [comment]
Is this ok?

**Comment by to266** [comment]
...I assume you tested that it actually does this?

**Comment by francisco-dlp** [comment]
It does it for me, but the point of reviewing is not trusting the biased author ;)

**Comment by to266** [comment]
The `[all]` option fails for me:
```bash
(testenv) ~/d/hyperspy ❯❯❯ pip install -e ".[all]"         ⏎ remotes/francisco/extra_requires ✭ ◼
Obtaining file:///home/to266/dev/hyperspy
Requirement already satisfied: scipy in /home/to266/anaconda3/envs/testenv/lib/python3.5/site-packages (from hyperspy===1.1.2-git-52-gf3f0212c)
Requirement already satisfied: ipython>=2.0 in /home/to266/anaconda3/envs/testenv/lib/python3.5/site-packages (from hyperspy===1.1.2-git-52-gf3f0212c)
Requirement already satisfied: matplotlib>=1.2 in /home/to266/anaconda3/envs/testenv/lib/python3.5/site-packages (from hyperspy===1.1.2-git-52-gf3f0212c)
Requirement already satisfied: numpy>=1.10 in /home/to266/anaconda3/envs/testenv/lib/python3.5/site-packages (from hyperspy===1.1.2-git-52-gf3f0212c)
Requirement already satisfied: traits>=4.5.0 in /home/to266/anaconda3/envs/testenv/lib/python3.5/site-packages (from hyperspy===1.1.2-git-52-gf3f0212c)
Requirement already satisfied: traitsui>=5.0 in /home/to266/anaconda3/envs/testenv/lib/python3.5/site-packages (from hyperspy===1.1.2-git-52-gf3f0212c)
Requirement already satisfied: natsort in /home/to266/anaconda3/envs/testenv/lib/python3.5/site-packages (from hyperspy===1.1.2-git-52-gf3f0212c)
Requirement already satisfied: requests in /home/to266/anaconda3/envs/testenv/lib/python3.5/site-packages (from hyperspy===1.1.2-git-52-gf3f0212c)
Requirement already satisfied: tqdm in /home/to266/anaconda3/envs/testenv/lib/python3.5/site-packages (from hyperspy===1.1.2-git-52-gf3f0212c)
Requirement already satisfied: sympy in /home/to266/anaconda3/envs/testenv/lib/python3.5/site-packages (from hyperspy===1.1.2-git-52-gf3f0212c)
Requirement already satisfied: dill in /home/to266/anaconda3/envs/testenv/lib/python3.5/site-packages (from hyperspy===1.1.2-git-52-gf3f0212c)
Requirement already satisfied: h5py in /home/to266/anaconda3/envs/testenv/lib/python3.5/site-packages (from hyperspy===1.1.2-git-52-gf3f0212c)
Requirement already satisfied: python-dateutil in /home/to266/anaconda3/envs/testenv/lib/python3.5/site-packages (from hyperspy===1.1.2-git-52-gf3f0212c)
Requirement already satisfied: ipyparallel in /home/to266/anaconda3/envs/testenv/lib/python3.5/site-packages (from hyperspy===1.1.2-git-52-gf3f0212c)
Requirement already satisfied: scikit-image in /home/to266/anaconda3/envs/testenv/lib/python3.5/site-packages (from hyperspy===1.1.2-git-52-gf3f0212c)
Collecting lxml (from hyperspy===1.1.2-git-52-gf3f0212c)
  Using cached lxml-3.7.2-cp35-cp35m-manylinux1_x86_64.whl
Collecting scikit-learn (from hyperspy===1.1.2-git-52-gf3f0212c)
  Using cached scikit_learn-0.18.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting i (from hyperspy===1.1.2-git-52-gf3f0212c)
  Could not find a version that satisfies the requirement i (from hyperspy===1.1.2-git-52-gf3f0212c) (from versions: )
No matching distribution found for i (from hyperspy===1.1.2-git-52-gf3f0212c)
```

**Comment by francisco-dlp** [comment]
You see ;) —fixed!

**Pull request merged**
