### PR TITLE
Powerlaw naming

### PR DESCRIPTION
**Pull request by jlaehne**
Implements change in Naming of PowerLaw component within background removal tool suggested in #2176. Removed space in the name when referring to the PowerLaw component. Checks for the two variations `PowerLaw` and `Power Law` are left for backwards compatibility.

### Progress of the PR
- [X] Change implemented (can be split into several points),
- [X] ready for review.

### CODE REVIEW

**Comment by ericpre** [comment]
This is a detail but I think prefer to have "Power law" in the GUI rather than "PowerLaw":

image

I guess it should be possible to set `PowerLaw` as parameter of `remove_background`. What is displayed in the GUI is defined in the [`t.Enum`](https://github.com/hyperspy/hyperspy/blob/4cd8e81d95a286c587bff4d12568f088b3dd5481/hyperspy/signal_tools.py#L647).

**Comment by francisco-dlp** [comment]
@ericpre, I propose to merge this since fixing the name displayed in the widgets is a different issue. Personally, I think that, even though "Power law" does look better, complexifying the code just for that may not be worth it.

**Comment by jlaehne** [comment]
To avoid confusions, as pointed out by @thomasaarholt, I think it would be best to also use the real component name in the GUI. But, I guess, in the end, what is displayed is a matter of taste.

**Comment by ericpre** [comment]
This is a simple change (2 lines with a if statement) to get the spelling correct, see https://github.com/ericpre/hyperspy/commit/919484476ba282d454ff768fca65d99f3b883409. Users using the GUIs and not familiar with hyperpsy components may just think this is a typo.

**Comment by jlaehne** [comment]
Well, we have a parallel discussion between here and #2176. 

What @ericpre suggests here is to use `Power law` (by the way introducing a third spelling to the `Power Law` used so far) in the function and having `PowerLaw` as an alias for the command line.

In #2176, @thomasaarholt and @francisco-dlp were aiming at completely of making `Power Law` an alias and completely removing it in future versions, at the expense of the spelling in the GUI.

**Comment by jlaehne** [comment]
As no one else commented, I implemented the changes suggested by @ericpre. 

While the background removal GUI now displays 'Power law', inline also 'Power Law' and 'PowerLaw' are accepted. That should make it fool proof in the usage.

**Comment by jlaehne** [comment]
Fixed merge conflicts and extended the Name handling concept to `SkewNormal` component.

**Comment by tjof2** [comment]
What's the status of this?

**Comment by jlaehne** [comment]
Should be ready, can you have a look @thomasaarholt and provide a review as you proposed this originally.

**Review by ericpre — CHANGES_REQUESTED** [review]
A more simple approach as done in #2307 (see https://github.com/ericpre/hyperspy/blob/82eed9b8374e7699e6f1103dff1d4c6c782a18c2/hyperspy/signal_tools.py#L1173) would be more robust and simple.

**Comment by ericpre** [comment]
Done in #2307.

**Comment by jlaehne** [comment]
This solution differed/went beyond #2307 in three aspects:
1. 'Power law' would be the correct spelling in the GUI not 'Power Law'
2. The naming should be consistent also for the new components SkewNormal and SplitVoigt
3. This implementation accepted the three aliases 'Power law', 'Power Law' and 'PowerLaw' in the CLI call of the `remove_background` function.

I have created a new PR #2465 that adds these three points (with #2307 this is much cleaner than the original) and also updates the documentation.

**Pull request closed without merging**
