### PR TITLE
Fix doc warning

### PR DESCRIPTION
**Pull request by ericpre**
### Progress of the PR
- [x] Fix many doc warning
- [x] doc build warning displayed as github annotation - see screenshot below,
- [x] improved navigation menu,
- [x] ready for review.

image

Warning before:
```
WARNING: missing attribute mentioned in :members: or __all__: module hyperspy, attribute api
/home/runner/work/hyperspy/hyperspy/hyperspy/_components/eels_cl_edge.py:docstring of hyperspy._components.eels_cl_edge.EELSCLEdge.fine_structure_active:1: WARNING: duplicate object description of hyperspy._components.eels_cl_edge.EELSCLEdge.fine_structure_active, other instance in api/hyperspy._components.eels_cl_edge, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/_components/eels_cl_edge.py:docstring of hyperspy._components.eels_cl_edge.EELSCLEdge.fine_structure_smoothing:1: WARNING: duplicate object description of hyperspy._components.eels_cl_edge.EELSCLEdge.fine_structure_smoothing, other instance in api/hyperspy._components.eels_cl_edge, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/_components/gaussian2d.py:docstring of hyperspy._components.gaussian2d.Gaussian2D.ellipticity:1: WARNING: duplicate object description of hyperspy._components.gaussian2d.Gaussian2D.ellipticity, other instance in api/hyperspy._components.gaussian2d, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/_components/gaussian2d.py:docstring of hyperspy._components.gaussian2d.Gaussian2D.rotation_angle_wrapped:1: WARNING: duplicate object description of hyperspy._components.gaussian2d.Gaussian2D.rotation_angle_wrapped, other instance in api/hyperspy._components.gaussian2d, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/_components/gaussian2d.py:docstring of hyperspy._components.gaussian2d.Gaussian2D.rotation_major_axis:1: WARNING: duplicate object description of hyperspy._components.gaussian2d.Gaussian2D.rotation_major_axis, other instance in api/hyperspy._components.gaussian2d, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/_components/gaussian2d.py:docstring of hyperspy._components.gaussian2d.Gaussian2D.sigma_major:1: WARNING: duplicate object description of hyperspy._components.gaussian2d.Gaussian2D.sigma_major, other instance in api/hyperspy._components.gaussian2d, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/_components/gaussian2d.py:docstring of hyperspy._components.gaussian2d.Gaussian2D.sigma_minor:1: WARNING: duplicate object description of hyperspy._components.gaussian2d.Gaussian2D.sigma_minor, other instance in api/hyperspy._components.gaussian2d, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/_signals/complex_signal2d.py:docstring of hyperspy._signals.complex_signal2d.Complex2Dmixin.plot:91: WARNING: Unexpected indentation.
/home/runner/work/hyperspy/hyperspy/hyperspy/_signals/eels.py:docstring of hyperspy._signals.eels.EELSSpectrum_mixin.kramers_kronig_analysis:39: WARNING: Definition list ends without a blank line; unexpected unindent.
/home/runner/work/hyperspy/hyperspy/hyperspy/_signals/signal2d.py:docstring of hyperspy._signals.signal2d.Signal2D.plot:78: WARNING: Unexpected indentation.
/home/runner/work/hyperspy/hyperspy/hyperspy/axes.py:docstring of hyperspy.axes.AxesManager.coordinates:1: WARNING: duplicate object description of hyperspy.axes.AxesManager.coordinates, other instance in api/hyperspy.axes, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/axes.py:docstring of hyperspy.axes.AxesManager.indices:1: WARNING: duplicate object description of hyperspy.axes.AxesManager.indices, other instance in api/hyperspy.axes, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/component.py:docstring of hyperspy.component.Parameter:55: WARNING: duplicate object description of hyperspy.component.Parameter.twin_inverse_function, other instance in api/hyperspy.component, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/component.py:docstring of hyperspy.component.Parameter.as_signal:1: WARNING: duplicate object description of hyperspy.component.Parameter.as_signal, other instance in api/hyperspy.component, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/component.py:docstring of hyperspy.component.Parameter.export:1: WARNING: duplicate object description of hyperspy.component.Parameter.export, other instance in api/hyperspy.component, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/component.py:docstring of hyperspy.component.Parameter.ext_bounded:1: WARNING: duplicate object description of hyperspy.component.Parameter.ext_bounded, other instance in api/hyperspy.component, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/component.py:docstring of hyperspy.component.Parameter.ext_force_positive:1: WARNING: duplicate object description of hyperspy.component.Parameter.ext_force_positive, other instance in api/hyperspy.component, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/component.py:docstring of hyperspy.component.Parameter.plot:1: WARNING: duplicate object description of hyperspy.component.Parameter.plot, other instance in api/hyperspy.component, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/component.py:docstring of hyperspy.component.Parameter.twin:1: WARNING: duplicate object description of hyperspy.component.Parameter.twin, other instance in api/hyperspy.component, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/component.py:docstring of hyperspy.component.Parameter.twin_function:1: WARNING: duplicate object description of hyperspy.component.Parameter.twin_function, other instance in api/hyperspy.component, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/component.py:docstring of hyperspy.component.Parameter.twin_function_expr:1: WARNING: duplicate object description of hyperspy.component.Parameter.twin_function_expr, other instance in api/hyperspy.component, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/component.py:docstring of hyperspy.component.Parameter.twin_inverse_function:1: WARNING: duplicate object description of hyperspy.component.Parameter.twin_inverse_function, other instance in api/hyperspy.component, use :noindex: for one of them
WARNING: autodoc: failed to import module 'conftest' from module 'hyperspy'; the following exception was raised:
No module named 'pytest'
/home/runner/work/hyperspy/hyperspy/hyperspy/drawing/marker.py:docstring of hyperspy.drawing.marker.MarkerBase.marker_properties:1: WARNING: duplicate object description of hyperspy.drawing.marker.MarkerBase.marker_properties, other instance in api/hyperspy.drawing.marker, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/drawing/signal1d.py:docstring of hyperspy.drawing.signal1d.Signal1DLine.line_properties:1: WARNING: duplicate object description of hyperspy.drawing.signal1d.Signal1DLine.line_properties, other instance in api/hyperspy.drawing.signal1d, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/drawing/signal1d.py:docstring of hyperspy.drawing.signal1d.Signal1DLine.set_line_properties:1: WARNING: duplicate object description of hyperspy.drawing.signal1d.Signal1DLine.set_line_properties, other instance in api/hyperspy.drawing.signal1d, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/drawing/signal1d.py:docstring of hyperspy.drawing.signal1d.Signal1DLine.type:1: WARNING: duplicate object description of hyperspy.drawing.signal1d.Signal1DLine.type, other instance in api/hyperspy.drawing.signal1d, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/drawing/signal1d.py:docstring of hyperspy.drawing.signal1d.Signal1DLine.update:4: WARNING: Unexpected section title.

Parameters:
-----------
/home/runner/work/hyperspy/hyperspy/hyperspy/drawing/widget.py:docstring of hyperspy.drawing.widget.ResizersMixin.resizers:1: WARNING: duplicate object description of hyperspy.drawing.widget.ResizersMixin.resizers, other instance in api/hyperspy.drawing.widget, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/io_plugins/bruker.py:docstring of hyperspy.io_plugins.bruker.SFS_reader.get_file:1: WARNING: duplicate object description of hyperspy.io_plugins.bruker.SFS_reader.get_file, other instance in api/hyperspy.io_plugins.bruker, use :noindex: for one of them
WARNING: autodoc: failed to import module 'mrcz' from module 'hyperspy.io_plugins'; the following exception was raised:
No module named 'mrcz'
/home/runner/work/hyperspy/hyperspy/hyperspy/io_plugins/nexus.py:docstring of hyperspy.io_plugins.nexus._fix_exclusion_keys:10: WARNING: Unexpected section title.

Parameter
---------
/home/runner/work/hyperspy/hyperspy/hyperspy/io_plugins/nexus.py:docstring of hyperspy.io_plugins.nexus._is_int:4: WARNING: Unexpected section title.

Parameter
---------
/home/runner/work/hyperspy/hyperspy/hyperspy/io_plugins/nexus.py:docstring of hyperspy.io_plugins.nexus._is_linear_axis:4: WARNING: Unexpected section title.

Parameter
---------
/home/runner/work/hyperspy/hyperspy/hyperspy/io_plugins/nexus.py:docstring of hyperspy.io_plugins.nexus._is_numeric_data:4: WARNING: Unexpected section title.

Parameter
---------
/home/runner/work/hyperspy/hyperspy/hyperspy/io_plugins/nexus.py:docstring of hyperspy.io_plugins.nexus._fix_exclusion_keys:6: WARNING: Unknown target name: "fix".
WARNING: autodoc: failed to import module 'usid_hdf5' from module 'hyperspy.io_plugins'; the following exception was raised:
No module named 'pyUSID'
/home/runner/work/hyperspy/hyperspy/hyperspy/misc/eels/electron_inelastic_mean_free_path.py:docstring of hyperspy.misc.eels.electron_inelastic_mean_free_path.iMFP_Iakoubovskii:4: WARNING: Unexpected section title.

Parameters:
-----------
/home/runner/work/hyperspy/hyperspy/hyperspy/misc/eels/electron_inelastic_mean_free_path.py:docstring of hyperspy.misc.eels.electron_inelastic_mean_free_path.iMFP_Iakoubovskii:11: WARNING: Unexpected section title.

Notes:
------
/home/runner/work/hyperspy/hyperspy/hyperspy/misc/eels/electron_inelastic_mean_free_path.py:docstring of hyperspy.misc.eels.electron_inelastic_mean_free_path.iMFP_Iakoubovskii:14: WARNING: Unexpected indentation.
/home/runner/work/hyperspy/hyperspy/hyperspy/misc/eels/electron_inelastic_mean_free_path.py:docstring of hyperspy.misc.eels.electron_inelastic_mean_free_path.iMFP_TPP2M:21: WARNING: Unexpected indentation.
/home/runner/work/hyperspy/hyperspy/hyperspy/misc/eels/electron_inelastic_mean_free_path.py:docstring of hyperspy.misc.eels.electron_inelastic_mean_free_path.iMFP_angular_correction:4: WARNING: Unexpected section title.

Parameters:
-----------
/home/runner/work/hyperspy/hyperspy/hyperspy/misc/eels/electron_inelastic_mean_free_path.py:docstring of hyperspy.misc.eels.electron_inelastic_mean_free_path.iMFP_angular_correction:13: WARNING: Unexpected section title.

Notes:
------
/home/runner/work/hyperspy/hyperspy/hyperspy/misc/eels/electron_inelastic_mean_free_path.py:docstring of hyperspy.misc.eels.electron_inelastic_mean_free_path.iMFP_angular_correction:16: WARNING: Unexpected indentation.
/home/runner/work/hyperspy/hyperspy/hyperspy/misc/eels/hartree_slater_gos.py:docstring of hyperspy.misc.eels.hartree_slater_gos.HartreeSlaterGOS.as_dictionary:1: WARNING: duplicate object description of hyperspy.misc.eels.hartree_slater_gos.HartreeSlaterGOS.as_dictionary, other instance in api/hyperspy.misc.eels.hartree_slater_gos, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/misc/eels/hartree_slater_gos.py:docstring of hyperspy.misc.eels.hartree_slater_gos.HartreeSlaterGOS.readgosfile:1: WARNING: duplicate object description of hyperspy.misc.eels.hartree_slater_gos.HartreeSlaterGOS.readgosfile, other instance in api/hyperspy.misc.eels.hartree_slater_gos, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/model.py:docstring of hyperspy.model.BaseModel.append:1: WARNING: duplicate object description of hyperspy.model.BaseModel.append, other instance in api/hyperspy.model, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/model.py:docstring of hyperspy.model.BaseModel.as_dictionary:1: WARNING: duplicate object description of hyperspy.model.BaseModel.as_dictionary, other instance in api/hyperspy.model, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/model.py:docstring of hyperspy.model.BaseModel.as_signal:1: WARNING: duplicate object description of hyperspy.model.BaseModel.as_signal, other instance in api/hyperspy.model, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/model.py:docstring of hyperspy.model.BaseModel.export_results:1: WARNING: duplicate object description of hyperspy.model.BaseModel.export_results, other instance in api/hyperspy.model, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/model.py:docstring of hyperspy.model.BaseModel.extend:1: WARNING: duplicate object description of hyperspy.model.BaseModel.extend, other instance in api/hyperspy.model, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/model.py:docstring of hyperspy.model.BaseModel.fetch_stored_values:1: WARNING: duplicate object description of hyperspy.model.BaseModel.fetch_stored_values, other instance in api/hyperspy.model, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/model.py:docstring of hyperspy.model.BaseModel.plot_results:1: WARNING: duplicate object description of hyperspy.model.BaseModel.plot_results, other instance in api/hyperspy.model, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/model.py:docstring of hyperspy.model.BaseModel.print_current_values:1: WARNING: duplicate object description of hyperspy.model.BaseModel.print_current_values, other instance in api/hyperspy.model, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/model.py:docstring of hyperspy.model.BaseModel.red_chisq:1: WARNING: duplicate object description of hyperspy.model.BaseModel.red_chisq, other instance in api/hyperspy.model, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/model.py:docstring of hyperspy.model.BaseModel.remove:1: WARNING: duplicate object description of hyperspy.model.BaseModel.remove, other instance in api/hyperspy.model, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/model.py:docstring of hyperspy.model.BaseModel.set_parameters_value:1: WARNING: duplicate object description of hyperspy.model.BaseModel.set_parameters_value, other instance in api/hyperspy.model, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/model.py:docstring of hyperspy.model.BaseModel.store_current_values:1: WARNING: duplicate object description of hyperspy.model.BaseModel.store_current_values, other instance in api/hyperspy.model, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/model.py:docstring of hyperspy.model.BaseModel.update_plot:1: WARNING: duplicate object description of hyperspy.model.BaseModel.update_plot, other instance in api/hyperspy.model, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/models/model1d.py:docstring of hyperspy.models.model1d.Model1D.append:1: WARNING: duplicate object description of hyperspy.models.model1d.Model1D.append, other instance in api/hyperspy.models.model1d, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/models/model1d.py:docstring of hyperspy.models.model1d.Model1D.fit_component:1: WARNING: duplicate object description of hyperspy.models.model1d.Model1D.fit_component, other instance in api/hyperspy.models.model1d, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/models/model1d.py:docstring of hyperspy.models.model1d.Model1D.plot:1: WARNING: duplicate object description of hyperspy.models.model1d.Model1D.plot, other instance in api/hyperspy.models.model1d, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/models/model1d.py:docstring of hyperspy.models.model1d.Model1D.remove:1: WARNING: duplicate object description of hyperspy.models.model1d.Model1D.remove, other instance in api/hyperspy.models.model1d, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/models/model1d.py:docstring of hyperspy.models.model1d.Model1D.signal:1: WARNING: duplicate object description of hyperspy.models.model1d.Model1D.signal, other instance in api/hyperspy.models.model1d, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/models/model2d.py:docstring of hyperspy.models.model2d.Model2D.signal:1: WARNING: duplicate object description of hyperspy.models.model2d.Model2D.signal, other instance in api/hyperspy.models.model2d, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/samfire.py:docstring of hyperspy.samfire.Samfire.active_strategy:1: WARNING: duplicate object description of hyperspy.samfire.Samfire.active_strategy, other instance in api/hyperspy.samfire, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/samfire.py:docstring of hyperspy.samfire.Samfire.append:1: WARNING: duplicate object description of hyperspy.samfire.Samfire.append, other instance in api/hyperspy.samfire, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/samfire.py:docstring of hyperspy.samfire.Samfire.backup:1: WARNING: duplicate object description of hyperspy.samfire.Samfire.backup, other instance in api/hyperspy.samfire, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/samfire.py:docstring of hyperspy.samfire.Samfire.change_strategy:1: WARNING: duplicate object description of hyperspy.samfire.Samfire.change_strategy, other instance in api/hyperspy.samfire, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/samfire.py:docstring of hyperspy.samfire.Samfire.extend:1: WARNING: duplicate object description of hyperspy.samfire.Samfire.extend, other instance in api/hyperspy.samfire, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/samfire.py:docstring of hyperspy.samfire.Samfire.generate_values:1: WARNING: duplicate object description of hyperspy.samfire.Samfire.generate_values, other instance in api/hyperspy.samfire, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/samfire.py:docstring of hyperspy.samfire.Samfire.log:1: WARNING: duplicate object description of hyperspy.samfire.Samfire.log, other instance in api/hyperspy.samfire, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/samfire.py:docstring of hyperspy.samfire.Samfire.optional_components:1: WARNING: duplicate object description of hyperspy.samfire.Samfire.optional_components, other instance in api/hyperspy.samfire, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/samfire.py:docstring of hyperspy.samfire.Samfire.plot:1: WARNING: duplicate object description of hyperspy.samfire.Samfire.plot, other instance in api/hyperspy.samfire, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/samfire.py:docstring of hyperspy.samfire.Samfire.plot_every:1: WARNING: duplicate object description of hyperspy.samfire.Samfire.plot_every, other instance in api/hyperspy.samfire, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/samfire.py:docstring of hyperspy.samfire.Samfire.pool:1: WARNING: duplicate object description of hyperspy.samfire.Samfire.pool, other instance in api/hyperspy.samfire, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/samfire.py:docstring of hyperspy.samfire.Samfire.refresh_database:1: WARNING: duplicate object description of hyperspy.samfire.Samfire.refresh_database, other instance in api/hyperspy.samfire, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/samfire.py:docstring of hyperspy.samfire.Samfire.remove:1: WARNING: duplicate object description of hyperspy.samfire.Samfire.remove, other instance in api/hyperspy.samfire, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/samfire.py:docstring of hyperspy.samfire.Samfire.save_every:1: WARNING: duplicate object description of hyperspy.samfire.Samfire.save_every, other instance in api/hyperspy.samfire, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/samfire.py:docstring of hyperspy.samfire.Samfire.start:1: WARNING: duplicate object description of hyperspy.samfire.Samfire.start, other instance in api/hyperspy.samfire, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/samfire.py:docstring of hyperspy.samfire.Samfire.stop:1: WARNING: duplicate object description of hyperspy.samfire.Samfire.stop, other instance in api/hyperspy.samfire, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/samfire.py:docstring of hyperspy.samfire.Samfire.update:1: WARNING: duplicate object description of hyperspy.samfire.Samfire.update, other instance in api/hyperspy.samfire, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/samfire.py:docstring of hyperspy.samfire.Samfire.backup:3: WARNING: Unknown target name: "backup".
/home/runner/work/hyperspy/hyperspy/hyperspy/samfire_utils/samfire_pool.py:docstring of hyperspy.samfire_utils.samfire_pool.SamfirePool.add_jobs:1: WARNING: duplicate object description of hyperspy.samfire_utils.samfire_pool.SamfirePool.add_jobs, other instance in api/hyperspy.samfire_utils.samfire_pool, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/samfire_utils/samfire_pool.py:docstring of hyperspy.samfire_utils.samfire_pool.SamfirePool.parse:1: WARNING: duplicate object description of hyperspy.samfire_utils.samfire_pool.SamfirePool.parse, other instance in api/hyperspy.samfire_utils.samfire_pool, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/samfire_utils/samfire_pool.py:docstring of hyperspy.samfire_utils.samfire_pool.SamfirePool.ping_workers:1: WARNING: duplicate object description of hyperspy.samfire_utils.samfire_pool.SamfirePool.ping_workers, other instance in api/hyperspy.samfire_utils.samfire_pool, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/samfire_utils/samfire_pool.py:docstring of hyperspy.samfire_utils.samfire_pool.SamfirePool.prepare_workers:1: WARNING: duplicate object description of hyperspy.samfire_utils.samfire_pool.SamfirePool.prepare_workers, other instance in api/hyperspy.samfire_utils.samfire_pool, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/samfire_utils/samfire_pool.py:docstring of hyperspy.samfire_utils.samfire_pool.SamfirePool.run:1: WARNING: duplicate object description of hyperspy.samfire_utils.samfire_pool.SamfirePool.run, other instance in api/hyperspy.samfire_utils.samfire_pool, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/samfire_utils/samfire_pool.py:docstring of hyperspy.samfire_utils.samfire_pool.SamfirePool.stop:1: WARNING: duplicate object description of hyperspy.samfire_utils.samfire_pool.SamfirePool.stop, other instance in api/hyperspy.samfire_utils.samfire_pool, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/samfire_utils/samfire_pool.py:docstring of hyperspy.samfire_utils.samfire_pool.SamfirePool.update_parameters:1: WARNING: duplicate object description of hyperspy.samfire_utils.samfire_pool.SamfirePool.update_parameters, other instance in api/hyperspy.samfire_utils.samfire_pool, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/signal.py:docstring of hyperspy.signal.MVATools.get_cluster_labels:4: WARNING: Title underline too short.

Parameters:
--------
/home/runner/work/hyperspy/hyperspy/hyperspy/signal.py:docstring of hyperspy.signal.MVATools.get_cluster_labels:4: WARNING: Unexpected section title.

Parameters:
--------
/home/runner/work/hyperspy/hyperspy/hyperspy/signal.py:docstring of hyperspy.signal.MVATools.get_cluster_signals:4: WARNING: Unexpected section title.

Parameter
---------
/home/runner/work/hyperspy/hyperspy/hyperspy/utils/parallel_pool.py:docstring of hyperspy.utils.parallel_pool.ParallelPool.has_pool:1: WARNING: duplicate object description of hyperspy.utils.parallel_pool.ParallelPool.has_pool, other instance in api/hyperspy.utils.parallel_pool, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/utils/parallel_pool.py:docstring of hyperspy.utils.parallel_pool.ParallelPool.is_ipyparallel:1: WARNING: duplicate object description of hyperspy.utils.parallel_pool.ParallelPool.is_ipyparallel, other instance in api/hyperspy.utils.parallel_pool, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/utils/parallel_pool.py:docstring of hyperspy.utils.parallel_pool.ParallelPool.is_multiprocessing:1: WARNING: duplicate object description of hyperspy.utils.parallel_pool.ParallelPool.is_multiprocessing, other instance in api/hyperspy.utils.parallel_pool, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/utils/parallel_pool.py:docstring of hyperspy.utils.parallel_pool.ParallelPool.setup:1: WARNING: duplicate object description of hyperspy.utils.parallel_pool.ParallelPool.setup, other instance in api/hyperspy.utils.parallel_pool, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/utils/parallel_pool.py:docstring of hyperspy.utils.parallel_pool.ParallelPool.sleep:1: WARNING: duplicate object description of hyperspy.utils.parallel_pool.ParallelPool.sleep, other instance in api/hyperspy.utils.parallel_pool, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/utils/parallel_pool.py:docstring of hyperspy.utils.parallel_pool.ParallelPool.timestep:1: WARNING: duplicate object description of hyperspy.utils.parallel_pool.ParallelPool.timestep, other instance in api/hyperspy.utils.parallel_pool, use :noindex: for one of them
/home/runner/work/hyperspy/hyperspy/hyperspy/utils/peakfinders2D.py:docstring of hyperspy.utils.peakfinders2D.find_local_max:11: WARNING: Inline strong start-string without end-string.
/home/runner/work/hyperspy/hyperspy/doc/dev_guide/testing.rst:6: WARNING: Duplicate explicit target name: "pytest documentation".
/home/runner/work/hyperspy/hyperspy/doc/user_guide/io.rst:5: WARNING: Duplicate explicit target name: "github repository".
```

### CODE REVIEW

**Comment by jlaehne** [comment]
nice!

**Comment by ericpre** [comment]
@thomasaarholt, do you want to review this PR?

**Comment by jlaehne** [comment]
@ericpre Can you fix the label warnings that now appear in the diff-view? Then it should be ready to merge from my point of view.

**Comment by ericpre** [comment]
Indeed after merging with with `RELEASE_next_patch`, we get a couple a nice warnings on github!! :)

**Comment by ericpre** [comment]
The warnings are fixed now!

**Pull request merged**
