### PR TITLE
Add missing He and H to elements database

### PR DESCRIPTION
**Pull request by francisco-dlp**
Helium and hydrogen were missing from our chemical element database.

### CODE REVIEW

**Comment by to266** [comment]
[He density](http://www.wolframalpha.com/input/?i=helium+density) is 1.785e-4 g/cm^3 (at 0° C) (yours is in kg/m^3)
[H density](http://www.wolframalpha.com/input/?i=hydrogen+density&lk=1&a=ClashPrefs_*Element.Hydrogen-) is 8.99e-5 g/cm^3 (for H2 at 0C). Again, yours is in kg/m^3 and slightly wrong (outdated maybe).

Also the energies can, in principle, be given with more significant figures, however I'm not sure it's relevant ( [24.587eV](http://www.wolframalpha.com/input/?i=helium+first+ionization+energy&lk=1&a=ClashPrefs_*Element.Helium.ElementProperty.FirstIonizationEnergy-) and [13.598eV](http://www.wolframalpha.com/input/?i=hydrogen+first+ionization+energy&lk=1&a=ClashPrefs_*Element.Hydrogen.ElementProperty.FirstIonizationEnergy-) for He and H respectively)

**Comment by francisco-dlp** [comment]
Well spotted! It should be fixed now.

**Comment by to266** [comment]
`Binding_energies` were not updated to higher precision

**Comment by francisco-dlp** [comment]
Done.

**Pull request merged**
