### PR TITLE
fix: readthedoc compiling

### PR DESCRIPTION
**Pull request by sem-geologist**
this should fix the issue with docs at #1139

it is simple snippet applied to the situation
as suggested by  the readthedocs.org faq

### CODE REVIEW

**Comment by sem-geologist** [comment]
I am not sure but there is very high probability that to the mocked list I should add also 'traits' as normally it also requires compiling... @francisco-dlp  should I add it?

**Comment by francisco-dlp** [comment]
I think that we need to add at least 'scipy', 'matplotlib', 'numpy', 'traits', 'traitsui','h5py'

**Comment by sem-geologist** [comment]
another important question would be: how to test it?

**Comment by francisco-dlp** [comment]
The easiest way is to merge it, if it doesn't work qw can unmerge it ;)

**Comment by sem-geologist** [comment]
ok, we are in trouble, it still tries to compile the numpy :/

**Comment by sem-geologist** [comment]
maybe it is this:

> If such libraries are installed via setup.py, you also will need to remove all the C-dependent libraries from your install_requires in the RTD environment.

from the faq of readthedoc...  thing is before we implemented setuptools, the `install_requires` was not even understood, now by setup tools it is taken into consideration.

**Comment by francisco-dlp** [comment]
[Still failing](https://readthedocs.org/projects/hyperspy/builds/4195919/)

This is not very urgent. We can fix it after releasing.

**Comment by sem-geologist** [comment]
I will register to readthe docs, and will experiment on separate branches, it is waste of precious travis osx and appveyor build power experimenting on the pullrequests and master of hyperspy

**Pull request merged**
